### ISSUE TITLE
windows我看release里面说ready soon，怎么一直没消息

### ISSUE THREAD

**Issue by lizhuangs** [oldj/SwitchHosts#102]
如题。我一直在用0.2版本的win版。但是发现mac都更新到了3.1了。3.1的release里面说ready soon，但是发现那是去年的事了。希望作者能更新一下win版。谢谢了。

**Comment by FFCZ** [comment]
同问，谢谢了

**Comment by iam3ddy** [comment]
+1. waiting for the windows version.

**Comment by xbotter** [comment]
期待

**Comment by ElfSundae** [comment]
ReadMe 里说了 v3 版是基于 MacGap 开发，而 MacGap 目前只支持开发 Mac 应用，所以该项目的 v3 版只有 Mac 版。
我试过 Windows 版，没发现有啥问题，可以正常使用，所以作者不再维护了。

ping @oldj 貌似 Windows 用户比较多，是不是考虑有空出个全平台兼容的 v4 版 😆

**Comment by oldj** [comment]
是的，要做到全平台兼容，就不能用 MacGap 了。
正在试验用 electron 改造全平台兼容的版本，唯一的问题是打包后的体积略大。基本完工了，还有些细节在调整，9 月上旬应该可以放出来。😆

**Comment by ElfSundae** [comment]
人才 👍  🎉  现在很多客户端都是用这个弄的。坐等更新。

**Comment by archonwang** [comment]
+1
等新版本。

**Comment by lizhuangs** [comment]
坐等更新喽~~~ :+1:

**Comment by gmaso** [comment]
+1

**Comment by justmd5** [comment]
@oldj 哪里有MacGap的学习案例，除了官网的残缺文档

**Comment by oldj** [comment]
使用 Electron 打包的 Windows 版发布了，[下载链接](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.0)，欢迎试用、反馈。🙂

**Comment by oldj** [comment]
@justmd5 我也没找到好的案例，主要是看官网的文档。MacGap 比较小巧，预置功能不多，如果要实现复杂功能需要用 Objective-C 扩展。

**Comment by lizhuangs** [comment]
马上试用~~~~happy~

**Comment by lizhuangs** [comment]
抓狂中，下载一半失败了，重新下载。。求百度云，360各种云盘地址有的走一个 @oldj 感谢~

**Comment by oldj** [comment]
[百度云盘](https://pan.baidu.com/share/link?shareid=150951&uk=3607385901#path=%252Fshare%252FSwitchHosts!%252FWindows) 上传了。

**Comment by ElfSundae** [comment]
不错 6666 👍

**Comment by ElfSundae** [comment]
@oldj  mac 版以前 remote 好像有个手动刷新的按钮，去掉了？

**Comment by oldj** [comment]
@ElfSundae 现在每次修改方案时，只要自动刷新时间不是“从不”（never），保存时就会刷新一次。刷新时右上角有“loading...”提示。

![image](https://cloud.githubusercontent.com/assets/416130/18275416/765003a6-7479-11e6-9a06-f3d493a10d64.png)

如果大家觉得需要手动刷新按钮，后面我会再加上。

**Comment by ElfSundae** [comment]
@oldj 嗯，这样挺好。加上也可以，更明显一点。

**Comment by archonwang** [comment]
Woooo, wait so long time and finally. Exciting~~

I will test it ASAP on windows 7. @oldj , thanks.
