### ISSUE TITLE
无法打开, win7

### ISSUE THREAD

**Issue by Gitzhaoyang** [oldj/SwitchHosts#105]
进程中存在, 但是应用程序中没有, 界面无法打开, 无论是管理员运行还是普通运行.

![image](https://cloud.githubusercontent.com/assets/12080364/18196968/30ccadd4-7127-11e6-9d41-054f5eb98e2e.png)

![image](https://cloud.githubusercontent.com/assets/12080364/18196975/49c97344-7127-11e6-8816-299cb34bd89a.png)

**Comment by oldj** [comment]
试试 [v3.2](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.0) 版？

**Comment by pengLeo** [comment]
清空C盘etc目录下hosts文件，杀掉进程，再次重启即可解决！
