### ISSUE TITLE
最新版的3.2无法导入之前的数据

### ISSUE THREAD

**Issue by lizhuangs** [oldj/SwitchHosts#106]
windows版本之前是0.2的，最新下载的3.2版本不能导入0.2版本的数据。2个版本导出来的文件格式不一样。

**Comment by lizhuangs** [comment]
另外最新版本的公共hosts配置在哪里，只看到一个system hosts，但是无法编辑，编辑器右上角有个锁的图标，点击也没反应。win10系统管理员打开的。

**Comment by oldj** [comment]
3.x 版和 0.2 版变化比较大，数据格式已经不一样了，暂时可能只能手工转一下。😁

3.x 版方案可以多选，因此没有必要单独放一个公共 hosts 方案，你可以把第一个或第二个方案做为公共的。那个 system hosts 是当前系统的 hosts 方案，那个右上角的锁图标表示当前 hosts 是只读的（鼠标悬停一会儿会有提示）。

**Comment by lizhuangs** [comment]
@oldj 感谢，已经用上了~
