### ISSUE TITLE
win10 64位，v3.2（4165） remote点击没反应

### ISSUE THREAD

**Issue by chongdianbao** [oldj/SwitchHosts#108]
new-》此处remote点了选不上

**Comment by oldj** [comment]
多谢反馈，是一个 bug，下个版本会修复。

**Comment by oldj** [comment]
试试 [v3.2.0.4159](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.0)，应该已经修复。也可以在 [百度网盘](https://pan.baidu.com/share/link?shareid=150951&uk=3607385901) 下载。
