### ISSUE TITLE
貌似自动刷新有bug

### ISSUE THREAD

**Issue by ElfSundae** [oldj/SwitchHosts#109]
新版自动刷新不起作用。mac版本。

**Comment by ElfSundae** [comment]
启动时的自动刷新、手动刷新都正常，app 运行过程中的自动刷新没用。

**Comment by ElfSundae** [comment]
看了下代码，agent 更新host内容后触发 change 事件，但是在自动刷新时 list 的 onChange 里获取到的 state.list 还是旧的，好像是 app 里的数据绑定没更新。删除一个自动刷新的 remote host 后，这个 host 还在刷新。

**Comment by oldj** [comment]
问题的确出在你说的位置，赞！👍

已修复，见 [v3.2.0.4160](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.0) 。

**Comment by ElfSundae** [comment]
Totally Fix 🎉
