### ISSUE TITLE
win10切换HOSTS失败，没有修改权限

### ISSUE THREAD

**Issue by yaqiShao** [oldj/SwitchHosts#110]
求助。
![image](https://cloud.githubusercontent.com/assets/22256690/18608301/3944268e-7d18-11e6-8776-b986642796d4.png)

安装的是绿色免安装版本的swithhosts，尝试了以管理员身份运行，也不行。
在etc\hosts直接以TXY文本打开进行修改，是可以修改HOSTS的。

**Comment by archonwang** [comment]
请使用管理员权限启动该程序。

**Comment by fengjx** [comment]
使用管理员权限启动该程序，还是无法解决

**Comment by archonwang** [comment]
有个笨办法，可以试试，将host文件的权限和所有权都重新赋值即可。
