### ISSUE TITLE
i can not open it on my x86 windows system

### ISSUE THREAD

**Issue by ocxco** [oldj/SwitchHosts#111]
能不能提供一个x86的版本呢，现在的版本都是x64的，不能打开

**Comment by oldj** [comment]
根据 electron-packager 的说明打包了一个 [ia32 版本](https://github.com/oldj/SwitchHosts/releases/download/v3.2.0/SwitchHosts-win32-ia32_v3.2.0.4160.zip)，我现在没有 x86 环境，没有测试，不知是否可用？

**Comment by ocxco** [comment]
好的，thanks, 现在手上没有x86的机器，我明天试试。

**Comment by ocxco** [comment]
好的，thanks, 现在手上没有x86的机器，我明天试试。
