### ISSUE TITLE
关于“允许方案多选”，能否加一个开关配置？【MAC】

### ISSUE THREAD

**Issue by Shangshj** [oldj/SwitchHosts#113]
现在每次切换host都需要点击、选择两次，先把旧的关闭再把新的打开，希望能加一个开关配置。

**Comment by oldj** [comment]
是希望增加一种单选模式么？

**Comment by oldj** [comment]
可以试下 3.2.0 (4165) 版或更新版本，设置面板中增加了单选、多选选项。

![image](https://cloud.githubusercontent.com/assets/416130/18812898/301c9a24-8316-11e6-8b26-e96bec2fc47c.png)

下载地址：[github release](https://github.com/oldj/SwitchHosts/releases/) 或 [百度云盘](https://pan.baidu.com/s/1inED1) 。

**Comment by Shangshj** [comment]
谢谢，太完美了！
