### ISSUE TITLE
[Bug] 新建列表时数据污染

### ISSUE THREAD

**Issue by ElfSundae** [oldj/SwitchHosts#114]
版本 Mac 3.2.0 (4160)

只要打开过某列表的编辑界面，这时再新建列表，新列表的内容就是刚才打开过编辑的那个列表的内容。

不管是新建本地还是新建远程，内容都是上一次编辑界面显示的内容。即便上次进入编辑界面删除了那个hosts，新建时依然是那个hosts内容。

**Comment by oldj** [comment]
感谢反馈。3.2.0 (4165) 中应该已经修复。

下载地址：[github release](https://github.com/oldj/SwitchHosts/releases/) 或 [百度云盘](https://pan.baidu.com/s/1inED1) 。🙂

**Comment by ElfSundae** [comment]
已修复 👍
