### ISSUE TITLE
3.2.0 (4165) 切换开关有问题

### ISSUE THREAD

**Issue by mycoin** [oldj/SwitchHosts#118]
已开启的分组开关按钮没有变化：
![image](https://cloud.githubusercontent.com/assets/1845440/19225781/950dadaa-8ed4-11e6-80b1-a8d82f8281da.png)

如图，实际上 global 分组是开启的

btw Version 3.1.1 (2882) 没有问题

**Comment by mycoin** [comment]
操作系统 MacOS 10.12 (16A323)

**Comment by oldj** [comment]
关闭程序再打开正常了么？

暂时没有重现，我再关注下…

**Comment by spwei** [comment]
同样的问题，系统：MacOS 10.12.1 Beta (16B2548a)

**Comment by spwei** [comment]
使用ENV=dev /Applications/SwitchHosts\!.app/Contents/MacOS/SwitchHosts\!模式打开，然后再关掉Console，开关显示就可以正常了
切换过程中有个提示：
AfterCmdError:

No matching processes were found

**Comment by brucejcw** [comment]
@spwei 
ENV=dev /Applications/SwitchHosts!.app/Contents/MacOS/SwitchHosts!  
```
event not found: .app/Contents/MacOS/SwitchHosts!
```
你有这问题么

**Comment by brucejcw** [comment]
补充一下@spwei 的, 我没法直接run这个命令, 卡在.app那里报错, 
```
zsh: event not found: .app/Contents/MacOS/SwitchHosts!
```
所以我先  
cd  /Applications/SwitchHosts!.app  
再cd到Contents/MacOS  
ENV=dev ./SwitchHosts!  

算是成功了

**Comment by spwei** [comment]
#147

**Comment by spwei** [comment]
#147 这个也可以关闭了

**Comment by spwei** [comment]
@oldj 这个也可以关闭了

**Comment by oldj** [comment]
好的。
