### ISSUE TITLE
[Bug] 网络错误信息被写入host了

### ISSUE THREAD

**Issue by ElfSundae** [oldj/SwitchHosts#119]
3.2.0 (4165)
macOS 10.11.6

无网络时刷新 remote host 失败，错误信息被写入host了。

> Error: getaddrinfo ENOTFOUND xxx.com

**Comment by oldj** [comment]
好像改为“如果更新失败，则保持原内容不变”比较合理，是吧？

**Comment by ElfSundae** [comment]
嗯 是

**Comment by oldj** [comment]
改了，试试 [v3.2.0.4167](https://pan.baidu.com/share/link?shareid=150951&uk=3607385901#list/path=%2Fshare%2FSwitchHosts!&parentPath=%2Fshare) 或更新版本。

新版本里有网络错误时 host 内容不会被替换，同时会有两处提示：

1、icon 变为感叹号图标

![image](https://cloud.githubusercontent.com/assets/416130/19315541/ab1fd03e-90d0-11e6-8d6b-8e7b42b54880.png)

2、编辑窗口顶上有浮层提示

![image](https://cloud.githubusercontent.com/assets/416130/19315568/c4e0da18-90d0-11e6-9bc4-5b310a8468be.png)

**Comment by ElfSundae** [comment]
👍
