### ISSUE TITLE
启动时，任务栏最小化的选项

### ISSUE THREAD

**Issue by Yannis520** [oldj/SwitchHosts#121]
我感觉有必要添加这个功能，（or有相关配置参数么，也可以。我加进桌面快捷方式里），因为不是每次都 是要现在编辑的，而已直接应用啦。设置开机自启，但开机又弹出来这很不人性化呀。

**Comment by oldj** [comment]
目前的版本中已有这个功能，可以试试 [v3.3.0](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.0) 。
