### ISSUE TITLE
强烈建议加入查找功能

### ISSUE THREAD

**Issue by 20131415** [oldj/SwitchHosts#123]
强烈建议加入查找功能    强烈建议加入查找功能     强烈建议加入查找功能

**Comment by oldj** [comment]
现在有查找功能哦，点左侧工具栏下方的放大镜图标，输入搜索关键字就可以。

还可以用“*”模糊查找，如果以“/”开头则是使用正则表达式查找。

<img width="602" alt="switchhosts_" src="https://cloud.githubusercontent.com/assets/416130/19502119/2fa17bf8-95dd-11e6-961e-44c20e3364ba.png">

**Comment by JulienBrks** [comment]
这个查找功能可以支持按回车，然后选中焦点么
