### ISSUE TITLE
hosts 最后一行是什么意思?

### ISSUE THREAD

**Issue by hankji** [oldj/SwitchHosts#124]
192.168.56.1 windows10.microdone.cn
总是在最后一行添加这条记录...
是什么意思

**Comment by oldj** [comment]
这不是 SwitchHosts! 加的哦，应该是其他软件自动改了 hosts。

**Comment by hankji** [comment]
我是从官方git这里下载的...
难道中招了?

**Comment by hankji** [comment]
知道原因了..
银联插件的问题 
关闭
