### ISSUE TITLE
有没有分组切换功能的？

### ISSUE THREAD

**Issue by anshao** [oldj/SwitchHosts#125]
比如我有两个HOST TITLE

[TEST]A
[TEST]B

当我开启[TEST]A时，自动停用[TEST]B
反之亦然。

=============================

点击托盘进行hosts切换
![image](https://cloud.githubusercontent.com/assets/1137539/19594434/8a7b57c0-97b7-11e6-881e-13b72e98cb1b.png)
会弹出下面这个窗，是正常的么？
![image](https://cloud.githubusercontent.com/assets/1137539/19594463/bc87cfe6-97b7-11e6-81ee-2847e6585aa4.png)

直接在程序界面切换不会弹这个窗

**Comment by oldj** [comment]
暂时没有分组功能。

可以在设置里切换为“单选模式”，实现类似效果，见下图：

<img width="534" alt="switchhosts_" src="https://cloud.githubusercontent.com/assets/416130/19594449/a2718e62-97b7-11e6-9667-0074acbec37b.png">
