### ISSUE TITLE
win系统非安装c盘，导致无法找到hosts文件

### ISSUE THREAD

**Issue by tltwuyu** [oldj/SwitchHosts#128]
win系统非安装c盘，导致无法找到hosts文件。能不能改用环境变量加路径去找host文件？

**Comment by wulechuan** [comment]
不知道可否采用Windows原始配备的环境变量“%windir%”，而非写死的C:\Windows。

**Comment by oldj** [comment]
[v3.2.1](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.1) 已做了判断，会先读取环境变量 `%windir%` 的值作为系统安装目录。
