### ISSUE TITLE
能不能进行分组啊。。。

### ISSUE THREAD

**Issue by txiaocao** [oldj/SwitchHosts#129]
能不能进行分组啊。。。

**Comment by nottellyou** [comment]
![image](https://cloud.githubusercontent.com/assets/8598743/23336813/8ad1de0c-fc15-11e6-92cb-d1e111ebc9ef.png)

你还想怎样切环境

**Comment by txiaocao** [comment]
最好能无限级啊，或者多增加一级。
分类1
        分类2
                方案
        分类3
            方案

**Comment by oldj** [comment]
@txiaocao 你有多少个 hosts 方案呢？貌似大部分用户 hosts 方案数量在 20 个以内，似乎没有必要做嵌套目录…
