### ISSUE TITLE
希望增加分组功能,每个组里只有一个可以host 方案生效.

### ISSUE THREAD

**Issue by xjl456852** [oldj/SwitchHosts#135]
我用的这个是新版本v3.2.0
我的host中,
有一个是作为基础的host配置.
其它的是作为动态切换的配置.
我选择单选模式和多选模式都不合适.
有一个基础的配置是必须一直打开的,其它的动态切换的那些是需要单选的.
所以我觉得可以加入分组的功能.
一个组里只有一个host 方案生效,也就是单选模式.
在分组外的host 方案,可以是多选模式.可以多个设置同时打开.
谢谢

**Comment by wulechuan** [comment]
我认为其实可以参考GasMask的所谓“Combined”模式。
GasMask: https://github.com/2ndalpha/gasmask

**Comment by yangg** [comment]
同求分组功能。

**Comment by takashiki** [comment]
求分组功能 +1。

**Comment by oldj** [comment]
试试 [v3.3.0](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.0) ，新增了分组功能。

**Comment by yangg** [comment]
@oldj 分组功能貌似没效果，点击切换还是只是增加了选中，同组内的其它没取消选中

**Comment by yangg** [comment]
分组直接跟之前一样弄成树状结构不是挺好的么？现在这种也不直观啊

**Comment by oldj** [comment]
@yangg “分组”可能是有点让人疑惑，可能文案改为叫“组合”会更好一些？

**Comment by iamybj** [comment]
不要增加不必要的功能。
多选功能已经足够了。

**Comment by zgr0629** [comment]
抱歉在2019年又回复这个主题，但是我搜遍了整个issues都没有看到相应的解决方案。
这个issues的题主说的问题可以说是完全满足我的需求。

实际情况是手头经常会有多个项目，每个项目多个环境：

项目1
	环境1
	环境2
项目2
	环境3
	环境4
	环境5
项目3
	环境6
	环境7
	环境8
	环境9

首先软件有“多选模式”，我可以随意勾选每个项目的环境，非常好。
但当我需要切换某个项目的环境时，我就蛋疼了，必须得点四下：1.点击图标打开menu，2.选择新环境（菜单消失），3.再次点击图标打开menu，4.取消旧环境。

如果想要只点两下，用单选模式，可以用“组合”。组合是把多个host绑定到一起，使其同时生效，同时失效。但这个不太满足我的需求，如果要强行用“组合+单选模式”。理论上我得写2*3*4=24个组合。。。然后从24+2+3+4=33个中选择一个。。。

我想了三种方案：
1.如题主所说新增分组功能，分别设置每个分组内是单选/多选，就完美解决这个问题了。
2.当是多选模式时，点击list后只改变勾选，菜单不要自动消失，点击菜单外面，菜单才消失。单选模式时点击就立即消失，可以节省一次点击。
3.按住command点list，菜单不要消失，这样也可以少点一次。

2019再提一下这个需求，希望作者考虑考虑，为我等多项目的同学解决懒癌问题，不想每次切换环境那么麻烦。感觉后两种方案，代码改动会比较小？

ps：目前appstore里的iHost就是这么实现的，可是他又没有“自定义命令”的功能，不能hook，所以没有用它

**Comment by oldj** [comment]
感谢详细反馈，下个版本中会添加【文件夹】功能，每个文件夹内可单独设置单选、多选。

**Comment by oldj** [comment]
文件夹功能在 [v3.5.0](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.0) 中添加了，欢迎下载试用。试用之前最好先备份一下原有数据。🙂
