### ISSUE TITLE
执行「导出」功能后 host 开关配置异常

### ISSUE THREAD

**Issue by ElfSundae** [oldj/SwitchHosts#138]
Version 3.2.0 (4169)
macOS 10.11.6

执行「导出」功能后，在主界面点击任意一个列表项的名字（不用点开关按钮），此时列表中的开关就全被「关闭」了。

问题出现时，托盘图标菜单里的开关正常，系统 hosts 内容正常。
问题出现后，如果重启 app 会恢复正常。
问题出现后，如果在主界面或托盘图标切换 host ，执行「导出」功能前的 host 开关配置将被本次操作覆盖。

上个版本 4167 偶然发现了这个问题，刚更新到 4169 还是存在这个 bug 。

**Comment by oldj** [comment]
这个问题在 [v3.2.2](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.2) 中应该修复了。

**Comment by ElfSundae** [comment]
已修复:+1:
