### ISSUE TITLE
win10 下任务栏通知栏上的图标有3个好麻烦啊。

### ISSUE THREAD

**Issue by liurongwei** [oldj/SwitchHosts#142]
![image](https://cloud.githubusercontent.com/assets/1342352/21535056/eac9fe0a-cdaa-11e6-97bc-85554aff69ea.png)

**Comment by chengaomin** [comment]
建议只能开启一个此软件，免得乱了

**Comment by chengaomin** [comment]
@oldj 建议使用makeSingleInstance方法，同一时刻最多只会有一个实例
https://github.com/electron/electron/blob/89feefac2cff7784788944257c08e5fc4a20da6d/docs-translations/zh-CN/api/app.md#appmakesingleinstancecallback

**Comment by oldj** [comment]
试试 [v3.2.2](https://github.com/oldj/SwitchHosts/releases) 或更新版？

**Comment by chengaomin** [comment]
嗯，最新版本只运行一个实例了。
