### ISSUE TITLE
在macOS托盘的弹出菜单中打开或关闭一个配置，会导致其上方的另一个配置被关闭

### ISSUE THREAD

**Issue by wulechuan** [oldj/SwitchHosts#143]
系统：macOS 10.12.2 (16C68)

![image](https://cloud.githubusercontent.com/assets/4899190/21923504/77d2768c-d9af-11e6-8a48-38728ca3afb1.png)

上图中，我每次点击第3号配置，即“某某某: Vagrant虚拟机”，不论是将其开启（打上勾）还是关闭（去掉勾），都会引起其上方的第2号配置被关闭（去掉勾）。

补充：
注意到：第2号配置文件结尾没有空行，或许与此有关。

**Comment by wulechuan** [comment]
果然，如果故意为上例中第2号配置文件添加结尾空行，那么：
如果不退出SwitchHosts!，则上述不正常行为依然存在；
如果先行退出SwitchHosts!再重新运行之，则上述不正常行为消失。

**Comment by oldj** [comment]
我这儿似乎不能重现…

不知你运行的是哪个版本的 SwitchHosts! 呢？

**Comment by wulechuan** [comment]
很抱歉，我无从查询我目前使用的版本。不过既然您的版本不能重现，很可能我运行的不是最新的版本。

**Comment by wulechuan** [comment]
更新：
根据我下载的安装包，当时出现bug的版本应该是：SwitchHosts-macOS-x64_v3.2.0.4178
