### ISSUE TITLE
在GUI中无从查询当前版本。

### ISSUE THREAD

**Issue by wulechuan** [oldj/SwitchHosts#145]
用户可能需要知道当前运行的版本。

**Comment by wulechuan** [comment]
勘误：在macOS下，先将SwitchHosts!切换至允许Docker的模式，即可通过菜单查阅SwitchHosts!的版本信息；而在无Docker模式，则确实无从查阅SwitchHosts!的版本信息。望改进！

我不熟悉macOS，但在工作中被迫使用它，所以误会了SwitchHosts!，抱歉！

**Comment by oldj** [comment]
明白了，这是个问题，感谢反馈！

**Comment by oldj** [comment]
[v3.2.3](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.3) 中增加了版本号的显示：

<img width="195" alt="item-0_and_item-0" src="https://cloud.githubusercontent.com/assets/416130/22646058/5d3763b0-eca5-11e6-9ad3-7f8e9f881144.png">

<img width="489" alt="switchhosts_" src="https://cloud.githubusercontent.com/assets/416130/22646031/3a8221a2-eca5-11e6-9fa0-ce95fb17228b.png">

现在应该能很方便地了解当前版本号了。:)

**Comment by wulechuan** [comment]
非常感谢！再接再厉！
