### ISSUE TITLE
开关不起作用

### ISSUE THREAD

**Issue by gejiawen** [oldj/SwitchHosts#147]
环境：
macOS 10.12.2
SwitchHost！v3.2.3 (4264)

点击开关，输入sudo密码之后，开关没有开启。其他功能都正常。

**Comment by lzou** [comment]
mac osX   
Version 3.1.2 (3216)   开关不起作用

**Comment by lzou** [comment]
解决了，重启下软件就好了

**Comment by lisi806** [comment]
macOS 10.12.3
SwitchHost！v3.2.3 (4264)
遇到同样的问题，开关点击没反应，不知道host有没有切换。

**Comment by oldj** [comment]
这个问题在 [最新的版本](https://github.com/oldj/SwitchHosts/releases) 中还存在吗？

**Comment by lisi806** [comment]
3.3.2解决了
