### ISSUE TITLE
[macOS]在apply新的hosts设定时，一旦输入错误的根密码，则导致之后的app始终无法正常使用

### ISSUE THREAD

**Issue by imeteora** [oldj/SwitchHosts#149]
步骤：
1、APP启动之后，开始打开（或关闭）某一个hosts设定组开关按钮，此时会弹出 密码输入框。 
2、如果在此时输入错误的密码，则会有错误提示框，点击 确认 按钮之后，相应的host设定组就不能添加到系统hosts文件里面。
3、再次点选打开（或关闭）某个host设定组的开关按钮，仍然会提示密码错误，无法修改系统hosts文件
。即因为第一次密码输入错误，则永远无法apply hosts里面的设定。除非退出并重新启动之后，重复第一步操作，并输入正确密码为止。

期待：
系统根密码输入错误之后，报错误提示。二次打开设定的时候，因为在提示错误之后，允许用户二次输入根密码的机会和权力。

环境:
macOS 10.12
SwitchHosts Version 3.2.3 (4264)

**Comment by oldj** [comment]
感谢反馈，这个问题将会在下一个版本（v3.3.0）中修复。

**Comment by oldj** [comment]
[v3.3.0](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.0) 发布了。:-)
