### ISSUE TITLE
在线host中有一个条目希望屏蔽掉，应该怎么办？

### ISSUE THREAD

**Issue by cancelpj** [oldj/SwitchHosts#150]

**Comment by oldj** [comment]
似乎暂时没有很方便的方法。

一个曲折一点的方案是**覆盖**，在它的上方再建一个 host 方案，里面放一条那个条目的值。重复的 host 方案以先出现的为准，把你希望的条目规则放它前面，就可以把这条规则**覆盖**掉了。

比如在线方案里有一条 `1.1.1.1 a.com`，但是你希望 `a.com` 指向  `2.2.2.2`，那么你可以在「在线方案」前面建一个新方案，内容为 `2.2.2.2 a.com`。

<img src="https://cloud.githubusercontent.com/assets/416130/23102884/6105a12c-f6ec-11e6-9b4d-e69e62df9516.png" width="445">

**Comment by cancelpj** [comment]
哈，谢谢，以先出现的条目为准，这方法用来覆盖是挺不错的。只不过只能针对固定ip的域名。
