### ISSUE TITLE
你好，oldj，弱弱的问一下，3.X版本和0.2.2版本多了那些功能？

### ISSUE THREAD

**Issue by nottellyou** [oldj/SwitchHosts#153]
弱弱的问一下，3.X版本和0.2.2版本多了那些功能？

win版本以前是9M，现在是50多M。体积大了那么多。

**Comment by oldj** [comment]
核心功能没有大的变化，主要是方案从单选改为了允许多选。

体积增加的主要原因是原来是用 [wxPython](https://wxpython.org/) 做的，3.X 版改成用 [Electron](https://electron.atom.io/) 做了，后者打包时会包含 Node.js 的运行环境以及一个浏览器内核，所以体积变大了很多。🤣
