### ISSUE TITLE
模式选择体验问题

### ISSUE THREAD

**Issue by Sherljohn** [oldj/SwitchHosts#156]
3.2.3 版本有两种选择模式：单选和多选。
1. 单选模式下，假设我有5个方案，每个方案都会共用一些hosts，那我在5个方案都写上这些共用的hosts，如果我要修改某个共用的hosts，那我得修改5个方案。可否新增一个特殊的公共的方案，让我不管切换到我的哪个方案，这个公共的方案都是生效的？
2. 多选模式下，多选模式下其实一定程度上解决了单选模式下公共hosts的问题，因为可以把公共的hosts新建一个方案，切换其他方案的时候，该公共的方案可以保持开启的状态。但是多选模式下有另一个体验的问题，那就是我每次切换方案都要点击两次——我需要先把我不想要的方案关闭，然后再把我想要的方案开启。而单选模式下并不会出现这个问题。
以上纯属个人体验问题，如果作者有时间，希望可以考虑下~

**Comment by oldj** [comment]
感谢反馈，正在计划开发“组合”功能，允许将多个方案组合成一个（相当于多选，但只有一个开关），应该可以解决这个问题。

**Comment by crazyxhz** [comment]
@oldj 现在是否支持多分组，组内互斥的功能了呢？
