### ISSUE TITLE
mac下复制粘贴无效

### ISSUE THREAD

**Issue by icanfly** [oldj/SwitchHosts#157]
如题，非常喜欢这款软件，但是有个比较老火的问题，就是mac下的复制与粘贴功能不可用啊，这个很蛋疼啊，比如有一堆的host需要设置的时候一个一个设置很老火啊，老板，有解决办法吗，我用的3.1和3.2.2的版本都不行啊。跪求解决方案。

**Comment by oldj** [comment]
哪里的复制粘贴呢？编辑器里应该是可以复制粘贴的啊。

**Comment by icanfly** [comment]
不管是从编辑器里面复制和粘贴，还是从外面的copy到switchhost里面的进行粘贴，均失效。我用的os版本是10.12.1

**Comment by icanfly** [comment]
无任何反应

**Comment by zhangqitao1** [comment]
我也是，，复制粘贴不可用，同桌就可以

**Comment by icanfly** [comment]
楼主，跪求解决，，，非常好的一款软件，但是就是mac下用起来有问题啊，能修复么。。。啊啊啊，用起来捉急啊。

**Comment by icanfly** [comment]
解决了，是自己的问题：系统偏好设置－键盘－快捷键－恢复成默认，之前不知道是不是做过变更，现在变成command+c,command+v复制粘贴就可以了。666
