### ISSUE TITLE
win10无法切换hosts

### ISSUE THREAD

**Issue by ZTielong** [oldj/SwitchHosts#158]
开启时以管理员权限运行，并且设置了administrator账户以及当前登录账户对hosts的完全控制权限，但是依然报   没有修改 %hostsPath% 的权限  ，还望解答，谢谢！

**Comment by xinghailong** [comment]
如果安装了360安全卫士 会有这个问题。需要把hosts文件在360里增加到信任列表中

**Comment by ZTielong** [comment]
已经解决了，的确是由安全软件引起的，我用的是卡巴斯基，分享一下解决方案：switchhosts默认被被分为了低限制组，是不被允许修改系统核心设置的，把switchhosts修改为受信任组就可以修改，但是卡巴斯基依然会监听hosts文件变动，修改时报毒，最后还是需要在文件监听里设置hosts为排除项。

**Comment by oldj** [comment]
感谢，已将解决方案添加到 [常见问题](https://github.com/oldj/SwitchHosts/wiki/FAQ) 列表。
