### ISSUE TITLE
0.2.2.1785

### ISSUE THREAD

**Issue by sports98** [oldj/SwitchHosts#159]
> 系统：Windows 10 
![image](https://cloud.githubusercontent.com/assets/3828455/24041056/ccd34e5e-0b46-11e7-8d4b-354f1442d0c4.png)
> 版本：0.2.2.1785
> 问题：可以启动多实例。

win7的时候使用还都正常，不知道win10后我的系统为什么可以启动多个switchHost.导致有时候数据重复被覆盖。

**Comment by oldj** [comment]
0.2 版已经不再维护了，试试 [新版本](https://github.com/oldj/SwitchHosts/releases) ？

**Comment by sports98** [comment]
哈，非常感谢。更新新版本使用了
