### ISSUE TITLE
切换host后，chrome不能及时生效

### ISSUE THREAD

**Issue by haoxunwang** [oldj/SwitchHosts#160]
切换host后，chrome(57.0.2987.110 (64-bit))浏览器不能及时生效，Safari浏览器可以，有解决的方法吗？

**Comment by oldj** [comment]
Chrome 目前暂时没有好办法，可以等一会儿（60秒或120秒），或者按下面的方式手动清除缓存：

访问 `chrome://net-internals/`，点击右上角下拉菜单中的 `Flush sockets` ，一般可以马上生效。

如下图：

![image](https://cloud.githubusercontent.com/assets/416130/24230644/1683c86c-0fbb-11e7-9b08-3a4d8d637bb4.png)

**Comment by haoxunwang** [comment]
确实有效，谢谢！

**Comment by wuliupo** [comment]
很高兴遇见了
