### ISSUE TITLE
利用Command-Z倒退编辑内容，会将其它方案完全覆盖当前编辑的方案。

### ISSUE THREAD

**Issue by wulechuan** [oldj/SwitchHosts#161]
本人偶然遇到此问题，但不情愿（不敢）尝试重现之。抱歉。
大至现象描述：
我当时正在着重编辑甲方案，但时不时切换到乙方案做一些相应改动。中途某次回到甲方案时，按下Command-Z组合键，发现乙方案的内容完全覆盖了甲方案。我不得不找出备份文本文件，手工恢复。

祝好！

**Comment by LKGin** [comment]
好吧经常用CTRL+z的我踩坑了

**Comment by oldj** [comment]
感谢反馈，会在下一个版本修复。
