### ISSUE TITLE
windows 10 build 15063 使用时出现 “请以管理员身份运行switchhosts”

### ISSUE THREAD

**Issue by jian555gg** [oldj/SwitchHosts#163]
如题，已经使用管理员身份运行了，但第一次使用时没有出现此提示。

**Comment by Auth8** [comment]
试下这个方法[Win10右键添加获取管理员权限](http://blog.sina.com.cn/s/blog_9ed014090102w4b2.html)

**Comment by Auth8** [comment]
@jian555gg 可以试一下这个方法  [Win10右键添加获取管理员权限](http://blog.sina.com.cn/s/blog_9ed014090102w4b2.html)
