### ISSUE TITLE
Windows下的构建问题

### ISSUE THREAD

**Issue by dongsir** [oldj/SwitchHosts#165]
> 首次执行此命令可能需要花费较多时间（需要下载对应的构建文件），也可先手动下载对应的发布版本（淘宝镜像），手动保存到 ~/.electron 目录下。更多信息请参考 Electron 文档。

Windows中，手动下载的包应该放在哪个目录中呢？
每次构建好像都会在C:\Users\xxx\AppData\Local\Temp中生成electron-tmp-download-xxxx-xxxxxx的文件夹,用来存放electron对应版本的zip.

另外执行npm run pack-win后，并没有执行打包，而是下面的提示.是因为electron没有被下载引起的吗？
```
PS D:\WorkSpace\Vue\SwitchHosts> npm run pack-win

> switchhosts@3.2.3 pack-win D:\WorkSpace\Vue\SwitchHosts
> gulp pack --platform=win64

{ _: [ 'pack' ],
  platform: 'win64',
  '$0': 'node_modules\\gulp\\bin\\gulp.js' }
[14:22:54] Using gulpfile D:\WorkSpace\Vue\SwitchHosts\gulpfile.js
[14:22:54] Starting 'pack'...
start packing, v: 3.2.3.4265 ..

# for windows x64
electron-packager ./app 'SwitchHosts!' --platform=win32  --arch=x64 --version=1.4.15 --overwrite --asar=true --prune --
con=./assets/app.ico  --ignore=node_modules/.bin --ignore=.git --ignore=dist --ignore=node_modules/electron-* --out=dis
 --app-version=3.2.3 --build-version=4265

end pack.
[14:22:54] Finished 'pack' after 48 ms
```

**Comment by dongsir** [comment]
将上述electron-packager ./app 'SwitchHosts!' --platform=win32  --arch=x64 --version=1.4.15 --overwrite --asar=true --prune --
con=./assets/app.ico  --ignore=node_modules/.bin --ignore=.git --ignore=dist --ignore=node_modules/electron-* --out=dis
 --app-version=3.2.3 --build-version=4265
通过node 直接执行，在下载electron之后会报错，再执行一次后就能正常构建了。

**Comment by oldj** [comment]
Windows中，手动下载的包放在当前用户主目录下的 `.electron` 目录下，例如：

```
cd %HOMEPATH%
mkdir .electron
cd .electron
```

比如 Windows 10 下，如果你的用户名是 MyName ，那么对应的目录是：`C:\Users\MyName\.electron`。
