### ISSUE TITLE
brew cask install 一个3.2, 你这又出来一个3.3

### ISSUE THREAD

**Issue by iamybj** [oldj/SwitchHosts#166]
能不能发布新版本时，顺便把 cask 也更新一下。
原来那个cask还有错误。

**Comment by oldj** [comment]
我似乎没有发布过 brew cask 安装的版本，`brew cask search` 也没有找到，能具体一点么？

**Comment by iamybj** [comment]
macbook:~ apple$ brew cask info switchhosts
switchhosts: 3.2.3.4264
https://oldj.github.io/SwitchHosts/
/usr/local/Caskroom/switchhosts/3.2.3.4264 (170B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/switchhosts.rb
==> Name
SwitchHosts!
==> Artifacts
SwitchHosts!-darwin-x64/SwitchHosts!.app (app)

**Comment by ElfSundae** [comment]
[Casks/switchhosts.rb](https://github.com/caskroom/homebrew-cask/commits/14129aaa2c2ae751fdfa436329833930998706d1/Casks/switchhosts.rb)
一个老外一直在维护 😄

**Comment by oldj** [comment]
好神奇… 😃

**Comment by ElfSundae** [comment]
# SwitchHosts 的国际市场很开阔呀 💯

**Comment by oldj** [comment]
看来以后更新时要多写点英文说明。😆

**Comment by iamybj** [comment]
你那首页上没写上 brew cask install.

**Comment by oldj** [comment]
[加上了](https://github.com/oldj/SwitchHosts/blob/master/README.md)，感谢 @iamybj 。
