### ISSUE TITLE
明文保存密码在_restart_mDNSResponder.sh 不安全？

### ISSUE THREAD

**Issue by jixiangqd** [oldj/SwitchHosts#169]

**Comment by oldj** [comment]
疏忽了，我改一下，执行完后马上删除 _restart_mDNSResponder.sh 临时文件。

这个问题是 v3.3.0 版引入的，[之前的版本](https://github.com/oldj/SwitchHosts/blob/v3.2.3/app/ui/agent.js#L147)中 _restart_mDNSResponder.sh 里没有写入密码。

**Comment by oldj** [comment]
试试 [v3.3.1](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.1) ？

**Comment by jixiangqd** [comment]
效率真高，赞一个

**Comment by oldj** [comment]
涉及安全的问题，必须优先处理。🙂
