### ISSUE TITLE
这工具，是纯js实现的吗？？？

### ISSUE THREAD

**Issue by noear** [oldj/SwitchHosts#173]
好有才啊。

**Comment by noear** [comment]
我以为你是用Qt搞的。能不能分享一下，我也想开发一个跨平台的工具：）

**Comment by oldj** [comment]
第一版和第二版是用 wxPython 搞的，现在的版本是基于 [Electron](https://electron.atom.io/) 的，有前端基础上手 Electron 应该比较容易，你可以看下 [Electron](https://electron.atom.io/) 官网的说明。

Electron 优点是可以跨平台，还可以使用 Web 技术开发，缺点是最后打包出来的文件体积比较大。:-)

**Comment by noear** [comment]
你这个工具太好用，太方便了：）

**Comment by noear** [comment]
如果 Electron 能支持web打开技术。可能它要内嵌一个 js 内擎，或者一个浏览器内核。所以体积就大了：）

**Comment by oldj** [comment]
感谢支持～ 😆
