### ISSUE TITLE
遇到一个非常奇怪的问题

### ISSUE THREAD

**Issue by gejiawen** [oldj/SwitchHosts#175]
开启 switchhost 的一个配置项A，然后再关闭配置项A开启配置项B，chrome发出的请求依然是A的绑定，在本地shell中curl的结果是B的绑定。

不知道有没有其他人遇到过这种情况

**Comment by StevenSun121** [comment]
修改host之后 我的Chrome也是这样，应该是Chrome的问题，不是SwitchHosts的问题

**Comment by oldj** [comment]
这是 Chrome 的缓存引起的，暂时似乎没有方便的办法，需要等一会儿或手动刷新，可以参见 #160 。

**Comment by lianer** [comment]
@oldj 可以重启网络服务吗？这样所有 TCP 连接就强制断开了。

**Comment by oldj** [comment]
@lianer 你用的是什么操作系统呢，如果是 macOS，其实是会尝试[重启网络服务](https://github.com/oldj/SwitchHosts/blob/db1191474bce534c8a57f014d4677ab51c953dec/app/server/applyAfter_Unix.js#L17)，不过对 Chrome 等浏览器来说似乎仍然有缓存。不知道有没有其他更好的命令……

另外，你也可以在设置中添加“自定义命令”来重启网络服务。

![image](https://user-images.githubusercontent.com/416130/30264773-8d7c9650-970c-11e7-8d3d-c6c1679444ba.png)
