### ISSUE TITLE
npm start error 

### ISSUE THREAD

**Issue by pengjielee** [oldj/SwitchHosts#177]
localhost:SwitchHosts pengjielee$ npm start

> switchhosts@3.3.1 start /Users/pengjielee/study/SwitchHosts
> electron app

/Users/pengjielee/study/SwitchHosts/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/Users/pengjielee/study/SwitchHosts/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pengjielee/study/SwitchHosts/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:570:32)

npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! switchhosts@3.3.1 start: `electron app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the switchhosts@3.3.1 start script 'electron app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the switchhosts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs switchhosts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls switchhosts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pengjielee/study/SwitchHosts/npm-debug.log

**Comment by oldj** [comment]
> Error: Electron failed to install correctly, please delete node_modules/electron and try installing again

看错误提示是 Electron 安装不正确，可以把 `node_modules/electron` 目录删除，再重新 `npm i` 安装一下试试？
