### ISSUE TITLE
遇到的两个问题

### ISSUE THREAD

**Issue by fengyiway** [oldj/SwitchHosts#179]
1、点击配置项的开关，并立即操作当前配置项中的某个host，等待几秒后，操作的那个host状态会回退。
2、开启一个默认关闭的配置项，然后开启当前配置项中的某个host，关闭当前配置项，开启的那个host未被正常取消。（验证方式，ping host）

SwitchHosts版本：3.3.1
操作系统版本：macOS 10.12.4

**Comment by oldj** [comment]
感谢反馈，问题 1 是一个已知 bug，正在处理。

问题 2 有点奇怪，不过我只在一种情况下能重现：系统 hosts 文件 `/etc/hosts` 内容为空时。如果 `/etc/hosts` 中有内容（即使只是一行注释），关闭当前配置项后，host 也能正常取消。你那儿是这样吗？

**Comment by fengyiway** [comment]
@oldj /etc/hosts不为空时，问题2依然能复现。操作步骤见附件
[images.zip](https://github.com/oldj/SwitchHosts/files/953988/images.zip)

**Comment by fengyiway** [comment]
@oldj  问题2确实只有当hosts文件为空时，才会出现我描述的问题

**Comment by oldj** [comment]
明白了，后面的版本会在写入时添加一行注释，防止生成空的系统 hosts 文件。

**Comment by fengyiway** [comment]
感谢
