### ISSUE TITLE
远程 hosts 方案被清空

### ISSUE THREAD

**Issue by ElfSundae** [oldj/SwitchHosts#180]
> v3.3.1 (5128)
> OS X 10.11.6

前两天更新了版本，发现远程方案可能会被清空（重置）。可能跟自动刷新有关系，暂时没发现重现规律。数小时睡眠后打开笔记本盖子，就发现远程 hosts 的配置被清空了，表现为：

- 状态栏菜单下的 host 配置名变为 "untitled"
- 主界面里的 host 配置名变为「未命名」
- 点开配置，相关的方案名、更新地址都被清空了
- 此时如果从状态栏菜单切换这个 "untitled" 方案，会自动新建一个 untitled 空白方案

![image](https://cloud.githubusercontent.com/assets/526008/25289347/cfb7fc5c-26fb-11e7-83a5-ffd4d46ed4c4.png)

**Comment by oldj** [comment]
感谢反馈，暂时没能重现，我会继续关注。

**Comment by ElfSundae** [comment]
纯净升级了电脑系统到 Sierra ，SwitchHosts 也升级到了 3.3.2 ，问题依旧。貌似跟电脑休眠有关系.. 
重现步骤：
1. 新建一个远程 hosts 方案，设置1小时刷新
2. 合上笔记本盖子去休息一段时间，可能要超过 1 小时这个自动刷新间隔
3. 打开笔记本盖子，发现这个远程 hosts 方案被清空了，方案名字也变成了 untitled

**Comment by oldj** [comment]
可能和 #198 是同一个原因，有些 https 远程方案在更新时，有一定概率会发生证书验证失败，从而导致方案被清空。

[v3.3.4](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.4) 版本中这个问题应该已经修复了。

**Comment by ElfSundae** [comment]
嗯 我试试

**Comment by ElfSundae** [comment]
应该是解决了 👍
