### ISSUE TITLE
sudo密码疑似会过滤特殊字符。现象：反复提示输入密码，而输入的密码完全正确。

### ISSUE THREAD

**Issue by wulechuan** [oldj/SwitchHosts#183]
sudo密码疑似会过滤特殊字符。现象：反复提示输入密码，而输入的密码完全正确。

注：密码中带有反斜杠号【\】。

**Comment by oldj** [comment]
感谢反馈，的确少了对反斜杠符号 `\` 的转义。

**Comment by wulechuan** [comment]
不客气！加油！

**Comment by zupodaniel** [comment]
When will you build next version? I'm affected with that issue. Thanks.

**Comment by oldj** [comment]
v3.3.2 is available for download now, you can find it at [https://github.com/oldj/SwitchHosts/releases](https://github.com/oldj/SwitchHosts/releases). @zupodaniel
