### ISSUE TITLE
macOS下，包含特殊字符的密码亦可使用，但每次动作均会被要求输入密码，其它普通密码则不会遭遇此现象。

### ISSUE THREAD

**Issue by wulechuan** [oldj/SwitchHosts#188]
例如，macOS系统密码为“\\\\”（无引号），每当开关任何host方案，软件均会要求我输入系统密码以获取权限。有意将macOS系统密码改为“kkkk”，重启SwitchHosts!软件，仅首次更改选项时，软件会要求我输入系统密码，之后不再提示。

具体来说：
拨动特定方案但开关，将其开启或关闭，必然会遭遇密码输入提示框。
编辑某方案的文本，则以很大概率遭遇密码输入提示框，但并不每次都会遭遇。

**Comment by lvsijian8** [comment]
我直接输入   ''     直接无限循环输密码.....不给我改
