### ISSUE TITLE
以管理员身份运行依然出错

### ISSUE THREAD

**Issue by 397272957** [oldj/SwitchHosts#189]
下面是错误界面：

[](http://file1.wailian.work/2017/05/05/d36615a4cf8a1770.jpg)
[](http://file1.wailian.work/2017/05/05/2.md.jpg)

**Comment by 397272957** [comment]
下面是错误界面：

![Uploading 无标题.jpg…]()
[](http://file1.wailian.work/2017/05/05/d36615a4cf8a1770.jpg)
[](http://file1.wailian.work/2017/05/05/2.md.jpg)

**Comment by onebraveman** [comment]
同样遇到这样的问题，开始是报错，然后编辑就提示权限问题。

![2017-05-15_204852](https://cloud.githubusercontent.com/assets/14172312/26058458/88fdf98e-39b0-11e7-8aa5-5827e521ef31.png)
![2017-05-15_205100](https://cloud.githubusercontent.com/assets/14172312/26058459/89122472-39b0-11e7-9870-92ca54391e60.png)

**Comment by oldj** [comment]
第一个错误应该是重复启动多个实例的一处 bug，会在下个版本修复。

第二个应该仍然是权限问题……

**Comment by onebraveman** [comment]
第一个问题在今天重启电脑后顺利解决；第二个问题有点诡异，因为自己昨天确实是以管理员权限运行的。今天再次右击管理员权限，正常打开。感谢@oldj

**Comment by archonwang** [comment]
这个问题比较诡异，，，，

有时候是右键打开，运行较长一段时间后会突然报错，未获取管理员权限等等。。

还有个奇怪问题，

online的配置有时候会莫名丢失，变成一个空白的配置项目。搞得头大。

**Comment by oweaF** [comment]
win10 15063版本 64位系统 软件版本：3.3.4 64位；杀软只有windows defender 还加了白名单；组策略里面的软件安全里面设置了不受限的权限；用Dism里面的“春哥模式”运行；右键管理员运行依旧报没有权限。
换成3.3.4 32位版本后管理员运行没有出现权限问题

**Comment by huisongd** [comment]
我关掉360后就没了。。。

**Comment by He-Xun** [comment]
一样的提示
发现一个坑  大家别跳了  
win10 创意者更新系统  会把host文件默认设为隐藏   而且还改不了隐藏属性  
就算用管理员权限  把host设为所有用户可编辑都不好使  
一定要把原来的host删掉  然后自己用编辑器建一个新文件才行  
试了n次   浪费我大半天时间   烦死了

**Comment by 397272957** [comment]
我已经放弃了，自己有vb写了个
打包完才200k大小
![default](https://user-images.githubusercontent.com/28405787/28490949-ea07a0e8-6f18-11e7-9828-802841d1c337.jpg)

**Comment by oldj** [comment]
@397272957 赞！很久以前也写过 VB，后来忘光了，Windows 下写这种小工具或许还是用 VB 等更适合。如果方便的话，不妨也开源分享一下。🙂

**Comment by lin09** [comment]
看了 https://github.com/oldj/SwitchHosts/issues/189#issuecomment-316662761
就查了我电脑的hosts文件默认为只读的，去掉只读就可以了。
系统：win10 1903

**Comment by wylsy** [comment]
> 我已经放弃了，自己有vb写了个
> 打包完才200k大小
> ![default](https://user-images.githubusercontent.com/28405787/28490949-ea07a0e8-6f18-11e7-9828-802841d1c337.jpg)

哈喽，我在SwitchHosts下发现了你的回答。针对SwitchHosts，管理员运行，修改hosts属性，增加用户，等依然不可用（提示没有写入hosts文件权限），试了其他编辑hosts程序，都是正常的（当前系统Windows 10 21H1 专业版）。暂时未找到类似SwitchHosts的其他应用，请问你自己写的这个程序能发我一份使用么，感谢Thanks♪(･ω･)ﾉ

**Comment by leohu1** [comment]
删了再用记事本建一个hosts文件就好了
