### ISSUE TITLE
自定义命令输入错误时，开关切换不起作用

### ISSUE THREAD

**Issue by spwei** [oldj/SwitchHosts#190]
MacOS：10.12.4 (16E195)
SwitchHosts! v3.3.2.5193

在配置(Command after a hosts be applied)中，直接填写相对路径，例如：surge-cli reload，而不是完整路径(/usr/local/bin/surge-cli reload)时，切换不会生效，也不提示错误。

**Comment by spwei** [comment]
#147

**Comment by oldj** [comment]
感谢反馈，[v3.3.3](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.3) 或[更新版](https://github.com/oldj/SwitchHosts/releases)中这个问题应该已经修复。

**Comment by spwei** [comment]
v3.3.3.5215 确认已修复
