### ISSUE TITLE
能否加入一个查找功能？

### ISSUE THREAD

**Issue by ijackwu** [oldj/SwitchHosts#192]
加入的host记录太多了，一眼看过去太累了，很难查找。

**Comment by oldj** [comment]
你用的是哪个版本呢？点左下角的放大镜按钮，或者按快捷键 Ctrl + F （或 Cmd + F），可以搜索啊。

<img width="300" alt="switchhosts__and_ _ _issue__192_ _oldj_switchhosts" src="https://cloud.githubusercontent.com/assets/416130/25771113/c790ee64-327a-11e7-93dd-13b5bd2e854a.png">

直接输入关键词即可搜索，比如`abc`。
输入以 `/` 开头的词，则以正则进行搜索，比如 `/a.*c` 可以匹配 `ac`、`abc`、`abbbc` 等。

**Comment by ijackwu** [comment]
win 版本。我错了
