### ISSUE TITLE
版本 3.3.2 (5193) 每隔一分钟会执行一次自定义命令

### ISSUE THREAD

**Issue by spwei** [oldj/SwitchHosts#193]
SwitchHosts 版本 3.3.2 (5193)
添加了自定义命令：echo `date` >>/alidata/www/logs/t.txt
发现每隔1分钟会执行一次，能否关掉这个属性？

**Comment by oldj** [comment]
应该是个 bug，我看一下。多谢反馈！

**Comment by oldj** [comment]
[v3.3.3](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.3) 或[更新版](https://github.com/oldj/SwitchHosts/releases)中这个问题应该已经修复。

**Comment by spwei** [comment]
v3.3.3.5215 确认已修复
