### ISSUE TITLE
互斥规则

### ISSUE THREAD

**Issue by sky0504** [oldj/SwitchHosts#194]
能否实现项目的互相切换，比如加了互斥规则之后，启用这个，另一个就自动移除

**Comment by oldj** [comment]
默认是“多选”模式，在设置中选择“单选”模式是不是就可以实现互斥？

<img src="https://cloud.githubusercontent.com/assets/416130/25885398/b5ff3d8c-358a-11e7-997a-03ff60782d07.png" width="336">

**Comment by wulechuan** [comment]
我猜作者“老J”并非全职于此项目，所以精力有限。但我不妨先提出建议：
允许将方案分组，这特定组内的多个方案，可配置为互斥。当然，亦可不做此配置，方案组仅用于方便地统一开启或关闭组内各方案。

**Comment by sky0504** [comment]
好的。多谢。之前也未曾注意到模式的选择。希望模式有组合模式。组内互斥。组间不互斥

**Comment by oldj** [comment]
的确不是全职于这个项目，平时工作也有点忙，SwitchHosts! 是业余时间维护。感谢理解与支持！😀 @wulechuan
