### ISSUE TITLE
打开报错

### ISSUE THREAD

**Issue by lizhuangs** [oldj/SwitchHosts#196]
![qq](https://cloud.githubusercontent.com/assets/7904121/25935449/d818d358-3655-11e7-8807-7672509caadb.png)
不知道什么原因

**Comment by Auth8** [comment]
@lizhuangs 可以看下任务栏托盘处是不是已经打开一个了

**Comment by oldj** [comment]
感谢 @Auth8 的提醒，的确是重复启动时的一个 bug。这个问题会在下个版本修复。

**Comment by oldj** [comment]
[v3.3.4](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.4) 中这个问题应该已经修复了。

**Comment by lizhuangs** [comment]
@oldj 我测试了多次，那个问题我复现不了，因为我打开一个最小化的系统托盘后，再打开的窗口和最小化是同一个窗口。我点击系统托盘也没有打开一个新的窗口。光标定位在之前的这个窗口上。
