### ISSUE TITLE
v3.3.3.5215的windows64位的不能更新远程host

### ISSUE THREAD

**Issue by oneness0** [oldj/SwitchHosts#198]
一直在转圈，试了一下是HTTPS的URL不能加载

**Comment by ElfSundae** [comment]
macOS 也是

**Comment by oldj** [comment]
感谢反馈，注意到这个问题了，有些 https 证书下更新远程 hosts 有问题，有些证书正常，看日志是遇到了 UNABLE_TO_VERIFY_LEAF_SIGNATURE 错误。

下个版本会修复这个问题。

**Comment by ElfSundae** [comment]
我这个貌似没修复。更新时一直转菊花，偶尔能更新到数据。

**Comment by ElfSundae** [comment]
v3.3.4 我用本地的 http 地址也是时好时坏

**Comment by ElfSundae** [comment]
我用 AppCleaner 把 SwitchHosts 卸载了，把配置目录也删了。重新安装然后导入配置， https 的远程 hosts 更新问题依旧。
上一条反馈的有问题，本地的 http 是一直能更新到。远程更新貌似是单任务，如果有一个更新时出问题了，会导致别的远程更新一直在等待，界面上也一直在转菊花。

另外，测试时出现了一次 404 错误，重启应用后好了。
![qq20170520-190329](https://cloud.githubusercontent.com/assets/526008/26275340/b417cf58-3d90-11e7-8f81-89692464574b.png)

**Comment by oneness0** [comment]
有的网址更新很快，有的就一直转菊花，等好长时间才好（同是github上的hosts，浏览器都能打开）

**Comment by oldj** [comment]
我也觉得奇怪，暂时没有找到规律… 😂

**Comment by lzhp529** [comment]
我想单独把吾爱破解跟百度云分享的链接添加到hosts里面去，因为新疆屏蔽该网站。我该怎么添加啊？
是自己添加本地么，具体需要添加什么条目啊？

**Comment by ElfSundae** [comment]
@oldj 跟踪了下代码，好像找到原因了。

https 没问题，request 也没问题，问题在代码逻辑。如果某个远程 host 更新后 content 没变，就陷入死循环了，一直在刷新。

`checkNeedRemoteRefresh.js` 中：

```
if (! isListEqual(list, list2)) {
  return saveHosts(svr, list2)
}
```

如果更新后 list 内容没变化，就没 return ，那么 `Promise.all` 是不是也就没结束？我对 Promise 一点都不懂，瞎猜的。按我想的，这里可能要加个 return ：

```
if (! isListEqual(list, list2)) {
  return saveHosts(svr, list2)
} else {
  return Promise.resolve(list2)
}
```

或者 给 `isHostsEqual` 里再加个条件: `&& hosts1.last_refresh === hosts2.last_refresh` 。因为成功更新后 last_refresh 会变，然后就调到了 saveHosts 并且 return 了，就跳出 `Promise.all` 了。

**Comment by oldj** [comment]
感谢 @ElfSundae ，的确是更新后 list 内容没有变化引起的问题。

之前的代码中，其实远程刷新已经正常完成了，但如果内容没有变化，就不会发送 `refresh_end` 消息，导致会一直显示 loading 状态。偏偏我用来测试的远程 hosts 是动态生成的，每次返回的内容中都包含一个时间戳，导致每次返回的内容都不一样，于是一直没发现引发问题的原因。😂

**Comment by ElfSundae** [comment]
✌️

**Comment by oldj** [comment]
这个问题在 [v3.3.5](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.5) 中应该已修复。
