### ISSUE TITLE
win10系统 64位 3.3.3 (5215) 更新远程hosts之后会变成未命名 远程地址消失

### ISSUE THREAD

**Issue by vescape920** [oldj/SwitchHosts#199]
远程hossts地址：https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts
设置的一小时更新 就会出现hosts地址丢失 方案名为未命名

**Comment by oldj** [comment]
试试 [v3.3.4](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.4) ？应该没有这个问题了。

**Comment by vescape920** [comment]
恩  修复了的 忘记回了
