### ISSUE TITLE
关于Windows/Unix换行格式的重大问题

### ISSUE THREAD

**Issue by yuyuen72** [oldj/SwitchHosts#200]
在线host源通常是Unix格式，所以在linux下应该没问题，但是Windows直接添加在线源似乎是用不了的。
由switchhosts更新下来的hosts文件换行全丢了，使用Windows自带的记事本打开可以看到效果。（我总是上传不了图片）
我用notepad++可以转换，但是这意味着每次更新完都需要手动转换一次。

**Comment by yuyuen72** [comment]
在百度搜Unix2dos，可以找到相关工具，[http://www.bastet.com/](url)这个网址可以下载这个工具，你把它和你的工具结合一下就完美了

**Comment by oldj** [comment]
感谢反馈！

**Comment by oldj** [comment]
这个问题在 [v3.3.5](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.5) 中应该已经修复。
