### ISSUE TITLE
请作者完善中文版的汉化，虽然看得懂

### ISSUE THREAD

**Issue by jinyiquan** [oldj/SwitchHosts#201]
请作者完善中文版的汉化，设置为中文，但中文并不完整，菜单里还有很多英文，虽然看得懂，但一半英文一半中文看着别扭，想自己汉化，却发现pak文件加密，谢谢作者了

**Comment by oldj** [comment]
好的。

早想做这个事，但是拖延症发作，一直拖着…… 🤣

**Comment by oldj** [comment]
[v3.3.5](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.5) 中菜单项应该已经汉化了。
