### ISSUE TITLE
可以使用vscode调试么？

### ISSUE THREAD

**Issue by hallooyo** [oldj/SwitchHosts#205]
默认使用vscode调试，没配置成功，请问oldj是通过什么方式调试的？

**Comment by oldj** [comment]
没有怎么用过 vscode，不了解应该怎么配置。

我调试时主要是用开发模式，与编辑器或 IDE 无关，用 `npm run dev` 启动，就会打开开发者面板，然后就可以像在 Chrome 中调试网页一样操作了。

**Comment by hanforing** [comment]
我使用vs code可以调试代码了，感觉很棒，主要在launch.json配置好就行。
  "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "启动程序",
            "program": "${workspaceRoot}/app/main.js",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron"
        }
    ]
