### ISSUE TITLE
remote hosts 不能修改

### ISSUE THREAD

**Issue by Yac836** [oldj/SwitchHosts#206]
同步到远程的hosts文件 一些条目不一定适合自己的电脑需要添加或者删除，现在只能只能注释 不能添加

**Comment by oldj** [comment]
remote hosts 不太适合在本地修改，因为后面你可能需要刷新它（从服务器再次下载），如果本地版本被修改了且与服务器的版本不一致，就会导致冲突，这时就要额外的工作，让用户选择覆盖还是合并。如果你真的需要修改，可以把它转为本地方案。

还有一个方法，因为 hosts 的生效规则是以先出现的为准，所以你可以把自己的条目放在 remote hosts 前面，让它们拥有更高的优先级。

比如如果你的 hosts 文件中同时包含两条规则：

```
1.1.1.1 test.com
2.2.2.2 test.com
```

那么实际生效的是第一条 `1.1.1.1 test.com` 。

所以，如果你有一些本地条目，想让它们覆盖 remote hosts 中指定条目的内容，不妨在 remote hosts 前面建一个方案，把你的条目放进去，这样就能保证指定域名解析到自己想要的址。
