### ISSUE TITLE
捐赠链接哪去了

### ISSUE THREAD

**Issue by iqyeah** [oldj/SwitchHosts#207]
原来还有支付宝捐赠页呢.

**Comment by oldj** [comment]
去掉了。😆

曾经放过一段时间的捐赠链接，一共收到 5 笔捐赠（感谢这 5 位朋友 😇），鉴于 SwitchHosts! 只是一个小众软件，有 5 笔捐赠还是很让人惊喜的，虽然总数额不大。

后来考虑到自己平时工作也比较忙，只是业余时间维护这个软件，能投入的时间不固定，决定还是将它做成一个比较纯粹的免费开源软件比较好，于是把捐赠链接去掉了。

**Comment by hucheng91** [comment]
还是放出来吧，不能白嫖，良心软件得支持下
