### ISSUE TITLE
switchhosts 双击打不开了

### ISSUE THREAD

**Issue by jiawenjing** [oldj/SwitchHosts#211]
switchhosts 已经运行，任务管理器也显示操作，但双击还是打不开，卸载并重新安装也无法运行，试了好几种方法也不行，不知道怎么办了？

**Comment by XDJAZZ** [comment]
我也遇到了这个问题，试了好久，题主你解决了吗？

**Comment by XDJAZZ** [comment]
我知道是什么原因了.是系统的hosts文件里有混合的编码导致的!!!
把系统的hosts文件清空再打开就好了.
原回答帖子：https://github.com/oldj/SwitchHosts/issues/37
