### ISSUE TITLE
宁愿用老版本。。

### ISSUE THREAD

**Issue by cyanqueen** [oldj/SwitchHosts#212]
新版的功能的确强大了不少，界面也好看了，但是，流畅度真的不行，有时候项目开多了，卡的不行，换回老版本的就没事。

**Comment by oldj** [comment]
不知你说的老版本是哪个版本呢？在我这边新版本似乎没有明显卡顿，我对比一下…… 😂

**Comment by 260242556** [comment]
昨天开始添加几个大的host源的时候卡的很，崩溃关闭很多次，倒退版本也一样出现这种情况。最后成功添加host源之后连打开程序都会卡爆崩溃。

后来想想应该问题是出现在host更新上面，因为我之前是一小时更新一次，开机就会自动更新所有host，将所有host更新改为“从不”状况改善了很多，但是只能手动更新host，而且每次更新还是会卡一下。

P.S. 我的系统host已经5万多行。

**Comment by cyanqueen** [comment]
0.2.2.1785版本的

**Comment by honglingjinhosts** [comment]
确实卡的要死,用0.2的就不卡
