### ISSUE TITLE
提示反复输入密码！

### ISSUE THREAD

**Issue by chejinying** [oldj/SwitchHosts#215]
我的mac密码是：l;'（回车左面的三个键），看到了一个历史Issues，与我的问题类似，是不是也缺少了特殊字符的转义？

我的解决方法： 修改了root密码为简单的数字。。。

**Comment by dukegod** [comment]
@chejinying 修改`/etc/hosts`的读写权限对我有用，你可以试下

`chmod -R  755 /etc/hosts`

**Comment by zhuziyi1989** [comment]
sudo chmod -R 755 /etc/hosts

**Comment by zhumingwei** [comment]
对我没用
macos 10.14.6

**Comment by Sligcm** [comment]
没用。
系统版本：macOS Big Sur 11.2.2 (20D80)
SwitchHosts版本：v3.5.8 (5556)

**Comment by Sligcm** [comment]
这个问题就没人重视吗？
macOS 11.2.3 (20D91)
chmod 755 /etc/hosts
运行命令之后每次开机还是会提示输入密码。

**Comment by Sligcm** [comment]
测试研究了下，其实就是当前用户的权限需要增加一个写入的权限。
这种sudo chmod -R 755的方式并不能解决问题。
首先，chmod -R 的这个-R 根本没必要加，因为没有子文件夹也不是文件夹。
相比较原来的用户权限，以我为例，/etc/hosts的原始权限是644，所属用户：root，所属用户组：wheel，就644的权限而言，只是多了一个执行权限1（x），而修改hosts根本不需要执行权限1（x），而我本身的账户既不是root也不属于wheel用户组。所以如果是我这种情况，只需要sudo chmod o+w 或者 sudo chmod 646（也就是给其他用户增加2（w）权限）即可不再提示需要输入密码。
但我的例子又存在一个问题，目前不知道是什么软件或者机制会导致我的/etc/hosts文件会在重启后恢复权限为644，目前怀疑是苹果系统的SIP机制导致的。因为上班时间的原因，暂时先排查到这，后续再继续研究。目前仅提供一个解决问题的思路。如果想临时解决问题可以试试我提供的命令。
请大家不要以讹传讹，遇到问题分析问题，理性解决问题。

**Comment by oldj** [comment]
其实输入 sudo 密码应该就可以了，从 https://github.com/oldj/SwitchHosts/releases 下载的版本都是直接用当前仓库公开的源码打包的，没有恶意代码，不会记录或窃取你的 sudo 密码。当然，出于谨慎，不向第三方软件输入 sudo 密码也是好习惯，但那样就需要手动修改一下 `/etc/hosts` 文件的权限。

也试验过类似 [electron-sudo](https://github.com/automation-stack/electron-sudo) 那样的方案，好处是弹出的鉴权提示框是属于操作系统的，SwitchHosts! 完全不知道用户输入的密码，这样安全性就会高很多，但缺点是这个授权只能对当前执行的这次命令生效，不能存储授权（或者是有方法，但我没有找到），于是每次写入都需要输入一次密码，对需要经常进行切换操作的用户来说体验不太好。

目前好像没有更优雅的方法。

**Comment by Sligcm** [comment]
> 其实输入 sudo 密码应该就可以了，从 https://github.com/oldj/SwitchHosts/releases 下载的版本都是直接用当前仓库公开的源码打包的，没有恶意代码，不会记录或窃取你的 sudo 密码。当然，出于谨慎，不向第三方软件输入 sudo 密码也是好习惯，但那样就需要手动修改一下 `/etc/hosts` 文件的权限。
> 
> 也试验过类似 [electron-sudo](https://github.com/automation-stack/electron-sudo) 那样的方案，好处是弹出的鉴权提示框是属于操作系统的，SwitchHosts! 完全不知道用户输入的密码，这样安全性就会高很多，但缺点是这个授权只能对当前执行的这次命令生效，不能存储授权（或者是有方法，但我没有找到），于是每次写入都需要输入一次密码，对需要经常进行切换操作的用户来说体验不太好。
> 
> 目前好像没有更优雅的方法。

有点奇怪，如果不修改/etc/hosts的权限，我每次开机后都需要sudo一次，但截止到下次开机之前修改hosts就不会再让我输入密码了。
您说的这个“其实输入 sudo 密码应该就可以了”是不是也是指每次开机都需要输入一次密码？
还是说只要输入一次密码，之后重启也不需要再次输入密码了。

**Comment by oldj** [comment]
每次启动 SwitchHosts! 都需要输入一次密码，但之后切换方案时不用再输入。因为出于安全考虑 SwitchHosts! 不会把 sudo 密码存储到硬盘上（即使加密后再存储也有泄露的风险），只是临时保存在内存变量中，所以退出软件后再次启动需要重新输入。

**Comment by Sligcm** [comment]
> 每次启动 SwitchHosts! 都需要输入一次密码，但之后切换方案时不用再输入。因为出于安全考虑 SwitchHosts! 不会把 sudo 密码存储到硬盘上（即使加密后再存储也有泄露的风险），只是临时保存在内存变量中，所以退出软件后再次启动需要重新输入。

好的，了解了，谢谢。
