### ISSUE TITLE
没有linux版的啊，求linux版的

### ISSUE THREAD

**Issue by dongritengfei** [oldj/SwitchHosts#22]
现在每天都用linux开发啊，没有switchhosts着实难受啊

**Comment by itbeihe** [comment]
现在依然没有linux版么？

**Comment by stotem** [comment]
在LinuxMint环境下编译出来的可执行包

https://github.com/diligrp/SwitchHosts

**Comment by oldj** [comment]
现在已经有 Linux 版了，[下载地址](https://github.com/oldj/SwitchHosts/releases)。
