### ISSUE TITLE
Alfred Workflow HTTP 接口服务存在 XSS 漏洞

### ISSUE THREAD

**Issue by monkeym4ster** [oldj/SwitchHosts#220]
## XSS 介绍
https://en.wikipedia.org/wiki/Cross-site_scripting

## 漏洞页面
http://127.0.0.1:50761/api/toggle?id=1%3Csvg%20onload='alert(1)'%3E

**Comment by oldj** [comment]
感谢反馈。

这个问题之前已经注意到，不过评估了一下，貌似不会造成影响，因为当前域下没有敏感信息，并且参数中的 HTML 代码应该不会被解析。

不过保险起见，已修改代码，添加了一个[校验](https://github.com/oldj/SwitchHosts/commit/5d2aa1a44f16abbd6fcfc33a69c0cb596be59243)，首先会验证参数格式，再进行后续操作，这样应该可以从源头上杜绝 XSS 攻击的风险。
