### ISSUE TITLE
多个host的配置

### ISSUE THREAD

**Issue by qiaodaimadelaowang** [oldj/SwitchHosts#223]
有这样一个场景，就是rules是从服务器拉取的，但是有时候想单独修改其中某一个host配置，由于是从服务器定时拉取，这个时候，自己修改的可能就被覆盖了。如果我新建一个本地的rules来单独配置这个host，那remotes和local的rules是可以覆盖的吗？是否可以有一个优先级，这样我就可以既使用remote的rules，也可以单独定制其中一个host了。

**Comment by oldj** [comment]
多条 hosts 方案如果重复，会以先出现的为准。所以你可以在远程 hosts 方案的前面建一个方案，放你的 rules。

**Comment by qiaodaimadelaowang** [comment]
thanks.
