### ISSUE TITLE
跳到第一行

### ISSUE THREAD

**Issue by qiaodaimadelaowang** [oldj/SwitchHosts#229]
### 操作系统
mac os
10.12.6

### SwitchHosts! 版本
v3.3.6 (5287)

### 问题描述
编辑host时，偶现光标跳到第一行。

### 重现步骤
在通过commond+v粘贴或者commond+/注释掉host时，偶现光标跳到整个rules的第一行。

**Comment by sunyq** [comment]
跟楼上的系统+软件版本号完全一样。
也是会经常出现这个问题。
希望作者有时间能关注下。

感谢SwitchHosts的各位开发者为我们贡献了这么一款优秀的工具！

**Comment by oldj** [comment]
试一试 [v3.3.7](https://github.com/oldj/SwitchHosts/releases) 或更新版本 ？新版本中这个问题应该不太会出现了。

**Comment by qiaodaimadelaowang** [comment]
使用v3.3.7 (5324)问题不在出现。
