### ISSUE TITLE
建议增加切换环境变量的功能

### ISSUE THREAD

**Issue by zdsiyan** [oldj/SwitchHosts#231]
### 操作系统
windows

### SwitchHosts! 版本
3.3.6

### 问题描述
建议切换Host时可以同时修改环境变量, 有些地址的配置是带端口号的, 放在host里改不了, 能切换环境变量就更好了

**Comment by zdsiyan** [comment]
或者切换时触发一个bat/cmd/sh脚本也可以, 每个分组绑定一个脚本

**Comment by oldj** [comment]
这个功能目前是有的，在【设置】->【自定义命令】中，可以添加 bat/cmd/sh 脚本命令，每次切换完成后会执行其中的命令。

![image](https://user-images.githubusercontent.com/416130/29555736-1d5e9fd2-8756-11e7-8110-1b5c9c1682bc.png)

**Comment by zdsiyan** [comment]
这里能判断是哪个模块触发的吗, 我想针对模块设置不同的环境变量

**Comment by oldj** [comment]
暂时不能判断。

目前的版本中，如果真的需要判断，有一个比较“绕”的方法：在执行这段命令时，hosts 内容已经写入系统文件了，可以通过读取系统 hosts 的内容来判断当前应用的是哪个模块。

倒是可以改一下源码，在这边添加一个注入参数，标识当前应用的是哪个模块，比如传入当前模块的名字。不知这样是否能解决你的问题？

**Comment by zdsiyan** [comment]
可以解决, 我也是用这个方案来处理的, 不过确实绕, 要用脚本判断文本中的文字. 如果每个模块能设置独立的脚本也会方便一些.
