### ISSUE TITLE
多个hosts拖动一下调整排序结果全部消失了？

### ISSUE THREAD

**Issue by bydx** [oldj/SwitchHosts#236]
### 操作系统
Windows7 x64

### SwitchHosts! 版本
v3.3.7.5322

### 问题描述
Q1：多个hosts拖动一下调整排序会导致hosts全部丢失。
Q2：不认https。
Q3：改成http好了，但是好像会发呆一会才同步？

### 重现步骤
随便新建多个hosts，然后拖动任意一条调整排序，松开鼠标后hosts全部消失。

**Comment by oldj** [comment]
果然，拖动会导致 hosts 丢失！v3.3.7.5322 的下载链接已删除，更新后再上传。感谢反馈！

**Comment by oldj** [comment]
[v3.3.7.5324](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.7) 中拖动的问题修复了。
