### ISSUE TITLE
启动卡顿，不支持windows系统盘不在C盘的情况

### ISSUE THREAD

**Issue by SkyBridge007** [oldj/SwitchHosts#238]
### 操作系统

windows 7 企业版

### SwitchHosts! 版本

3.3.7

### 问题描述

1. 启动卡顿，hosts  文件过大就卡死
2. 默认仅支持系统盘在C盘的hosts文件切换，系统盘不在C盘就鸡肋了。希望能自动识别系统盘位置。

**Comment by oldj** [comment]
文件过大在编辑的时候的确会卡，比如超过 5000 行，暂时没有特别好的办法，可能的话建议把大方案拆分一下。不过如果只是引入方案，只切换不编辑，应该不会感觉特别卡？

代码中有处理[系统不在 C 盘](https://github.com/oldj/SwitchHosts/blob/a49121e5310d84bd25591e46063ad316c5e52eaa/app/server/paths.js#L13)的情况，不过手上没有系统不在 C 盘的机器，不知具体表现是什么呢？

**Comment by SkyBridge007** [comment]
文件大更新和浏览的时候会卡。
我的是双系统，代码默认替换了C盘的hosts文件，实际使用的操作系统在E盘，是否可以通过环境变量来判断系统盘所在位置，或者根据某些特殊命令的位置来判断。

**Comment by SkyBridge007** [comment]
只是引入方案，只切换不编辑，确实没问题。
我是双系统，实际切换方案只会修改C盘的hosts文件，我实际使用的系统盘在E盘。是否可以考虑根据系统环境变量来确认系统盘位置，或者考虑一些特殊命令的所在位置来确定系统盘位置。

**Comment by SkyBridge007** [comment]
v3.3.8 (5338)  解决这个问题.
