### ISSUE TITLE
有个图标按钮不知道意思，特来询问一下

### ISSUE THREAD

**Issue by zzm-note** [oldj/SwitchHosts#239]
### 操作系统

windows 10 64位

### SwitchHosts! 版本
最新版

### 问题描述
如图

![01](https://user-images.githubusercontent.com/25860330/30436422-a49d5f4c-999e-11e7-8b51-9dcd3b2de1f1.jpg)

### 重现步骤

**Comment by oldj** [comment]
这个按钮用于临时禁用/恢复所有规则，比如有时开启了多个方案，需要看一下什么 host 也不绑定的情况，如果一个一个地关闭/开启比较麻烦，就可以用这个按钮进行临时切换。如下图：

<img src="https://user-images.githubusercontent.com/416130/30462639-9ea0397e-99f9-11e7-8c11-2759e0291f93.gif" alt="" width="324" />

**Comment by zzm-note** [comment]
先多谢解答，然后提交个bug
描述：
先建立一个a，然后再建立一个本地b，b是跟a建立一个group，如图
![tim 20170915103748](https://user-images.githubusercontent.com/25860330/30464075-f79e6354-9a01-11e7-9952-cdb3a6a427a9.png)
然后每开关一次b，组合的a就多一条记录
![tim 20170915103945](https://user-images.githubusercontent.com/25860330/30464319-84861ffe-9a03-11e7-8c55-55f3956977ae.png)

PS：
1、个人觉得建立group应该不能和自己组合（图中b和自己组合了，所以导致出问题了）；
2、自从可以多选了之后，貌似group没有什么实际用途了，可以考虑取消节约维护成本吧？

**Comment by oldj** [comment]
确实，在把本地/远程方案改成组合方案时，可以把自己包含进来，后面会修复这个问题，感谢反馈！🙂

group 还是有应用场景的，主要是在组合之间切换的时候，可以少点几下鼠标。比如组合 X 包含 a、b、c 三个方案，组合 Y 包含 d、e、f 三个方案，如果没有组合，从 X 切换到 Y，需要分别关闭 a、b、c，再分别打开 d、e、f，要点 6 次，有组合的话只要关闭 X，再打开 Y，只要点两次。
