### ISSUE TITLE
alfred workflow 是不是只支持python2.X？

### ISSUE THREAD

**Issue by sunhao-java** [oldj/SwitchHosts#242]
### 操作系统
macos 10.12.6

### SwitchHosts! 版本
v3.3.8 (5338)

### 问题描述
switch hosts 的Alfred workflow在python3.6.2环境下会报错

### 重现步骤
![image](https://user-images.githubusercontent.com/2178487/30574229-326c9a42-9d2b-11e7-8c67-fd02930325f9.png)

**Comment by oldj** [comment]
是的，Alfred workflow 功能使用了第三方库： [Alfred-Workflow](https://github.com/deanishe/alfred-workflow)，根据它的[文档](http://www.deanishe.net/alfred-workflow/supported-versions.html#python-versions)，它只支持 macOS 系统自带的 Python 版本，不支持 Python 3。

**Comment by oldj** [comment]
补充一下，根据 Alfred-Workflow 作者的说法：

> Personally, I don’t use Python 3 very much (Python 2 is a much better fit for command-line tools, which is what I usually write), and it’s not part of macOS, so I consider the huge effort required to write 2.6- and 3.x-compatible code a waste of my time. If someone else wants to contribute Python 3 support, it will be gratefully accepted.

Alfred-Workflow 目前应该没有支持 Python 3 的计划。

**Comment by stormning** [comment]
@sunhao-java @oldj 
不错，居然也是基于Electron，看来我也得写个什么玩玩
