### ISSUE TITLE
mac 版本推荐作者在brew cask 中添加forumal

### ISSUE THREAD

**Issue by rainplus** [oldj/SwitchHosts#253]
### 操作系统

mac high sierria

### 问题描述

建议添加brew cask Formual 可以使用brew cask install switchhost进行安装

### 重现步骤

@oldj

**Comment by spwei** [comment]
已经有了，善用brew cask search

 ~/
$ brew cask search switchhosts
==> Exact Match
switchhosts ✔

 ~/
$ brew cask info switchhosts
switchhosts: 3.3.8.5338
https://oldj.github.io/SwitchHosts/
/usr/local/Caskroom/switchhosts/3.3.8.5338 (160B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/switchhosts.rb
==> Name
SwitchHosts!
==> Artifacts
SwitchHosts!-darwin-x64/SwitchHosts!.app (App)

**Comment by rainplus** [comment]
！！！！我查询的时候没有找出来。。
