### ISSUE TITLE
hosts文件空白问题

### ISSUE THREAD

**Issue by rainplus** [oldj/SwitchHosts#260]
### 操作系统
MacOS 10.13.1

### SwitchHosts! 版本
 最新

### 问题描述

把默认系统的Host 127.0.0.1 localhost 替换成了空白。。

### 重现步骤

取消所有的host 应用，就会出现

**Comment by oldj** [comment]
这个似乎不能算 bug，取消所有 host 应用，本来就意味着什么规则都不设置，系统 hosts 文件自然会变成空白……

**Comment by rainplus** [comment]
我觉得吧， 是不是应该保留一个127.0.0.1 这个地址所有默认系统都应用默认的
