### ISSUE TITLE
要求管理员权限，但是我右键管理员运行的

### ISSUE THREAD

**Issue by AllenZF** [oldj/SwitchHosts#267]
### 操作系统

win 10  16299.64

### SwitchHosts! 版本
v3.3.8.5338

### 问题描述
在百度网盘下载，解压SwitchHosts-win32-x64_v3.3.8.5338\SwitchHosts!-win32-x64，然后右键以管理员运行SwitchHosts!应用程序。打开程序后，添加远程，结果弹出对话框要求以管理员运行SwitchHosts!

### 重现步骤
EPERM: operation not permitted, open 'C:\WINDOWS\system32\drivers\etc\hosts'    Please run SwitchHosts! as an Administrator.

**Comment by zanjs** [comment]
me too

**Comment by JayVae** [comment]
一样的问题。

**Comment by XWenbo** [comment]
到C:\WINDOWS\system32\drivers\etc\hosts 下 右键属性-安全  把账户权限添加上

**Comment by JayVae** [comment]
多谢  解决了！！

**Comment by AllenZF** [comment]
EBUSY:resource busy or locked, open'C:\WINDOWS\system32\drivers\etc\hosts' Please run SwitchHosts! as an Administrator.

**Comment by qingmuccc** [comment]
怎么解决的，我添加了hosts的账户权限，以管理员运行SH还是会报run as Administrator的错误

**Comment by AllenZF** [comment]
我也是加上了hosts的权限，但是还是报错，如上

**Comment by qingmuccc** [comment]
@AllenZF  你去看看Issues首页第一个，我已经解决了

**Comment by syhyz1990** [comment]
去 C:\WINDOWS\system32\drivers\etc\hosts 右键属性，只读去掉

**Comment by xmeng1** [comment]
好像把 ALL Packages 的 Full Control 勾上就行了 在win10上
![snipaste_2018-09-03_21-14-28](https://user-images.githubusercontent.com/5753142/45000623-81bb8f80-afbe-11e8-9ba7-657123a7fa1e.png)

**Comment by AlekseiMarinichenko** [comment]
Giving of all permissions does not help. Still, get the error "Busy or locked". The program is running as an Administrator. 
谷歌翻译：授予所有权限无济于事。 仍然，收到错误“忙碌或锁定”。 该程序以管理员身份运行。

**Comment by mymonkey110** [comment]
把“只读”属性去掉

**Comment by makemyownlife** [comment]
把只读属性去掉就可以。

**Comment by JayVae** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，欢迎联系！收到您的邮件后我会第一时间阅读并回复您的。
