### ISSUE TITLE
字号太小了希望可以调字号

### ISSUE THREAD

**Issue by levinit** [oldj/SwitchHosts#269]
### 操作系统
Linux (Gnome)

### SwitchHosts! 版本
3.3.8

### 问题描述
1080p的分辨率 文字太小 希望能有选项可以调节字号

**Comment by peakrock** [comment]
滚轮不能放大吗？

**Comment by levinit** [comment]
@peakrock 是的 滚轮 ctrl滚轮 ctrl+ ctrl shift+ 都没反应

**Comment by linkdesu** [comment]
最好是能设置字体和字体大小，这需求太必要了~
