### ISSUE TITLE
hosts中没有换行,不起作用

### ISSUE THREAD

**Issue by Serenity1994** [oldj/SwitchHosts#271]
### 操作系统
win7 64位系统

### SwitchHosts! 版本
v3.3.8 (5338)

### 问题描述
hosts文件中所有的配置都在一行,没有换行

### 重现步骤
在软件中看到的hosts:
![image](https://user-images.githubusercontent.com/11631078/34702514-1b2a4748-f529-11e7-87d0-aa1fbac8fc2b.png)
实际的hosts文件
![image](https://user-images.githubusercontent.com/11631078/34702542-35d34086-f529-11e7-9c8a-60fae30ab5d7.png)

**Comment by liujiangpeng** [comment]
win10 64 338同样没有换行

**Comment by KAROTT7** [comment]
这两天也遇上这问题，不是换行的问题，我同事用记事本打开也是没换行。
我刚才突然把VPN关了（因为我VPN默认开启激动），然后再切换就有用了（汗-_-||），不知道楼主是不是平常默认开启VPN的。
希望能帮到大家。
