### ISSUE TITLE
Please run SwitchHosts! as an Administrator

### ISSUE THREAD

**Issue by luffyzhao** [oldj/SwitchHosts#272]
### 操作系统
windows 10
### SwitchHosts! 版本
v3.8
### 问题描述
![image](https://user-images.githubusercontent.com/4166371/34704769-6109c39e-f536-11e7-9c1a-d695caa8daaa.png)
### 重现步骤
我是用的管理员运行还是不可以呢。

**Comment by luffyzhao** [comment]
问题已存在：https://github.com/oldj/SwitchHosts/issues/267

**Comment by safir187** [comment]
I'm not chinese (this is chinese right?) so i have no idea what @luffyzhao said, but i have the same issue. 
i'm running on win10.

**Comment by oldj** [comment]
@safir187 Yes, this is Chinese. :-)

Open the folder `C:\WINDOWS\system32\drivers\etc\`, there should be a file named `hosts`, right click on it, select the Security tab in the pop-up window, then add your account permissions.

Hope this is useful to you.

**Comment by xmeng1** [comment]
need to add the modify permission to the current user even the user is the admin.
