### ISSUE TITLE
建议把密码保存在客户端

### ISSUE THREAD

**Issue by teshoudong** [oldj/SwitchHosts#274]
### 操作系统

mac

### SwitchHosts! 版本

3.x.x

### 问题描述

建议把密码通过一些对mac地址的对称加密保存在客户端，这样每次就不需要重新输入

### 重现步骤

无

**Comment by oldj** [comment]
保存密码到本地风险比较大，即便是经过加密之后。如果希望不要每次修改都重新输入密码，可以修改 `/etc/hosts` 文件的权限，让当前用户可写（当然，这样也有一定风险……）。

**Comment by teshoudong** [comment]
好吧
