### ISSUE TITLE
macOS，随便打开一个应用，全屏状态，点击菜单栏中的图标无法显示下拉菜单

### ISSUE THREAD

**Issue by Sligcm** [oldj/SwitchHosts#275]
### 操作系统
macOS 10.13.2

### SwitchHosts! 版本
v3.3.8 (5338)

### 问题描述
如题

### 重现步骤
如题

**Comment by wangkira** [comment]
macOS 10.13.3
v3.3.9(5343) 同样问题

**Comment by Sligcm** [comment]
> macos 10.14 (18A391)
> v3.3.12(5349)
> 没有此问题...供参考

v3.3.12(5349)确实没有这个问题了。
