### ISSUE TITLE
编辑 hosts 时当前编辑行位置移动问题

### ISSUE THREAD

**Issue by Sherljohn** [oldj/SwitchHosts#277]
### 操作系统
macOS High Sierra
版本 10.13.2

### SwitchHosts! 版本
v3.3.9
v3.3.8

### 问题描述
编辑时会自动将当前编辑行的位置移到窗口底部（现象就是闪一下）。
这个比较难描述，我直接举个栗子：
假设我有 100 行 IP 绑定，再假设当前窗口一页最多显示 20 行，那第 25 行应该在第二页。我现在把第 25 行移动到当前窗口中间的位置（当前窗口第一行是 Line 15， 最底部是 Line 34）。编辑第 25 行，比如输入几个空格。闪一下的结果就是本来第 25 行在中间的位置，突然变成了当前窗口最底部（当前窗口第一行是 Line 6， 最底部是 Line 25）。

### 重现步骤
编辑 hosts 时，非必现，但是概率蛮高的。

**Comment by smile-magic** [comment]
是的,我也经常出现.编辑时突然一闪跳到别的行.出现频率很频繁.望修复,谢谢
