### ISSUE TITLE
能移植个安卓版本吗？

### ISSUE THREAD

**Issue by panhezeng** [oldj/SwitchHosts#278]

**Comment by linkdesu** [comment]
我不是项目的参与者，只是路过做一点说明：你这个需求恐怕不太可能被满足，SwitchHosts! 是基于 Atom 开发的，这个框架只支持桌面跨平台。如果要到移动端去做相当于要从头再来一个，不是简单的移植了，而如你所见这是个开源项目，大家的精力有限。

**Comment by lowwor** [comment]
android的可以用这个，https://github.com/iTXTech/Daedalus/，不需要root

**Comment by oldj** [comment]
感谢 @linkdesu 的解释，的确是这样，所以暂时没有做安卓版本的计划。也感谢 @lowwor 的推荐，安卓用户可以试一下。
