### ISSUE TITLE
建议：远程环境内容框建议背景跟本地或组合区别

### ISSUE THREAD

**Issue by IT513** [oldj/SwitchHosts#280]
### 问题描述
当前分 本地、远程、组合等环境
本地可以修改， 远程的是不可以修改的。当前是远程的内容框与其他没有区别。
没有区别老是误导成可点击修改... 但是实际是不可以修改的，如果远程环境的内容框 是只读背景颜色为灰色或其他颜色 这样就不用误导...

**Comment by oldj** [comment]
远程方案右上角有一个小锁，提示不可修改，不过这个提示可能不太明显……。感谢反馈，后面会考虑一下增加差异…… 😶

![image](https://user-images.githubusercontent.com/416130/37031029-32b556c0-2178-11e8-9557-2a9050c25b06.png)
