### ISSUE TITLE
启动时，弹出错误：SwitchHosts! 已停止工作

### ISSUE THREAD

**Issue by bjlxfh** [oldj/SwitchHosts#283]
### 操作系统
windows 7

### SwitchHosts! 版本
[v3.3.9]

### 问题描述
启动时，弹出错误：SwitchHosts! 已停止工作
问题事件名称:	BEX64
  应用程序名:	SwitchHosts!.exe
  应用程序版本:	5343.0.0.0
  应用程序时间戳:	5a665abd
  故障模块名称:	StackHash_b5a5
  故障模块版本:	0.0.0.0
  故障模块时间戳:	00000000
  异常偏移:	0000000000000000
  异常代码:	c0000005
  异常数据:	0000000000000008
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他信息 1:	b5a5
  其他信息 2:	b5a52b638795d47144f18984e08cfc42
  其他信息 3:	1a67
  其他信息 4:	1a6783ae82ccec0cd273bb4a637e6b12

### 重现步骤
如上所述。。

**Comment by czhuyu** [comment]
+1

**Comment by dulinanaaa** [comment]
+1

**Comment by zsw12013** [comment]
+1
