### ISSUE TITLE
双系统 hosts 切换失败

### ISSUE THREAD

**Issue by q2qiang** [oldj/SwitchHosts#284]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

window7

### Description / 描述

我的电脑是双系统的，win7系统的hosts 不在 C 盘，导致修改失败，能告知我在哪里可以写死 hosts 获取路径么

**Comment by oldj** [comment]
你使用的 SwitchHosts! 版本是什么呢？目前最新版本是 [v3.3.9](https://github.com/oldj/SwitchHosts/releases) 。

最新的版本中已经考虑到[系统不在 C 盘的情况](https://github.com/oldj/SwitchHosts/blob/a49121e5310d84bd25591e46063ad316c5e52eaa/app/server/paths.js#L13)，启动时会先从环境变量中读取系统所在目录，应该能正常处理你说的情况。

**Comment by q2qiang** [comment]
问题已经 ok ，thks
