### ISSUE TITLE
v3.3.10版本修改hosts无法保存

### ISSUE THREAD

**Issue by laoqiren** [oldj/SwitchHosts#287]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac
### SwitchHosts! Version / SwitchHosts! 版本

v3.3.10

### Description / 描述

修改hosts，保存功能失效，切换生效和不生效，修改内容会自动恢复，切换到其他版本解决该问题

### How to reproduce / 重现步骤

* 新建hosts配置
* 添加内容，切换生效
* 修改配置，尝试保存
* 切换为不生效，发现修改内容恢复

**Comment by oldj** [comment]
问题的确存在，感谢反馈！

**Comment by oldj** [comment]
可以试试最新的版本，比如 [v3.3.11](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.11) ，这个问题应该修复了。
