### ISSUE TITLE
图标换个不要这么醒目的

### ISSUE THREAD

**Issue by yehuijun** [oldj/SwitchHosts#29]
图标换个不要这么醒目的， 例如淡蓝色， 淡绿色，淡黄色， 旺旺 轩辕剑 的颜色。

一般太亮了  我会关了它， 因为分散了工作注意力

**Comment by oldj** [comment]
试试 [v3.1](https://github.com/oldj/SwitchHosts/releases) 版？现在用单色图标了。:)
