### ISSUE TITLE
功能建议：白名单

### ISSUE THREAD

**Issue by laggardkernel** [oldj/SwitchHosts#292]
建议加入白名单功能，基本效果是这样：
在多个host表（本地或是远程订阅）合并应用到`/etc/hosts/`前，将白名单中`Hostname`对最终的合成表条目匹配，若匹配到，则删除合成表中条目。之后，再将合成表应用到`/etc/hosts`。

之前在AdAway（Android app）见到过此功能，白名单条目内容仅为`Hostname`，不需要对应IP。主要应用场景：**排除订阅列表中的条目，不应用到最终hosts文件**。另外建议白名单中Hostname条目支持通配符`*`和`?`。

**Comment by laggardkernel** [comment]
算了，自己搞个列表调用sed直接操作hosts文件好了。

**Comment by oldj** [comment]
赞，如果写好了，方便的话可以分享一下给大家。🙂
