### ISSUE TITLE
添加操作时提示轻易管理员身份运行

### ISSUE THREAD

**Issue by look0613415** [oldj/SwitchHosts#316]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Windows 10 x64

### SwitchHosts! Version / SwitchHosts! 版本

3.3.12

### Description / 描述

以管理员运行后，添加操作时提示轻易管理员身份运行

**Comment by zlren** [comment]
我也是，即使右键以管理员身份运行后依旧提示权限问题

**Comment by candyguy242** [comment]
同样

**Comment by look0613415** [comment]
> 我也是，即使右键以管理员身份运行后依旧提示权限问题

等更新吧

**Comment by zoumt1633** [comment]
修改下你正在使用的用户权限，改为完全控制，

**Comment by zoumt1633** [comment]
切换失败是因为权限不够，解决办法如下：

1.找到host文件

C:\Windows\System32\drivers\etc

2.右键host，点击属性，选择安全

3.赋予User所有权限

**Comment by xspeed1989** [comment]
electron 兼容性始终没有Native程序好！

**Comment by YoungLedo** [comment]
> 切换失败是因为权限不够，解决办法如下：
> 
> 1.找到host文件
> 
> C:\Windows\System32\drivers\etc
> 
> 2.右键host，点击属性，选择安全
> 
> 3.赋予User所有权限

并不行。
