### ISSUE TITLE
支持使用scoop安装switchhosts

### ISSUE THREAD

**Issue by spkingr** [oldj/SwitchHosts#321]
### System (Windows 7/8/10) / 操作系统
win10

### SwitchHosts! Version / SwitchHosts! 版本
任意

### Description / 描述
使用scoop安装switchhosts：

`scoop install switchhosts`

**Comment by ahunigel** [comment]
Install failed with following errors
```
PS D:\Apps> scoop install switchhosts
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'switchhosts' (3.4.0) [64bit]
Loading SwitchHosts._windows_installer_3.4.0.5450.exe from cache.
Checking hash of SwitchHosts._windows_installer_3.4.0.5450.exe ... ok.
Extracting dl.7z ... Expand-7zipArchive : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At D:\Apps\Scoop\apps\scoop\current\lib\install.ps1:558 char:13
+             & $extract_fn -Path "$dir\$fname" -DestinationPath "$dir\ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Expand-7zipArchive], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Expand-7zipArchive
```

**Comment by ahunigel** [comment]
It seems like 7zip not completely installed caused this problem

> Install failed with following errors
> 
> ```
> PS D:\Apps> scoop install switchhosts
> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
> Installing 'switchhosts' (3.4.0) [64bit]
> Loading SwitchHosts._windows_installer_3.4.0.5450.exe from cache.
> Checking hash of SwitchHosts._windows_installer_3.4.0.5450.exe ... ok.
> Extracting dl.7z ... Expand-7zipArchive : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
> At D:\Apps\Scoop\apps\scoop\current\lib\install.ps1:558 char:13
> +             & $extract_fn -Path "$dir\$fname" -DestinationPath "$dir\ ...
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Expand-7zipArchive], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationError,Expand-7zipArchive
> ```

It seems like 7zip not completely installed caused this problem

BTW, this issue could be closed
