### ISSUE TITLE
如何找回原来的hosts

### ISSUE THREAD

**Issue by li0817** [oldj/SwitchHosts#324]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
win10

### SwitchHosts! Version / SwitchHosts! 版本
v3.3.12 (5349)

### Description / 描述
默认的hosts被覆盖了，如何找回

### How to reproduce / 重现步骤
1. 下载、打开switchhosts
2. 打开系统的 hosts，将系统的 hosts 内容转移至 switchhosts
3. 系统的 hosts 里原来的内容尽数消失，只显示了一行 # switchhost! ，无法进行转移
4. 删除switchhosts，原系统hosts内容依旧没有恢复
5. 如何找回

**Comment by oldj** [comment]
首次打开 SwitchHosts! 的时候应该会自动生成两个方案，其中一个名为 backup 的方案内容为原来 hosts 的备份，如下图：

![image](https://user-images.githubusercontent.com/416130/47263986-3265fa00-d53f-11e8-92a5-3f84a632601f.png)

如果你没有手动删除 backup 方案，或者将 SwitchHosts! 的数据文件（位于 `~/.SwitchHosts/data.json`）整个删除，应该还能从 backup 中找回原来的内容。

**Comment by li0817** [comment]
backup之前看了记得里面没东西，my hosts和backup 都是空的，所以以为把生成的方案删了应该就恢复默认了，所以默认的两个方案就都删了；
数据文件我之前也去看过了，没删，因为没啥东西
![image](https://user-images.githubusercontent.com/27659768/47264095-de104980-d541-11e8-9c78-5652a54ade08.png)

再者，之前为了恢复默认的，我把switchhosts整个程序的文件夹也删了，然后再把下载的东西又放了进去，所以这时即便出现了backup备份的也应该是空文件了，所以应该是找不回来了吧；而这个操作来回做了三遍

刚刚第四遍，又把switchhosts下下来看了下，确实已经空了
![image](https://user-images.githubusercontent.com/27659768/47264112-52e38380-d542-11e8-9ce1-fca05fe3ce13.png)

**Comment by oldj** [comment]
那应该是找不回来了…… :'(

按理 backup 不应该为空的，我也再检查一下代码。

**Comment by li0817** [comment]
找不回就算了，有意解决就行；可以在说明文档里写一下，也可以在初次运行时弹出是否覆盖系统 hosts 的对话框之类的，至少得把“打开即自动覆盖”这一行为放在显著位置说明才是
