### ISSUE TITLE
建议退出时自动删除 SnoreToast

### ISSUE THREAD

**Issue by BYZYB** [oldj/SwitchHosts#334]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10

### SwitchHosts! Version / SwitchHosts! 版本
v3.3.12 (5349)

### Description / 描述
![image](https://user-images.githubusercontent.com/34391595/48662075-532a5c80-eab7-11e8-9d4c-a7710c026bb9.png)
如上图，每当启用/切换 hosts 时，都会有相关的 Toast 通过 SnoreToast 弹出；但程序退出后，SnoreToast 仍继续留在 %localappdata%\Temp\ 中，且会自动在开始菜单中创建快捷方式。
建议在程序退出时可以自动删除 SnoreToast 及其快捷方式。

### How to reproduce / 重现步骤
打开或切换任意 hosts 的开关之后。

**Comment by dsyo2008** [comment]
同样问题，退出依旧还在。希望改善一下。
