### ISSUE TITLE
左侧栏右下角图标作用

### ISSUE THREAD

**Issue by derotyang** [oldj/SwitchHosts#340]
左侧栏右下角那个黑白橡皮一样的按钮什么作用？

这个设计也是无力吐槽了，

猜测是切换正反代理，但是一点都不明显

**Comment by francis707** [comment]
加个tooltip也好啊，都不知道是干嘛用的，一点就清空系统hosts了

**Comment by oldj** [comment]
感谢反馈。这个功能不常用，增加了理解成本，目前的版本中已将它移除。
