### ISSUE TITLE
支持分钟级别的同步

### ISSUE THREAD

**Issue by cwtuan** [oldj/SwitchHosts#343]
### SwitchHosts! Version / SwitchHosts! 版本
3.3.13

### Description / 描述
目前同步时间最小是一小时，希望能够支持5分钟同步一次。
![image](https://user-images.githubusercontent.com/3455798/51440349-2b4ab580-1d01-11e9-81aa-a615c56c4ac0.png)

**Comment by nabaonan** [comment]
导出json后，将更新时间更改成0.01666666就是相当于1分钟了把，然后再倒入
