### ISSUE TITLE
一个CTRL+Z的BUG

### ISSUE THREAD

**Issue by LKGin** [oldj/SwitchHosts#348]
WIN7 X64下
现有hostsA和B,在左侧栏选择A，再选择B进入编辑状态，按下CTRL+Z，当前B方案会被A完全覆盖。（当时使用CTRL+Y可以恢复的）
使用最新64位版本3.3.12多次测试均有次现象。
搜索发现已有反馈
https://github.com/oldj/SwitchHosts/issues/161

**Comment by oldj** [comment]
感谢反馈，会在下一个版本修复。
