### ISSUE TITLE
启动时弹窗报错:A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by sunxiaochuan1300** [oldj/SwitchHosts#359]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10
### SwitchHosts! Version / SwitchHosts! 版本
3.312
### Description / 描述
Error
A JavaScript error occurred in the main processUncaught Exception:Error: ENOENT: no such file or directory, open'C:\Windows\system32\drivers\etc\hosts'at Object.fs.openSync (fs.js:652:18)at Object.module.(anonymous function) [as openSync](ELECTRON ASAR.js:172:20)at Object.fs.readFileSync (fs.js:553:33)at Object.fs.readFileSync (ELECTRON ASAR.js:508:29)at module.exports(D:SwitchHosts\SwitchHosts!-win32-x64\resources\app.asar\server\initWorkP..: 16 at Object. <anonymous>(D:\SwitchHosts\SwitchHosts!-win32-x64\resources\app.asar\server\paths.js:22:28) at Object.<anonymous>(D:\SwitchHosts\SwitchHosts!-win32-x64\resources\app.asar\server\paths.js:48:31 at Module. compile (module.js:569:30)at Object.Module. extensions..js (module.js:580:10) at Module.load (module.js:503:32)

**Comment by sunxiaochuan1300** [comment]
朋友们，我的文件已经解决了，问题是我的hosts文件有一个后缀 hosts.iso，我把后缀.iso删除了就能打开SwitchHosts了

**Comment by sunxiaochuan1300** [comment]
朋友们，我的问题已经解决了，问题是我的hosts文件有一个后缀hosts.iso，我把后缀.iso删除了就能打开SwitchHosts了

**Comment by oldj** [comment]
感谢反馈！
