### ISSUE TITLE
在MAC下打开提示错误：“SwtichHosts! Error”

### ISSUE THREAD

**Issue by chaoren1641** [oldj/SwitchHosts#36]
之前使用是OK的，现在打开突然弹出这个提示，就不能用了，重新下载安装也没有用，求解决方案
![image](https://f.cloud.github.com/assets/404245/510525/9275b6e8-bdd9-11e2-93e0-3ad17ea91197.png)

**Comment by mycoin** [comment]
公共Hosts太多的原因

**Comment by oldj** [comment]
感谢 @mycoin 。

ps. Mac 用户可以试试新版本：https://github.com/oldj/SwitchHosts/releases/tag/v3.0.0 。:)
