### ISSUE TITLE
一些编辑快捷键问题，希望优化

### ISSUE THREAD

**Issue by JellyWhite** [oldj/SwitchHosts#365]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
MAC 10.14.4

### SwitchHosts! Version / SwitchHosts! 版本
V3.3.12

### Description / 描述
复制，粘贴快捷键不好使，希望能沿用系统自己的默认快捷键

**Comment by oldj** [comment]
不是很明白。编辑器中 <kbd>Cmd</kbd> + <kbd>C</kbd> 以及 <kbd>Cmd</kbd> + <kbd>V</kbd> 键可以使用啊？
