### ISSUE TITLE
在win8 x64运行后打不开界面

### ISSUE THREAD

**Issue by yuanhaoliang** [oldj/SwitchHosts#37]
最新版本,0.2.2.1797,之前是可以的,后来不知道什么时候开始,启动后就不弹出界面来了,托盘是有的,但是右键没反应,双击也激活不了主界面,简单一句话,用不了了~~~~~~~~~~~~

**Comment by GavinSheng** [comment]
win10 也有同样的问题，host比较多的时候经常出问题
