### ISSUE TITLE
`Remote Hosts Refresh Error` after upgrading to v3.3.13

### ISSUE THREAD

**Issue by JounQin** [oldj/SwitchHosts#372]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Darwin MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

### SwitchHosts! Version / SwitchHosts! 版本
v3.3.13

### Description / 描述
As title

### How to reproduce / 重现步骤
Remote Hosts:
https://raw.githubusercontent.com/Mosiki/github/master/github_hosts.txt

**Comment by zizhazhu** [comment]
I face the same problem

**Comment by JounQin** [comment]
That works, thx!
