### ISSUE TITLE
远程 hosts 内容自动刷新时间间隔可否自行调整？

### ISSUE THREAD

**Issue by shimmerXXX** [oldj/SwitchHosts#373]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

mac windows

### SwitchHosts! Version / SwitchHosts! 版本
v3.3.12 (5349)

### Description / 描述
最短一小时的间隔在某些场景下过于迟缓了。如果有分钟级或者可以自定义的时间间隔就太棒了

**Comment by oldj** [comment]
![image](https://user-images.githubusercontent.com/416130/115133876-13784e00-a03e-11eb-9df6-16905ec4f5c5.png)

现在最短时间间隔可以设置为 1 分钟了。
