### ISSUE TITLE
启动失败，看了下有两个人反映过了，但是没人理会

### ISSUE THREAD

**Issue by LangsStudio** [oldj/SwitchHosts#374]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Win10

### SwitchHosts! Version / SwitchHosts! 版本
V3,3,12,5349

### Description / 描述
A javaScript erro...具体我就不弄了，没工具直接转，详情可以看其他
https://github.com/oldj/SwitchHosts/issues/366#issue-446091005

### How to reproduce / 重现步骤
这个启动需要环境? 在我两台电脑中启动都是必然出现。。。

**Comment by FlyDamao** [comment]
将你的用户账户提升权限，具体可以参考https://www.cnblogs.com/jepson6669/p/9737645.html

**Comment by LangsStudio** [comment]
> 将你的用户账户提升权限，具体可以参考https://www.cnblogs.com/jepson6669/p/9737645.html
看着不像是这个对hosts操作权限不够的问题啊。软件在启动就提示错误崩溃了。我去试试看吧。

**Comment by oldj** [comment]
看起来像是启动网络服务时失败。

SwitchHosts! 启动时会启动一个网络服务，地址为 http://127.0.01:50761 ，用于给 [Alfred 插件](http://www.packal.org/workflow/switchhosts)等工具使用。是不是本地有软件禁用了 SwitchHosts! 的网络服务？
