### ISSUE TITLE
win10 v3.3.13版本安装完成后运行 报错

### ISSUE THREAD

**Issue by Vibing** [oldj/SwitchHosts#375]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Win10

### SwitchHosts! Version / SwitchHosts! 版本
3.3.13

### Description / 描述
安装完成后运行 报错
![微信截图_20190710141656](https://user-images.githubusercontent.com/10387532/60945157-66778a00-a31d-11e9-9b42-a8284c292121.png)

### How to reproduce / 重现步骤
以管理员身份安装和运行 SwitchHosts，运行后直接报错

**Comment by tyonly** [comment]
你用的是portable版本吧？用安装版到没事

chenLong <notifications@github.com> 于2019年7月10日周三 下午2:19写道：

**Comment by Vibing** [comment]
@tyonly installer和portable都试过 都不行

**Comment by 570805869** [comment]
楼主问题解决了吗，我遇到了相同的问题

**Comment by Wuun** [comment]
遇到相同问题了，没解决

**Comment by Vibing** [comment]
@570805869 @Wuun 没解决 换Mac了

**Comment by shimmerXXX** [comment]
> @570805869 @Wuun 没解决 换Mac了
mac标表示也碰到了相同的问题。

**Comment by oldj** [comment]
感谢反馈，应该是在初始化工作目录时出了问题，比如无法创建工作目录之类。下一个版本会尝试显示更友好的信息。
