### ISSUE TITLE
希望增加配置项，可以让 mac 菜单栏只保留 icon

### ISSUE THREAD

**Issue by dreamerblue** [oldj/SwitchHosts#376]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
macOS 10.14.5

### SwitchHosts! Version / SwitchHosts! 版本
3.3.14

### Description / 描述
mac 上菜单栏会显示一大串已开启 host 的名称，菜单栏空间本来就寸土寸金。希望给一个配置，像以前版本一样只显示 icon，不显示已开启 host 列表。

**Comment by oldj** [comment]
感谢反馈，下个版本会添加这个配置项。

**Comment by oldj** [comment]
[v3.4.0](https://github.com/oldj/SwitchHosts/releases/tag/v3.4.0) 中新增了对应的设置，见下图：

![image](https://user-images.githubusercontent.com/416130/61963091-82f21280-affd-11e9-9d25-fa1f7b5d8c6f.png)
