### ISSUE TITLE
macOS 10.14.3 启动报js错误 

### ISSUE THREAD

**Issue by shimmerXXX** [oldj/SwitchHosts#377]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

macOS 10.14.3

### SwitchHosts! Version / SwitchHosts! 版本

3.3.14

### Description / 描述

启动报错
![image](https://user-images.githubusercontent.com/52687961/61941548-4d800180-afca-11e9-95fe-61e44211dfe4.png)

**Comment by oldj** [comment]
感谢反馈，与 #375 是同一个问题。
