### ISSUE TITLE
启动报错 Error:listen EACCESS: permission denied 127.0.0.1:50671

### ISSUE THREAD

**Issue by francis707** [oldj/SwitchHosts#378]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10 专业版 Build 17763

### SwitchHosts! Version / SwitchHosts! 版本
v3.4.0

### Description / 描述
启动报错：
Error:listen EACCESS: permission denied 127.0.0.1:50671

![QQ截图20190727145612](https://user-images.githubusercontent.com/35424113/61991159-bc1e9700-b07e-11e9-926d-a0839d55c38f.png)

netstat -ano|findstr 50761 没有进程

点“确定”之后软件正常启动，也能正常使用

### How to reproduce / 重现步骤
安装时选为所有用户安装，安装位置：C:\Program Files\switchhosts，弹出UAC提示之后点同意，安装成功，但是启动报错，点“确定”之后软件正常启动，也能正常使用

**Comment by francis707** [comment]
选 只为当前用户安装 也是一样的错误

**Comment by francis707** [comment]
#366 #374

**Comment by capricornxl** [comment]
我也碰到这个问题了，跟你截图中一模一样。

**Comment by LauWingHung** [comment]
一样,现在还没解决哦

**Comment by lzskyline** [comment]
一样

**Comment by yukunshang** [comment]
一样

**Comment by cheerfulman** [comment]
一样

**Comment by edwinhuish** [comment]
同样的问题，mark 一下

**Comment by oldj** [comment]
这个是 HTTP API 服务，主要是提供给 Alfred 等第三方快捷启动软件用的，[v3.5.8](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.8) 版可以在设置中将这个服务关闭。

见下图：

![image](https://user-images.githubusercontent.com/416130/109374515-c9ea6d00-78f0-11eb-9760-795c0f4f3a16.png)

**Comment by francis707** [comment]
新版本这个选项默认关闭没问题了

**Comment by CongAn** [comment]
找到原因了！

因为`50761`是hyper-v的保留端口。

运行以下命令可以查看哪些端口被保留了。

```powershell
netsh interface ipv4 show excludedportrange protocol=tcp
```

1. 解决方案是删除这个保留端口。（不推荐，删掉后鬼知道hyper-v会出什么问题）。
2. 修改SwitchHosts代码，自行打包。


参考资料

* [Windows 10禁止端口绑定](https://pomeroy.me/2020/09/solved-windows-10-forbidden-port-bind/)
* [不能通过使用 Windows Server 2008 或 Windows Server 2008 R2 中的 ReservedPorts 注册表项排除端口](https://support.microsoft.com/en-us/topic/you-cannot-exclude-ports-by-using-the-reservedports-registry-key-in-windows-server-2008-or-in-windows-server-2008-r2-a68373fd-9f64-4bde-9d68-c5eded74ea35)

**Comment by CongAn** [comment]
## 如何修改 SwitchHosts 客户端的HTTP API的端口号？（Windows & Cmd）

#### 安装`nodejs`

```
https://nodejs.org/
```

进入官网下载并安装`nodejs`。


#### 安装`asar`解压压缩工具

```shell
 npm i @electron/asar -g
```

速度慢就配置npm淘宝镜像源。

#### 解压SwitchHosts安装目录下的`app.asar`

```shell
asar extract %UserProfile%\AppData\Local\Programs\SwitchHosts\resources\app.asar %UserProfile%\AppData\Local\Programs\SwitchHosts\resources\app
```

示例是安装到用户目录的SwitchHosts。

#### 替换文件内`50761`端口

利用编辑器等工具，搜索并替换解压出来的`app`目录下所有文件中的`50761`为你想要设置的端口，例如`40761`。

#### 重新打包`app.asar`

```shell
asar pack %UserProfile%\AppData\Local\Programs\SwitchHosts\resources\app %UserProfile%\AppData\Local\Programs\SwitchHosts\resources\app.asar
```
