### ISSUE TITLE
强烈要求添加搜索功能，再加备份功能

### ISSUE THREAD

**Issue by musdenisbetter** [oldj/SwitchHosts#38]
强烈要求添加搜索功能，再加备份功能

**Comment by oldj** [comment]
新版本中已经有搜索功能。

关于备份，用户第一次运行 SwitchHosts! 时，会将当前系统的 hosts 内容备份为一个叫 *backup* 的方案，列在左侧；

如果用户想备份所有的 hosts 方案，可以在 File 菜单中导出，输出结果为一个 json 文件。
