### ISSUE TITLE
系统Host页面可以用Ctrl+/进行注释与反注释，让人产生一种修改了Host的错觉

### ISSUE THREAD

**Issue by ztyzbb** [oldj/SwitchHosts#384]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows10

### SwitchHosts! Version / SwitchHosts! 版本
v3.3.14 (5404)

### Description / 描述
系统Host页面可以用Ctrl+/进行注释与反注释，让人产生一种修改了Host的错觉，实际上并没有修改，切换到其他Host列表，再切回来会还原

### How to reproduce / 重现步骤
在系统Host页面用Ctrl+/注释一行，切换到其他Host方案，再切换回来，更改消失了

**Comment by oldj** [comment]
新版本中这个问题已修复。
