### ISSUE TITLE
如何启动项目，并修改

### ISSUE THREAD

**Issue by OliverWeb** [oldj/SwitchHosts#386]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
win10

### SwitchHosts! Version / SwitchHosts! 版本
3.5.0

### Description / 描述

npm run dev 修改内容没有，页面没有改变，需要重新npm run dev

### How to reproduce / 重现步
clone 项目后出现，

**Comment by oldj** [comment]
暂时没有热重载。修改代码并 build 之后，可以在 App 界面按 <kbd>Cmd</kbd> + <kbd>R</kbd> （Windows 下为 <kbd>Ctrl</kbd> + <kbd>R</kbd>）刷新，就像刷新网页一样。
