### ISSUE TITLE
host左侧滚动不了

### ISSUE THREAD

**Issue by SUH11** [oldj/SwitchHosts#396]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
mac air

### SwitchHosts! Version / SwitchHosts! 版本
3.5.0

### Description / 描述
左侧菜单栏不可以滚动，很多个host的时候就滚动不到最下面了 切不了

### How to reproduce / 重现步骤
1.打开软件
2.导入原来的host 很多个
3.拉不到就下面

**Comment by raphaelchaib** [comment]
Cannot scroll the sidebar list of hosts neither. Something broke in the new release. I got back to 3.4.0 and now it works again.

**Comment by pop-lee** [comment]
+1

**Comment by WPF0414** [comment]
3.5有此问题，希望解决。非常感谢。给你点赞
