### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by nKsnC** [oldj/SwitchHosts#397]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Windows10 

### SwitchHosts! Version / SwitchHosts! 版本

switchhosts3.5

### Description / 描述

中文乱码，backup里的中文乱码
重新创建的模式，输入中文没有乱码

**Comment by oldj** [comment]
SwitchHosts! 内部使用的是 UTF-8 编码，如果你使用的是 Windows，并且 hosts 文件之前写入过 GBK 编码的汉字等内容，首次运行 SwitchHosts! 时生成的 backup 内容就会是乱码。

Node.js 似乎没有好用的编码探测库，这个问题暂时没有好的解决办法。如果你的 hosts 文件中有非 UTF-8 字符，目前建议先手动转换一下。
