### ISSUE TITLE
多级文件夹时，子文件夹和方案无法删除

### ISSUE THREAD

**Issue by lizhuangs** [oldj/SwitchHosts#401]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
win10

### SwitchHosts! Version / SwitchHosts! 版本
3.5

### Description / 描述
新建了一个多级文件夹，子文件夹无法删除，只能把子文件夹拖到根目录才可以。而且只能删除子目录，不能删除子目录里面的本地方案，不知道是不是和我上面提的一个issue有关，因为这些目录里面的本地方案都是同一个默认放进去的。
![QQ五笔截图未命名](https://user-images.githubusercontent.com/7904121/66693061-461de980-ecd7-11e9-954a-64e74c72ae91.jpg)

### How to reproduce / 重现步骤
新建多级目录，然后删除子目录。

**Comment by Vincent1993** [comment]
遇到了同样的问题，只能移动到顶层目录才能被删除

**Comment by lizhuangs** [comment]
> 遇到了同样的问题，只能移动到顶层目录才能被删除

多级文件夹问题实在太多了，不过勉强可用，希望作者有空可以修复吧。尤其是拖动，多个文件夹和目录重名的情况。

**Comment by oldj** [comment]
试试 [v3.5.1](https://github.com/oldj/SwitchHosts/releases)，应该已经修复了。

**Comment by lizhuangs** [comment]
谢谢，可以了！
