### ISSUE TITLE
编辑过程中快捷键撤销内容丢失

### ISSUE THREAD

**Issue by ihaiker** [oldj/SwitchHosts#402]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
mac

### SwitchHosts! Version / SwitchHosts! 版本
v3.3.12 (5349)

### Description / 描述
编辑过程中快捷键撤销内容丢失

### How to reproduce / 重现步骤
1、编辑随意内容
2、快捷键撤销、内容丢失

**Comment by oldj** [comment]
试一试新版本？
