### ISSUE TITLE
安装后系统告警，来自未受信任的开发者。

### ISSUE THREAD

**Issue by mushi007** [oldj/SwitchHosts#412]
### System (Mac,10.15.1) / 操作系统
macOS 10.15.1

### SwitchHosts! Version / SwitchHosts! 版本3.5.1
版本3.5.1

### Description / 描述
安装后系统告警，来自未受信任的开发者。

**Comment by oldj** [comment]
暂时不知道怎么处理这个开发者证书信任问题，也希望有经验的朋友指点一下。😅

目前可以在访达中右键单击 App 图标，在弹出菜单中选择【打开】，即可正常打开。

**Comment by ElfSundae** [comment]
@oldj 编译后要用苹果开发者账号签名
