### ISSUE TITLE
已经用了管理员权限打开，但Windows10还是用不了。

### ISSUE THREAD

**Issue by hmony** [oldj/SwitchHosts#419]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10 1909 18363.476

### SwitchHosts! Version / SwitchHosts! 版本
3.5.2 5504

### Description / 描述
无法切换hosts

### How to reproduce / 重现步骤
先设置Switchhosts 为用管理员权限打开，双击图标打开，是否使用管理员，是的，然后会提示下图，然后切换hosts时也会提示下图。无法使用hosts功能。

**Comment by tldzyx** [comment]
同Windows10下无法使用, 已经使用管理员权限启动了.

**Comment by hmony** [comment]
@tldzyx 问题找到了，是装了其他软件，导致其他软件让hosts文件给设置成只读导致的，修改成去掉只读就可以了。
