### ISSUE TITLE
3.5.3 版 mac 无法导出

### ISSUE THREAD

**Issue by nicholasxuu** [oldj/SwitchHosts#430]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac OSX Catalina v10.15.2

### SwitchHosts! Version / SwitchHosts! 版本

3.5.3 

### Description / 描述

3.5.3 导出后，文件不会出现。
降到3.5.2就好了。

### How to reproduce / 重现步骤

导出，选择文件夹，确定 => 看似完成了，但是没有json文件，试过多个文件夹地址都没用。（mac也没提示”app要download文件夹的权限“之类的）

**Comment by oldj** [comment]
感谢反馈，会在下次发布中修复。

**Comment by oldj** [comment]
可以试一试 [v3.5.4](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.4) 。

**Comment by nicholasxuu** [comment]
v3.5.4好了~
