### ISSUE TITLE
Export does not write any files

### ISSUE THREAD

**Issue by s0lucien** [oldj/SwitchHosts#432]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10

### SwitchHosts! Version / SwitchHosts! 版本
3.5.3(5514)

### Description / 描述
Export does not write any files

### How to reproduce / 重现步骤
Open SwitchHosts, select a configuration, Settings -> Export . 
Name the file, press OK.
No file is created by the export function

**Comment by oldj** [comment]
Thanks for the feedback, it will be fixed in the next release.

**Comment by oldj** [comment]
#430
