### ISSUE TITLE
打开客户端后弹出js error

### ISSUE THREAD

**Issue by Sanmejie** [oldj/SwitchHosts#433]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

win10

### SwitchHosts! Version / SwitchHosts! 版本
v3.5.3 (5514)

### Description / 描述
打开客户端后弹出js error

### How to reproduce / 重现步骤
在win10系统下打开SwitchHosts!
![image](https://user-images.githubusercontent.com/40269911/72318508-69da3c80-36d7-11ea-9bdf-fb4ad487e2e5.png)

**Comment by yukunshang** [comment]
同这个错误 打开50761端口 发现也没有任何软件占用

**Comment by oldj** [comment]
新版中这个 HTTP API 服务默认关闭，需要的用户可以在设置中手动开启。
