### ISSUE TITLE
无法导出json文件

### ISSUE THREAD

**Issue by Sanmejie** [oldj/SwitchHosts#434]
System (Mac, Windows 7/8/10, Linux) / 操作系统
win10（教育版）

SwitchHosts! Version / SwitchHosts! 版本
v3.5.3 (5514)

Description / 描述
无法导出json文件

How to reproduce / 重现步骤
1.打开SwitchHosts!
2.点击主界面“小扳手”图标
3.导出到电脑桌面

结果没有json文件生成。

**Comment by oldj** [comment]
感谢反馈，会在下次发布中修复。

**Comment by oldj** [comment]
与 #430 重复，先关闭。
