### ISSUE TITLE
Question: Why are there so many forks?

### ISSUE THREAD

**Issue by josias-r** [oldj/SwitchHosts#443]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Mac Catalina

### SwitchHosts! Version / SwitchHosts! 版本
3.5.v

### Description / 描述
This application seems great and does its job. I'm just really really curious why there are over 1k forks? Is there a major bug in this application or do they patch out a hidden trojan? 😂

**Comment by oldj** [comment]
I think a possible reason is that this is a simple project based on [Electron](https://www.electronjs.org/), some people may want to refer to this project to make their Electron application. This is just my guess. 😂

**Comment by josias-r** [comment]
Wow, interesting. 9k stars, 1k forks. 1 out of 9 GitHub users forked it 🤯.
Thanks for this great and simple tool, it replaced the ugly gas mask application I had before.
