### ISSUE TITLE
Remote Hosts Refresh Error

### ISSUE THREAD

**Issue by xiaoshiguang123** [oldj/SwitchHosts#445]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Windows 10

### SwitchHosts! Version / SwitchHosts! 版本

v3.5.4

### Description / 描述

hosts为远程地址时点击刷新按钮提示

Remote Hosts Refresh Error

ECONNRESET

### How to reproduce / 重现步骤

使用Clash代理全局依旧无法刷新

地址: https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt

**Comment by xiaoshiguang123** [comment]
发现只有引用github资源时出现问题,已使用CDN方式解决无法更新的问题,目测应该是该软件没有通过代理访问远程配置文件,
地址:https://cdn.jsdelivr.net/gh/vokins/yhosts@master/hosts.txt

**Comment by drw2005** [comment]
> 发现只有引用github资源时出现问题,已使用CDN方式解决无法更新的问题,目测应该是该软件没有通过代理访问远程配置文件,
> 地址:https://cdn.jsdelivr.net/gh/vokins/yhosts@master/hosts.txt
确实有这个问题，引用github资源无法更新，用你这个CDN方式正常。最新的3.5.6.5551也是如此。
