### ISSUE TITLE
远程不能自动更新

### ISSUE THREAD

**Issue by Got99** [oldj/SwitchHosts#452]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

mac  10.14.6

### SwitchHosts! Version / SwitchHosts! 版本
3.5.4

### Description / 描述
我更新一个码云上的hosts 
https://gitee.com/pbug/hosts/raw/master/hosts
除了第一次获取,再也没有更新过,手动点击也没有用

**Comment by oldj** [comment]
感谢反馈，[v3.5.6](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.6) 中这个问题应该修复了。
