### ISSUE TITLE
能否增加预览当前host的功能

### ISSUE THREAD

**Issue by xuoutput** [oldj/SwitchHosts#453]
每次切换host后, 不知道当前host有哪些, 增加显示当前激活了哪些host的功能挺方便的.

**Comment by cssmagic** [comment]
![ui](https://user-images.githubusercontent.com/1231359/88018353-2535cf00-cb5a-11ea-82b5-9f13ed67050f.png)

听起来这个 “System Hosts” 就你需要的？
