### ISSUE TITLE
能否开发.deb版本？

### ISSUE THREAD

**Issue by David-H-1** [oldj/SwitchHosts#457]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Ubuntu 19.10

### SwitchHosts! Version / SwitchHosts! 版本
3.5.4

### Description / 描述
我是个小白，发现怎么弄那个zip文件都没法把它装到我的系统中，解压后连个deb或sh文件都没有，让我怎么下手？？？zip文件是最不适合linux系列的，因为你没有告诉用户到底怎么打开你的程序。
装了node.js，然后呢？？？也没有install或readme文件！对终端用户太不友好了！！！
连个安装说明都没有。一脸懵逼。。。。。。
### How to reproduce / 重现步骤
下载64位zip文件
然后。。。。。。你懂得。。。。。。

**Comment by David-H-1** [comment]
@oldj 大神，到底怎么把那个文件装到我的ubuntu 19.10 上？？？什么安装包也没有啊？

**Comment by oldj** [comment]
可以下载并直接双击运行那个 .AppImage 文件。

.zip 的话，解压后，需要在命令行中运行那个 switchhosts 文件。

**Comment by David-H-1** [comment]
@oldj 可是我解压后，切换到那个解压后的文件夹，在终端（命令行）输入switchhosts运行后提示switchhosts：無此指令

**Comment by ASC8384** [comment]
> @oldj 可是我解压后，切换到那个解压后的文件夹，在终端（命令行）输入switchhosts运行后提示switchhosts：無此指令

try  ` ./switchhosts `
```
 ./switchhosts                     
# maybe you shoule add './' before the command                              
SwitchHosts! HTTP server is listening on port 50761!
-> http://127.0.0.1:50761
getSysHosts: /etc/hosts
```
