### ISSUE TITLE
希望单选模式中可以锁定一个或多个选项，其他未锁定的为单选

### ISSUE THREAD

**Issue by non-trace** [oldj/SwitchHosts#458]
### 描述
因为经常有一个或两个公共的配置，其余的为单选配置，希望单选模式下可以锁定公共的配置，未锁定的配置为单选

**Comment by oldj** [comment]
可以将全局设为多选模式，公共配置放在外层，然后将需要单选的配置放在一个文件夹里，将那个文件夹设为单选。
