### ISSUE TITLE
在线方案提示URL无法访问

### ISSUE THREAD

**Issue by jazzhuang** [oldj/SwitchHosts#46]
是一个内部URL， 浏览器访问是OK的。
如有必要，可以直接联系， 花名- 乐东

**Comment by chengjk** [comment]
浏览器访问时看看源文件，是不是有html相关的标签。这里是工具实际会用的，必须和host格式一致。我是用内部gitlab管理的，路径应该是http://git.dy/pmdr/hosts/raw/master/Prod.hosts。 注意是raw。 还有问题可以联系我。

**Comment by xiaokk06** [comment]
https://raw.githubusercontent.com/racaljk/hosts/master/hosts 在github上找的hosts 浏览器可以正常打开 但是添加作为在线方案的时候出现无法访问的情况 mac上可以正常使用 windows上出现无法访问的情况
