### ISSUE TITLE
SnoreToast开始菜单快捷方式无法删除

### ISSUE THREAD

**Issue by fxzxmic** [oldj/SwitchHosts#467]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Windows10 2004

### SwitchHosts! Version / SwitchHosts! 版本

3.5.4

### Description / 描述

使用一段时间后会自己创建一个SnoreToast开始菜单快捷方式，删除后隔一段时间又会出现

### How to reproduce / 重现步骤

![image](https://user-images.githubusercontent.com/54622331/81383080-02db0a80-9142-11ea-8958-d88c4755b1d6.png)

**Comment by oldj** [comment]
感谢反馈，似乎是用到的第三方通知库 [node-notifier](https://github.com/mikaelbr/node-notifier) 生成的，后续会处理一下。
