### ISSUE TITLE
网盘链接失效

### ISSUE THREAD

**Issue by mengyilingjian** [oldj/SwitchHosts#472]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
windows10 2004

### Description / 描述
网盘链接失效了。

**Comment by oldj** [comment]
果然失效了…… 😰
感谢提醒。

**Comment by oldj** [comment]
现在应该可以访问了。

**Comment by areyouse7en** [comment]
又失效了
![image](https://user-images.githubusercontent.com/3938443/86237820-0d100700-bbcf-11ea-8a58-aeca85d99f3e.png)

**Comment by oldj** [comment]
看来得放弃使用百度网盘分享了…… 😂
