### ISSUE TITLE
系统原有host配置被清空

### ISSUE THREAD

**Issue by Jarvis2018** [oldj/SwitchHosts#481]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

mac 10.15.5

### SwitchHosts! Version / SwitchHosts! 版本

SwitchHosts._macOS_3.5.4.5517.dmg

### Description / 描述

卸载SwitchHosts后，原有的host配置文件被清空

### How to reproduce / 重现步骤

先应用了My host的配置，但是没有应用backup的，到时原有配置被清空，卸载软件后依然不能恢复原有的系统配置

**Comment by oldj** [comment]
卸载的时候，程序不会自动恢复原来的 hosts 。你找一找 `~/.SwitchHosts` 目录，如果没有在卸载时被同时删除的话，里面应该还有 backup 的记录。
