### ISSUE TITLE
需要开机密码能不能去掉

### ISSUE THREAD

**Issue by littlefund** [oldj/SwitchHosts#482]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

mac

### SwitchHosts! Version / SwitchHosts! 版本

v3.5.4 (5517)

### Description / 描述

修改hosts配置让我输入开机密码，能不能去掉这个，神烦

**Comment by oldj** [comment]
如果没有这个，SwitchHosts! 就没有权限修改 /etc/hosts 文件。
一般启动后，只在第一次修改时需要输入密码，后面就不需要输入了吧？

如果实在不喜欢，也可以修改 /etc/hosts 文件的权限，让当前用户直接可写。但一般不建议这么做，因为如果机器上有其他恶意程序，可能也会向 /etc/hosts 写入内容，除非你非常清楚自己在做什么。

**Comment by littlefund** [comment]
了解了，谢谢！
