### ISSUE TITLE
Alfred上无法启动，Error in workflow

### ISSUE THREAD

**Issue by huangsansui** [oldj/SwitchHosts#484]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac

### SwitchHosts! Version / SwitchHosts! 版本

Alfred Workflow SwitchHosts, version = 1.0

### Description / 描述

无法使用SwitchHost的Alfred插件，提示 Error in workflow。端口号未被占用

![image](https://user-images.githubusercontent.com/17234371/88245879-597ccd00-cccb-11ea-8cad-20f48bc56b61.png)

**Comment by oldj** [comment]
可以从 http://www.packal.org/workflow/switchhosts 下载 v1.1.0 版，应该修复这个问题了。

**Comment by huangsansui** [comment]
> 可以从 http://www.packal.org/workflow/switchhosts 下载 v1.1.0 版，应该修复这个问题了。

我重新下载了 V1.1.0 版本，还是一样有问题哈

**Comment by oldj** [comment]
SwitchHosts! 本身是在运行的，对吧？访问 http://127.0.0.1:50761/ ，能看到 `Hello SwitchHosts!` 的文字吗？

**Comment by mayday5555** [comment]
我一开始也提示这个错误，后来发现是没运行

**Comment by xibeilin** [comment]
![image](https://user-images.githubusercontent.com/7733210/121163877-ba7ca780-c881-11eb-9f7f-ffadb03aaeef.png)
