### ISSUE TITLE
Remote hosts 的 Auto refresh 不灵

### ISSUE THREAD

**Issue by cssmagic** [oldj/SwitchHosts#487]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac

### SwitchHosts! Version / SwitchHosts! 版本

3.5.4, 3.5.1

### Description / 描述

添加 Remote hosts，设定 Auto refresh。添加时是可以读取远程文件内容的，但不能按照设定好的时间间隔自动刷新，也没有刷新出错的提示。点击手动刷新按钮无反应。

以前添加过一次 Remote hosts，是可以自动刷新的；后来添加的几条 Remote hosts 又不可以。找不到什么规律。

### How to reproduce / 重现步骤

![SwitchHosts](https://user-images.githubusercontent.com/1231359/88519822-4f3d3480-d025-11ea-88dc-144eedaae9c5.png)

图中红线标出的时间是第一次添加 Remote hosts 的时间。右上角红圈是当前时间。

---

我现在很痛苦，望作者早日定位问题，感谢！

**Comment by cssmagic** [comment]
我好像发现一点规律了：程序重启之后，以前添加的 Remote hosts 就不灵了；每次新建的 Remote hosts 都没有问题（所以测试时很难发现这个 bug）。

**Comment by drw2005** [comment]
确实，我就更新成功过一次，也不知道是什么情况下，突然发现更新成功了。但是后面再更新，就没再成功过了。
不知道到底是什么原因。

**Comment by oldj** [comment]
终于找到原因了，之前的逻辑有点问题，导致文件夹中的远程方案不能刷新（顶层的可以）。

[v3.5.6](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.6) 中这个问题应该已经修复了。

**Comment by cssmagic** [comment]
@oldj 
感谢感谢！感觉自己满血复活了 😆
