### ISSUE TITLE
远程模式无法更新，手动更新也不行。。。

### ISSUE THREAD

**Issue by drw2005** [oldj/SwitchHosts#498]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 7

### SwitchHosts! Version / SwitchHosts! 版本
v3.5.4 (5517)

### Description / 描述
https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
上面的地址就成功过一次，以后再也不更新了，手动也不行，一直提示：远程主机刷新错误。

**Comment by cssmagic** [comment]
Duplicate of #487

**Comment by drw2005** [comment]
> Duplicate of #487
看你的帖子里说的，难道需要每次新建解决这个问题？

**Comment by oldj** [comment]
[v3.5.6](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.6) 中这个问题应该修复了。

**Comment by cssmagic** [comment]
@drw2005 
新版已修复，可以正常使用了 🎉

**Comment by Ca11back** [comment]
> @drw2005
> 新版已修复，可以正常使用了

刚刚更新3.5.6的时候可以了,但我现在又刷新不了了,就点refresh的话,按钮会显示loading,然后又回复到refresh可点击状态,但hosts并没更新,也是这个yhosts,我的stevenblack可以正常用,而且yhosts删了重建也不可以.
