### ISSUE TITLE
SwitchHosts 开关关闭问题

### ISSUE THREAD

**Issue by hyz116** [oldj/SwitchHosts#501]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac 

### SwitchHosts! Version / SwitchHosts! 版本
V 3.5.4.5517

### Description / 描述
例如有 ARK 与 仿真。首先我的环境是在 ARK的，点击 “仿真”后，“仿真”开关打开。但是“ARK”开关没有关闭
![1601199588260](https://user-images.githubusercontent.com/11884897/94361675-bc824a00-00e8-11eb-93c3-dd9432d5e26d.jpg)

### How to reproduce / 重现步骤
见描述

**Comment by oldj** [comment]
默认允许开启多个方案，方便用户组合。如果想一次只开启一个方案，可以在设置中的【选择模式】中选择【单选】。

![image](https://user-images.githubusercontent.com/416130/94361746-48947180-00e9-11eb-8d43-05efe3da987f.png)

**Comment by hyz116** [comment]
ok , It`s work!
