### ISSUE TITLE
启动时出现警告提示

### ISSUE THREAD

**Issue by learn18** [oldj/SwitchHosts#505]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

win10

### SwitchHosts! Version / SwitchHosts! 版本

最新

### Description / 描述

启动时出现警告提示，即使以管理员权限运行也是这样，之前都不会的，不知道什么原因

### How to reproduce / 重现步骤
![image](https://user-images.githubusercontent.com/60352398/95062531-b0713a80-072f-11eb-909b-1b3649812551.png)
只要启动就会这样

**Comment by caixiaomao** [comment]
win10  出现了一样的问题

**Comment by eallion** [comment]
![Snipaste_2020-12-03_23-04-29](https://user-images.githubusercontent.com/1698841/101047916-2f161700-35bd-11eb-92c6-3683eda9071f.png)

**Comment by Second-dimension** [comment]
![Uploading image.png…]()

**Comment by oldj** [comment]
与 #378 重复。在 v3.5.8 中可以关闭 HTTP API 服务，从而避免这个错误。
