### ISSUE TITLE
文件夹方案包含的远程文件不会自动刷新，手动刷新也没有效果

### ISSUE THREAD

**Issue by TanqiZhou** [oldj/SwitchHosts#507]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Win10

### SwitchHosts! Version / SwitchHosts! 版本
3.5.4

### Description / 描述

文件夹方案包含的远程文件不会自动刷新，手动刷新也没有效果

**Comment by oldj** [comment]
感谢反馈，[v3.5.6](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.6) 中这个问题应该修复了。

**Comment by drw2005** [comment]
> 感谢反馈，[v3.5.6](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.6) 中这个问题应该修复了。

下载更新试了一下，确实不再有错误提示，但是刷新后，并没有更新。
用的这个：https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts

**Comment by TanqiZhou** [comment]
OK，完美解决
