### ISSUE TITLE
暗色模式时域名看不到

### ISSUE THREAD

**Issue by non-trace** [oldj/SwitchHosts#508]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Mac

### SwitchHosts! Version / SwitchHosts! 版本
v3.5.1 (5498)

### Description / 描述
<img width="800" alt="图片" src="https://user-images.githubusercontent.com/7167108/97251310-931d2100-1842-11eb-863a-a4d731ee200b.png">

### How to reproduce / 重现步骤

mac  暗色模式

**Comment by oldj** [comment]
[v3.5.5](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.5) 中这个问题应该修复了。

<img src="https://user-images.githubusercontent.com/416130/97277416-69c8b900-1873-11eb-8771-ca93eca7d7ce.png" width="225" alt="">
