### ISSUE TITLE
请问有计划支持苹果芯片的架构吗

### ISSUE THREAD

**Issue by xueyaodeai** [oldj/SwitchHosts#516]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
macOS big sur

**Comment by oldj** [comment]
后续会研究一下的。🙂

**Comment by TooBug** [comment]
试了一下，升级electron到最新版本，就可以直接支持m1芯片了。

但是，由于：

1. 我本地开发时安装依赖有些问题，所以package-lock文件被改到面目全非了，而且仓库中的lock文件用的是v1，我本地是v2
2. 我本地开发时缺少几个依赖：md5-file request cheerio electron-window-state，不确定是否是我打开方式不对

因此，就不发Pull Request了。如有必要可以提供协助。

**Comment by oldj** [comment]
我还没有 m1 芯片的设备，感谢 @TooBug 的反馈，我升级下依赖重新打个包试试。

**Comment by oldj** [comment]
[v3.5.7](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.7) 使用了最新的 electron（v11.2.0）打包， @TooBug  方便看看能在 m1 芯片的设备上运行吗？

**Comment by xueyaodeai** [comment]
> [v3.5.7](https://github.com/oldj/SwitchHosts/releases/tag/v3.5.7) 使用了最新的 electron（v11.2.0）打包， @TooBug 方便看看能在 m1 芯片的设备上运行吗？

<img width="256" alt="image" src="https://user-images.githubusercontent.com/6952857/104436802-fc523c00-55c8-11eb-89c1-82858c6dda62.png">
安装了，看信息还是 intel 架构

**Comment by xueyaodeai** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/6952857/104437903-530c4580-55ca-11eb-97d6-5de92cefa07c.png">
M1 芯片的 MacBook Pro 使用正常，不过简介还是显示 intel 程序

**Comment by xueyaodeai** [comment]
[链接](https://blog.csdn.net/petertanjinjie/article/details/111602647)

看了下这篇文章，m1 芯片应该需要改打包的参数

**Comment by TooBug** [comment]
和 @xueyaodeai 的一样，还是显示intel架构。我在本地开发的时候显示的是apple架构，这里可能确实是打包需要处理一下。

**Comment by oldj** [comment]
根据文档，打包了一个 ARM 的版本： https://github.com/oldj/SwitchHosts/releases/download/v3.5.7/SwitchHosts._mac-arm64.zip ，因为没有 m1 芯片设备，我本地无法运行，哪位有 m1 芯片设备的方便测试一下吗？

**Comment by xueyaodeai** [comment]
我安装了，使用正常，赞一个

**Comment by TooBug** [comment]
显示Apple架构，使用正常+1

**Comment by oldj** [comment]
感谢！ @xueyaodeai @TooBug 🙏
