### ISSUE TITLE
【错误】使用npm install安装项目依赖electron@9.2.1出现TLS错误

### ISSUE THREAD

**Issue by mrluffya** [oldj/SwitchHosts#518]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
macOS 10.13.6(high_sierra)

### SwitchHosts! Version / SwitchHosts! 版本
3.5.5

### Description / 描述
使用npm install安装项目依赖electron@9.2.1出现TLS错误。
~Client network socket disconnected before secure TLS connection was established.~

### How to reproduce / 重现步骤
- 尝试以下方式
  + rm -rf -v node_modules
    * ~npm install electron@9.2.1~
    * ~npm install electron@9.3.0~
    * ~npm install electron@9.3.5~
    * ~npm install electron@10~
    * ~npm install electron@11~

---

_例子@9.2.1（electron@9.2.1）：_
mrluffya ~/Documents/workspaces/git/20201201/SwitchHosts % npm i                  

.> fsevents@1.2.13 install /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/fsevents
.> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.

.> core-js@2.6.11 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/core-js
.> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
.> https://opencollective.com/core-js 
.> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

.> core-js@3.6.5 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/global-agent/node_modules/core-js
.> node -e "try{require('./postinstall')}catch(e){}"

.> ejs@2.7.4 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/webpack-bundle-analyzer/node_modules/ejs
.> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

.> electron@9.2.1 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/electron
.> node install.js

RequestError: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.2.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@9.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mrluffya/.npm/_logs/2020-12-03T09_39_41_415Z-debug.log

---

_例子@11（electron@11）：_
mrluffya ~/Documents/workspaces/git/20201201/SwitchHosts % npm i electron@11 

.> core-js@3.8.0 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/global-agent/node_modules/core-js
.> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
.> https://opencollective.com/core-js 
.> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

.> electron@11.0.3 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/electron
.> node install.js

Downloading electron-v11.0.3-darwin-x64.zip: [==========================] 100% ETA: 0.0 seconds
RequestError: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-import@>=2.18.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-node@>=9.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@11.0.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@11.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mrluffya/.npm/_logs/2020-12-03T09_30_49_940Z-debug.log

### Additional Information / 附加信息
最新情况，请参阅：
[electron#26827](https://github.com/electron/electron/issues/26827#issue-756805140)

本机问题，具体进度详见附加信息，已关闭issues。

**Comment by JasonSubMara** [comment]
我安装 9.3.5 版本后启动App 也出现这个错误，通过cnpm 就解决了是吗？

**Comment by Hotcapsicum** [comment]
> 我安装 9.3.5 版本后启动App 也出现这个错误，通过cnpm 就解决了是吗？

通过cnpm安装依赖，启动项目都是没问题的。但是最后使用electron-builder打包，就会出问题，cnpm安装的依赖会有问题，一直没法解决

**Comment by JasonSubMara** [comment]
> > 我安装 9.3.5 版本后启动App 也出现这个错误，通过cnpm 就解决了是吗？
> 
> 通过cnpm安装依赖，启动项目都是没问题的。但是最后使用electron-builder打包，就会出问题，cnpm安装的依赖会有问题，一直没法解决

我最后打包也是会失败。被迫终止了学习，还没找到解决方按

**Comment by mrluffya** [comment]
> > 我安装 9.3.5 版本后启动App 也出现这个错误，通过cnpm 就解决了是吗？
> 
> 通过cnpm安装依赖，启动项目都是没问题的。但是最后使用electron-builder打包，就会出问题，cnpm安装的依赖会有问题，一直没法解决

最近electron使用TLS1.3安全套件下载资源，默认情况下electron会通过环境变量electron_mirror指定镜像站，尝试更换国内镜像站。
- 具体操作请参考本issues的 Try/尝试解决
