### ISSUE TITLE
这是Bugdows的锅，与我无关，与SwitchHosts!无关

### ISSUE THREAD

**Issue by DilongX** [oldj/SwitchHosts#523]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
10

### SwitchHosts! Version / SwitchHosts! 版本
3.5.6

### Description / 描述
开启了Hyper-V导致大量端口被Hyper-V的网络适配器占用，然后一些软件就打不开了（Android Studio，IDEA等JetBrains系IDE）
故而修改了系统的端口范围来避免端口占用导致的JetBrains系IDE打不开，但修改的这个端口范围却占用了SwitchHosts!使用的端口，导致每次打开SwitchHosts!都会出现下图错误

![image](https://user-images.githubusercontent.com/28427536/102066806-3cd96100-3e35-11eb-9e68-97735f56a083.png)

虽然不是SwitchHosts!的问题但还是想哔哔赖赖一下，我这边再改一下端口范围或许能解决，但我怕又出现新的风暴......不对...是问题，所以如果可以的话希望杰哥看着办吧

**Comment by oldj** [comment]
这个接口其实目前基本只有 Alfred 插件会用到，后面的版本中会提供修改这个端口以及关闭网络服务的设置。
