### ISSUE TITLE
给同一个 host 分别设置 ipv4 和 ipv6，其中一个会因重复被注释掉

### ISSUE THREAD

**Issue by airycanon** [oldj/SwitchHosts#536]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
macOS 11.1

### SwitchHosts! Version / SwitchHosts! 版本
3.5.7

### Description / 描述
给同一个 host 分别设置 ipv4 和 ipv6，其中一个会因重复被注释掉

### How to reproduce / 重现步骤
```
127.0.0.1	localhost
::1             localhost
```

这两个是 /etc/hosts 中自带的，使用 SwitchHosts 保存之后会变成 
```
127.0.0.1	localhost

# invalid hosts (repeated)
# ::1	localhost
```

**Comment by TooBug** [comment]
这个特性是我发的pull request……这里有点不是太明白，同一个域名同时设置ipv4和ipv6的hosts是会同时生效的吗？

**Comment by airycanon** [comment]
> 这个特性是我发的pull request……这里有点不是太明白，同一个域名同时设置ipv4和ipv6的hosts是会同时生效的吗？

我有时候要本地调试代码，会配置一个 127.0.0.1 api.local，但 macOS 有个奇怪的问题，如果不同时配置 ipv6 的话，这个 host 的请求响应会很慢，所以我通常会配置成这样
```
127.0.0.1 api.local
::1 api.local
```
