### ISSUE TITLE
恕我少见多怪，请问现在对小程序的定义是什么？

### ISSUE THREAD

**Issue by gugu33** [oldj/SwitchHosts#539]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

win10 pro

### SwitchHosts! Version / SwitchHosts! 版本

last

### Description / 描述

win安装版100多M算小程序吗？我只想轻松的改个hosts文本文件而已呀
问题1：给管理员权限运行了，依旧不端提示要权限，是因为要对hosts设置可写吗？
问题2：不想下载安装版的，看到便携版也要50多M 忍了，下载下来运行发现时运行时动态解压缩的，这会影响问题1吗？
问题3：是因为要多平台快速开发而用框架，所以多余的 东西一大堆吗？ 我只想改个文本文件而已

### How to reproduce / 重现步骤
同上，见识少勿怪

**Comment by tanghengvip** [comment]
问题1：要管理员权限，也要对hosts文件设置可写，否则会提示没有管理员权限（这个可以优化下
问题2：不会
问题3：不知道，需要开发者来解答一下体积问题 @oldj

**Comment by gugu33** [comment]
谢谢



________________________________
发件人: tanghengvip <notifications@github.com>
发送时间: Monday, January 25, 2021 9:19:53 AM
收件人: oldj/SwitchHosts <SwitchHosts@noreply.github.com>
抄送: gugu33 <samfa33@gmail.com>; Author <author@noreply.github.com>
主题: Re: [oldj/SwitchHosts] 恕我少见多怪，请问现在对小程序的定义是什么？ (#539)


问题1：要管理员权限，也要对hosts文件设置可写，否则会提示没有管理员权限（这个可以优化下
问题2：不会
问题3：不知道，需要开发者来解答一下体积问题 @oldj<https://github.com/oldj>

―

**Comment by oldj** [comment]
关于问题 3 ，是的，因为要跨平台，现在采用了 Electron 进行开发，打包后体积会比较大。😅 不过对现代开发电脑来说，所占用的资源应该是可以接受的。

以前曾经有过 Python 版本（在 Windows 下不到 10M），以及 MacGap 版本（在 macOS 下不到 2M），但因为对应的框架更新太慢或不能跨平台，放弃了。

**Comment by JsonSong89** [comment]
如果你用的是win10 可以用 0.2.2版本 
我也是偶然发现这个项目还在更新,一看安装包50M 哈哈,瞬间不想用了,我不需要跨平台,还是用老版本吧

**Comment by JsonSong89** [comment]
https://www.123pan.com/s/Ww6Ajv-rY7lA.html?提取码:JJyX
