### ISSUE TITLE
系统Hosts显示空白

### ISSUE THREAD

**Issue by hmsjy2017** [oldj/SwitchHosts#542]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10

### SwitchHosts! Version / SwitchHosts! 版本
3.5.6&3.5.7

### Description / 描述
系统Hosts显示空白，使用管理员权限运行仍然显示空白
![捕获](https://user-images.githubusercontent.com/42692274/106537891-35c9f780-6536-11eb-8d97-6df4e62e32db.PNG)

**Comment by jkhuangfu** [comment]
。。不是bug，系统host是你开启选项后的集合，你把下面的myhost或者backup启动一下再看系统的
