### ISSUE TITLE
Someone sells your app in the Mac App Store

### ISSUE THREAD

**Issue by muuvmuuv** [oldj/SwitchHosts#543]
I don't know if this is you, but someone is selling this Software under a different name "HostsWizard". I would be happy to pay for such a nice tool, but I want to give the right author my money ^^. Maybe report that to Apple or if that is you keep the naming and Logo consistent.

> https://apps.apple.com/de/app/hostswizard/id1510312500?mt=12

**Comment by oldj** [comment]
Thank you for your reminder, it's not me. SwitchHosts has been a free software so far, and there is no plan to charge. I will try to report it to Apple.

**Comment by muuvmuuv** [comment]
Maybe change the Licence to something for restricted. With MIT he would be allowed to redistribute and sell that software BUG just with a copyright notice which he does not provide. At least I cannot see any.

**Comment by oldj** [comment]
Now the license of SwitchHosts has been changed to Apache-2.0. 
This is still a very loose license, but if someone else does something with it they should at least indicate where it came from and what they modified. 🙂

**Comment by muuvmuuv** [comment]
Nice! Thanks for this time-saving app btw. Maybe you get your version into the App Store anytime ^^ I hope his got removed, couldn't find it anymore.

**Comment by oldj** [comment]
I am going to close this issue, thank you again for your reminder. 🙂
