### ISSUE TITLE
能不能把 issue 清一下，这么多BUG 啥时候改的完？大部分issue 跟到一半就没有下文了。学学国外项目的issue 跟踪。

### ISSUE THREAD

**Issue by JamesZBL** [oldj/SwitchHosts#545]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

macOS 10.15.7

### SwitchHosts! Version / SwitchHosts! 版本

3.5.6

### Description / 描述

能不能把 issue 清一下，这么多BUG 啥时候改的完？大部分issue 跟到一半就没有下文了。学学国外项目的issue 跟踪。

**Comment by oldj** [comment]
正在开发 v4.0，等 v4.0 发布了会清理一波。
不过这是非盈利项目，背后也没有组织或公司支持，各位贡献者都是业余时间参与，可能 issue 处理不会很及时。😂
