### ISSUE TITLE
data.json文件尺寸大会导致失败

### ISSUE THREAD

**Issue by MonoGlory** [oldj/SwitchHosts#548]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Windows 10 Version 1903

### SwitchHosts! Version / SwitchHosts! 版本

应该是所有

### Description / 描述

当此文件过大时会导致SwitchHosts高占用并长时间假死 之后极大概率会提示使用管理员身份运行 实际是有权限且hosts文件非只读
而当我把导致文件过大的内容（在我使用中为在线hosts）删掉后 此问题消失
所以能否不把在线hosts的内容保存在此文件中 或使用其他解决办法

**Comment by oldj** [comment]
v4.0 中会将每个方案的内容保存到单独的文件中，而不是统一保存到 data.json 文件，应该可以避免或缓解这个问题。
