### ISSUE TITLE
功能实用性改进建议

### ISSUE THREAD

**Issue by jiangzhen3s** [oldj/SwitchHosts#55]
开发者您好：
   首先感谢你们做出这么实用的软件！
   功能上我提一个个人的建议，首先切换方案存在一个问题，它是整个hosts换掉，但如果我只是想其中一部分的映射改掉，剩余的保留当前的映射，当前的设计就很难做到。我觉得这个功能做的好会很赞的.
  谢谢.

**Comment by oldj** [comment]
如果用 Mac 的话，试试 [v3.1](https://github.com/oldj/SwitchHosts/releases) 版？现在支持方案多选了，或许能解决你的问题。
