### ISSUE TITLE
分组不能同时开启

### ISSUE THREAD

**Issue by lya0** [oldj/SwitchHosts#556]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac

### SwitchHosts! Version / SwitchHosts! 版本

4.0

### Description / 描述

分组不能同时开启，是bug还是feture

### How to reproduce / 重现步骤

切换分组

**Comment by oldj** [comment]
有单选和多选模式，在选项里，把选择模式改为【多选】试试？

![image](https://user-images.githubusercontent.com/416130/112927005-e1628300-9146-11eb-8b41-a0cca8f1e2e7.png)

**Comment by lya0** [comment]
@

> 有单选和多选模式，在选项里，把选择模式改为【多选】试试？
> 
> ![image](https://user-images.githubusercontent.com/416130/112927005-e1628300-9146-11eb-8b41-a0cca8f1e2e7.png)

**Comment by lya0** [comment]
是我眼神不好，我还特意翻了好几遍选项，竟然没看到！

**Comment by oldj** [comment]
[v4.0.1](https://github.com/oldj/SwitchHosts/releases/tag/v4.0.1) 开始默认是多选模式了。
