### ISSUE TITLE
4.0版本夜间模式光标看不见

### ISSUE THREAD

**Issue by MaxSherry** [oldj/SwitchHosts#565]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10

### SwitchHosts! Version / SwitchHosts! 版本
4.0正式版

### Description / 描述
设置成夜间模式的情况下，光标看不见在哪儿

**Comment by oldj** [comment]
[v4.0.1](https://github.com/oldj/SwitchHosts/releases/tag/v4.0.1) 中这个问题应该修复了。
