### ISSUE TITLE
问题：最新版本不能开启多个Hosts

### ISSUE THREAD

**Issue by heguohui2018** [oldj/SwitchHosts#569]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

macos

### SwitchHosts! Version / SwitchHosts! 版本

4.4.0

### Description / 描述

不能开启多个host，当开启一个，另一个就会自动关闭，不能同时开启

**Comment by vanishcode** [comment]
选项-选择模式-多选。
p.s 话说为什么默认不是多选啊。。。

**Comment by oldj** [comment]
的确，默认多选可能更符合直觉。下个版本会改成默认多选。

**Comment by heguohui2018** [comment]
原来有多选模式，我才注意到，眼神不好，没注意到。
