### ISSUE TITLE
Mac Dock 图标无法隐藏

### ISSUE THREAD

**Issue by BleuRain** [oldj/SwitchHosts#570]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac Big Sur

### SwitchHosts! Version / SwitchHosts! 版本

v4.0.0(6029)

### Description / 描述

Dock 图标无法隐藏

### How to reproduce / 重现步骤

打开应用 100% 复现

**Comment by oldj** [comment]
是通过托盘图标右键菜单切换的吗？如下图：
![image](https://user-images.githubusercontent.com/416130/115652877-a8da5180-a360-11eb-9f7d-03f48f2f049b.png)

我这儿似乎是正常的，还有其他人遇到一样的问题吗？

**Comment by BleuRain** [comment]
我的问题，没有找到这个，新版本非常好用，感谢感谢
