### ISSUE TITLE
不能同时应用多个hosts

### ISSUE THREAD

**Issue by CxistHans** [oldj/SwitchHosts#572]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
win10

### SwitchHosts! Version / SwitchHosts! 版本
4.0

### Description / 描述
不能同时应用多个hosts，记得之前的版本能的

### How to reproduce / 重现步骤
应用一个hosts，然后想应用另一个，第一个应用的就会被取消

**Comment by oldj** [comment]
可以在选项设置里，将选择模式改为多选。参见 #556 。
