### ISSUE TITLE
Can't select two configurations

### ISSUE THREAD

**Issue by pitichampi** [oldj/SwitchHosts#578]
System : macOS 11.3

SwitchHosts ! Version : v4.0.0 (6029)

Description :
Sorry if this bug has already been reported in Chinese...
I can't select two configurations.
For example I have a local file which describe a main host (ie : 192.168.0.33    mainhost) and a remote file which is automatically generated on the main host with a php script on the mainhost (https://mainhost/hosts.php).
For some reasons (working locally or through a different vpn) I need to change the mainhost and the remote file (ie : 10.144.12.12   mainhost // https://mainhost/hosts.php?vpn=true).
If I select one configuration, the other one is automatically unselected.

Here is an example of my configuration :

![Capture d’écran 2021-05-03 à 13 18 24](https://user-images.githubusercontent.com/1125819/116870091-28dea200-ac12-11eb-9e7e-e6c6df2eb46e.png)

In v4 I can't check two configurations. In v3 I could use two (or more) configurations. 

Here is my conf in v3 :

![Capture d’écran 2021-05-03 à 13 21 20](https://user-images.githubusercontent.com/1125819/116870315-a4d8ea00-ac12-11eb-8815-4d9153eb65c0.png)

**Comment by shohi** [comment]
select "Multiple" Choice mode in configuration

**Comment by pitichampi** [comment]
my bad (◡_◡) ... It works as expected... Many thanks for the answer !

**Comment by oldj** [comment]
In [v4.0.1](https://github.com/oldj/SwitchHosts/releases/tag/v4.0.1) and later versions, "Multiple" will be the default option of choice mode.
