### ISSUE TITLE
hosts文件不存在时 更新失败

### ISSUE THREAD

**Issue by Malcolmli** [oldj/SwitchHosts#579]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
windows10

### SwitchHosts! Version / SwitchHosts! 版本
20H2

### Description / 描述
当C:\Windows\System32\drivers\etc目录下不存在hosts文件 更新失败

### How to reproduce / 重现步骤
删除C:\Windows\System32\drivers\etc目录下hosts文件 更新失败

**Comment by dxkrs** [comment]
同20H2系统，新安装系统，新安装软件，完全无法设置host，开了设置，过一会儿软件也显示关闭

**Comment by oldj** [comment]
应该是 SwitchHosts 对 `C:\Windows\System32\drivers\etc` 目录没有操作权限，无法创建 hosts 文件。这种情况应该只能手动创建一个系统 hosts 文件了，然后再赋予 SwitchHosts 操作这个 hosts 文件的权限。
