### ISSUE TITLE
新版本组合只能选远程配置，不能选本地配置

### ISSUE THREAD

**Issue by Isarg** [oldj/SwitchHosts#584]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
macOS 10.15.7

### SwitchHosts! Version / SwitchHosts! 版本
v4.0

### Description / 描述
新版本组合只能选远程配置，不能选本地配置，换回v3.5.8才行

### How to reproduce / 重现步骤
1、新建一个本地配置，一个远程配置
2、新建一个组合配置，只能看到远程配置，看不到本地配置

**Comment by oldj** [comment]
[v4.0.1](https://github.com/oldj/SwitchHosts/releases/tag/v4.0.1) 中这个问题应该修复了。
