### ISSUE TITLE
小托盘太不友好了

### ISSUE THREAD

**Issue by busyrat** [oldj/SwitchHosts#587]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Mac

### SwitchHosts! Version / SwitchHosts! 版本

v4.0.0 (6025)

### Description / 描述

小托盘在mac多屏和多桌面下使用很不友好，点击顶部的图标后，只能在主屏的主桌面弹出选项框
如果失去了小托盘的便利性，那还不如直接去掉小托盘，每次打开主页，都要点两次

**Comment by oldj** [comment]
和 #571 是不是一个问题呢？[v4.0.1](https://github.com/oldj/SwitchHosts/releases/tag/v4.0.1) 中对 mac 下的托盘图标做了改进，我这里测试似乎正常了，你那边 v4.0.1 还有没有问题呢？

**Comment by billy98** [comment]
4.0.1版本在mac系统 dock上都不显示图标

**Comment by Isarg** [comment]
> 4.0.1版本在mac系统 dock上都不显示图标

右击菜单栏图标，点那个显示/隐藏任务栏图标就可以切换了

**Comment by spwei** [comment]
> > 4.0.1版本在mac系统 dock上都不显示图标
> 
> 右击菜单栏图标，点那个显示/隐藏任务栏图标就可以切换了

还正没注意到这个选项。

**Comment by busyrat** [comment]
> 和 #571 是不是一个问题呢？[v4.0.1](https://github.com/oldj/SwitchHosts/releases/tag/v4.0.1) 中对 mac 下的托盘图标做了改进，我这里测试似乎正常了，你那边 v4.0.1 还有没有问题呢？

没有解决呢，我再描述一下场景：
双屏环境下，主屏在右边，副屏在左
主屏点顶部小图标弹出的小托盘位置正常，小托盘在图标正下方；
但是副屏同样的操作，小托盘出现在主屏的左上角

**Comment by oldj** [comment]
> 没有解决呢，我再描述一下场景：
> 双屏环境下，主屏在右边，副屏在左
> 主屏点顶部小图标弹出的小托盘位置正常，小托盘在图标正下方；
> 但是副屏同样的操作，小托盘出现在主屏的左上角

我这儿双屏下似乎正常，不管主屏还是副屏，小托盘都会出现在鼠标所在屏幕的图标正下方。我的系统是 macOS 11.3.1 ， @busyrat 你的系统版本是什么呢？

**Comment by busyrat** [comment]
> > 没有解决呢，我再描述一下场景：
> > 双屏环境下，主屏在右边，副屏在左
> > 主屏点顶部小图标弹出的小托盘位置正常，小托盘在图标正下方；
> > 但是副屏同样的操作，小托盘出现在主屏的左上角
> 
> 我这儿双屏下似乎正常，不管主屏还是副屏，小托盘都会出现在鼠标所在屏幕的图标正下方。我的系统是 macOS 11.3.1 ， @busyrat 你的系统版本是什么呢？

10.13.6 (17G11023)

**Comment by busyrat** [comment]
系统 升级到11.4 (20F71) switch-host 也更新到v4.0.2 (6057)，问题一样存在

显示器排列：
![image](https://user-images.githubusercontent.com/20984527/120436321-60777000-c3b1-11eb-8667-6d2442fcb1a9.png)


点击副屏（左）顶部的图标，弹框出现在主屏（右）的左上角
![image](https://user-images.githubusercontent.com/20984527/120436122-2017f200-c3b1-11eb-9fbc-f977cb013d50.png)


@oldj
