### ISSUE TITLE
SwitchHosts运行后一片空白

### ISSUE THREAD

**Issue by qingyunluck** [oldj/SwitchHosts#596]
### System (Mac, Windows 7/8/10, Linux) / 操作系统:
windows 10 专业版

### SwitchHosts! Version / SwitchHosts! 版本：
绿色版——最新版本+上一个版本也是一样

### Description / 描述

1. 自从上次点击了最右侧一个按钮，程序就变成空白界面。

### How to reproduce / 重现步骤

重新下载最新版本的绿色版本SwitchHosts，打开程序后还是一片空白。

**Comment by qingyunluck** [comment]
> ### System (Mac, Windows 7/8/10, Linux) / 操作系统:
> windows 10 专业版
> 
> ### SwitchHosts! Version / SwitchHosts! 版本：
> 绿色版——最新版本+上一个版本也是一样
> 
> ### Description / 描述
> 1. 自从上次点击了最右侧一个按钮，程序就变成空白界面。
> 
> ### How to reproduce / 重现步骤
> 重新下载最新版本的绿色版本SwitchHosts，打开程序后还是一片空白。

![image](https://user-images.githubusercontent.com/9709889/119939924-1c572a80-bfc1-11eb-88cf-df99959d8a5f.png)

**Comment by munpf** [comment]
我也是的，更新了之后，不小心点了一下右上角的一个按钮，然后就变成全白色了，重新安装也没用

**Comment by oldj** [comment]
应该是点击了系统托盘图标右键菜单中的【显示/隐藏任务栏图标】，见下图：

![显示/隐藏任务栏图标](https://user-images.githubusercontent.com/416130/120069438-961e0f80-c0b8-11eb-87db-4e4732dd51de.png)


在 Windows 下这个功能有 bug，会造成主窗口界面空白。再点一下那个【显示/隐藏任务栏图标】，然后完全退出 SwitchHosts 再打开，应该就好了。

下个版本会修复这 个问题。

**Comment by oldj** [comment]
试一试 [v4.0.2](https://github.com/oldj/SwitchHosts/releases) ，如果是上面提到的问题，v4.0.2 中应该正常了。

**Comment by munpf** [comment]
> 试一试 [v4.0.2](https://github.com/oldj/SwitchHosts/releases) ，如果是上面提到的问题，v4.0.2 中应该正常了。

我试了一下，还是没有完全解决，我和之前一样点的右上角的一个像是时钟一样的按钮，应该是历史记录吧，然后又变成白屏了，这次不需要点【显示/隐藏任务栏图标】（虽然这个版本已经没有这个按钮了），直接退出重新打开就行了，但还是会变白屏。
![image](https://user-images.githubusercontent.com/27046354/120093279-c662be00-c14b-11eb-9864-6201844e105b.png)

**Comment by qingyunluck** [comment]
刚刚按照你的方式试了，可以正常显示了，谢谢你！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月29日(星期六) 晚上8:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oldj/SwitchHosts] SwitchHosts运行后一片空白 (#596)





 
应该是点击了系统托盘图标右键菜单中的【显示/隐藏任务栏图标】，见下图：
 

 
在 Windows 下这个功能有 bug，会造成主窗口界面空白。再点一下那个【显示/隐藏任务栏图标】，然后完全退出 SwitchHosts 再打开，应该就好了。
 
下个版本会修复这 个问题。
