### ISSUE TITLE
👍 好应用，已收录，感谢开发者！

### ISSUE THREAD

**Issue by macwkcom** [oldj/SwitchHosts#609]
![image](https://user-images.githubusercontent.com/53843550/122955161-842b4600-d3b2-11eb-8947-4763bee90bfb.png)

[收录地址](https://www.macwk.com/soft/switchhosts)

因为并不是多有开发者都需要被宣传，如果开发者觉得不合适，回复我一下，我把它下掉。🥰

**Comment by oldj** [comment]
感谢推荐！😊
