### ISSUE TITLE
建议添加快速注释

### ISSUE THREAD

**Issue by xphwv** [oldj/SwitchHosts#61]
因为工作经常可能会对某个ip切换或者更换本地，建议添加host的行号，每次双击行号可以直接注释当前行，望采纳

**Comment by zhuping** [comment]
顶，希望增加批量注释和查询功能

**Comment by oldj** [comment]
点击行号快速注释的功能，在新版里已添加。如用 Mac 可从 https://github.com/oldj/SwitchHosts/releases/tag/v3.0.0 下载。

Windows 版会在迟一些发出，如需要也可先自行打包。
