### ISSUE TITLE
Hide SwitchHosts from dock, entirely

### ISSUE THREAD

**Issue by martin-braun** [oldj/SwitchHosts#610]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Mac

### SwitchHosts! Version / SwitchHosts! 版本
v3.5.6 (5551)

### Description / 描述
SwitchHosts is great, but it's showing in the dock when it's only resting in the menu bar, thus wasting precious space in my dock. I've seen apps that live in the tray, but still don't waste space on the dock. Can this app be changed to do the same?

### How to reproduce / 重现步骤
Just start, hide to tray and inspect the dock. There it lives: 

<img width="191" alt="Screen Shot 2021-06-25 at 02 19 12" src="https://user-images.githubusercontent.com/24259245/123350673-c2b03480-d55b-11eb-97fc-e1570204612d.png">

**Comment by oldj** [comment]
Click on the icon on tray(or menu bar) and there should be an option to toggle the docker icon on the popup menu, as shown below.

![](https://user-images.githubusercontent.com/416130/123354621-9fef4180-d596-11eb-911e-b2c60b39f603.png)

By the way, version 3.x is no longer updated, you can continue to use these older versions, but it is also recommended to upgrade to the latest version 4.x. 🙂

**Comment by martin-braun** [comment]
Thanks @oldj, I missed this option and also that there are updates. Would've benefited from any sort of notification that version 3 becomes obsolete.

Great work, appreciate it. :)
