### ISSUE TITLE
希望能够修改数据存储目录，以便把数据放入iCloud、OneDrive等云盘备份同步

### ISSUE THREAD

**Issue by jsssk** [oldj/SwitchHosts#620]
![](https://user-images.githubusercontent.com/80049442/126318527-5f7e0786-fc10-427f-8ff1-fe4d17565caf.png)
如图，希望可以修改红圈中的数据存放位置，以便备份同步。

**Comment by lichangwei** [comment]
期待这个功能 +1

**Comment by bigbeef** [comment]
修改后不生效

**Comment by jsssk** [comment]
更新后看到这个功能了，谢谢 @oldj
