### ISSUE TITLE
在 macOS 中显示 hosts 文件只读

### ISSUE THREAD

**Issue by samwangdd** [oldj/SwitchHosts#625]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

macOS Big Sur V11.0.1, MacBook Air (M1, 2020)

### SwitchHosts! Version / SwitchHosts! 版本
v4.0.2 (6057)

### Description / 描述
- 在 macOS 中显示 hosts 文件只读，无法修改
![Screen Shot 2021-08-08 at 10 13 09 AM](https://user-images.githubusercontent.com/29837369/128618565-0a1f58bf-205c-40d9-97b4-da6d9dd5c9bb.png)

- 使用 Alfred 打开，提示 connection refused
![Screen Shot 2021-08-08 at 10 16 08 AM](https://user-images.githubusercontent.com/29837369/128618569-911de000-1a4c-42a3-aa1d-6c35b1f096a9.png)

**Comment by pplmx** [comment]
windows同样的问题

**Comment by chlyyy** [comment]
同样问题

**Comment by oldj** [comment]
系统 hosts 是只读的，显示的是当前系统的 hosts 配置内容，功能设计上就是这样。

要添加/修改 hosts 规则的话，可以点左上角的 `+` 图标新增 hosts 方案。

**Comment by anyforever** [comment]
提示没有写入 Hosts 文件的权限。@oldj

**Comment by RussellCao824** [comment]
> 系统 hosts 是只读的，显示的是当前系统的 hosts 配置内容，功能设计上就是这样。
> 
> 要添加/修改 hosts 规则的话，可以点左上角的 `+` 图标新增 hosts 方案。

系统`/etc/hosts`文件设计就是只读的，然后只能在自己新建的文件中进行编辑，是这个意思吗？

**Comment by oldj** [comment]
> > 系统 hosts 是只读的，显示的是当前系统的 hosts 配置内容，功能设计上就是这样。
> > 要添加/修改 hosts 规则的话，可以点左上角的 `+` 图标新增 hosts 方案。
> 
> 系统`/etc/hosts`文件设计就是只读的，然后只能在自己新建的文件中进行编辑，是这个意思吗？

对，是这个意思。

**Comment by OxYGC** [comment]
同问 怎么修改呢

<img width="445" alt="image" src="https://github.com/oldj/SwitchHosts/assets/26112510/ab621b9e-033f-454e-8e48-49917d16943c">
