### ISSUE TITLE
总是提示没有写入Host的权限

### ISSUE THREAD

**Issue by gy0801151351** [oldj/SwitchHosts#628]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows10

### SwitchHosts! Version / SwitchHosts! 版本
4.0.2.6057

### Description / 描述
![image](https://user-images.githubusercontent.com/16450354/130092922-0ba4c62c-363f-4cc1-abf7-496419018795.png)
问题就如上图所示. 我已经把hosts文件的权限设置成能用当前用户的notepad都能编辑hosts文件了. 为什么用switchhosts还是提示没有权限. 不太明白switchhosts到底要判断哪些文件的哪些权限? 能否给个明确的说明?
![image](https://user-images.githubusercontent.com/16450354/130093512-9f02fe11-df2f-411a-8521-f6f98716384d.png)

**Comment by oldj** [comment]
文件的只读属性也去掉了吗？

**Comment by wf-soft** [comment]
一样，不是只读的问题，文本编辑器都能保存，管理员启动SwitchHosts也没用

**Comment by gy0801151351** [comment]
只读属性早就去掉了, 我没有截那张图, 因为我已经说明了, 用notepad都可以修改hosts文件了. 按理说, 用switchhosts同样也能修改hosts. 但是却得到的是上面的红色提示.

**Comment by gy0801151351** [comment]
我怀疑, switchhosts判断的可能不只一个文件的权限, 也可能是在某些特殊的情况下, 获取到的hosts文件不是系统默认的那个, 当然仅仅是怀疑, 因为我的操作系统是经过多次升级的, 并不是属于完全重装的那种, 里面可能有一些其他的hosts缓存或备份什么的. 具体的需要作者去DEBUG.

**Comment by oldj** [comment]
奇怪，我也暂时没有头绪……

判断是否可写入的权限，是用的 Node.js 的 `fs.access()` 方法，见 [checkAccess()](https://github.com/oldj/SwitchHosts/blob/f9d0e13987e763c2ca5d730f5005f06d9c412f66/src/main/actions/hosts/setSystemHosts.ts#L33) 。不知是哪里出了问题，或者有人知道更好的判断写入权限的方法吗？

**Comment by gy0801151351** [comment]
原因我已经弄清楚了, 是 src/main/actions/hosts/setSystemHosts.ts 代码里的 fs.promises.writeFile(sys_hosts_path, content, 'utf-8') 这行代码触发了操作系统的hosts防篡改保护机制, 被安全软件拦截了. 修改了一下防护策略就可以了. 
但是奇怪, 我用系统自带的notepad和第三方的notepad++都没这种情况...

**Comment by oldj** [comment]
原来是这个原因，感谢反馈！可能是 notepad、notepad++ 等常见文本编辑软件在安全软件的白名单里，安全软件认为通过这些软件修改的话是用户自主的行为，所以没有拦截。

方便介绍一下你的安全软件是哪款以及怎么修改防护策略吗？也许能让其他用户少走一点弯路。🙂

**Comment by wf-soft** [comment]
昨天我也发现，确实是被杀毒软件给拦截了

![image](https://user-images.githubusercontent.com/62228539/130309438-721411c2-8369-4abd-a754-2e43004eea1e.png)
