### ISSUE TITLE
严重bug 其他分组hosts被删除

### ISSUE THREAD

**Issue by installH** [oldj/SwitchHosts#634]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Mac

### SwitchHosts! Version / SwitchHosts! 版本
v4.0.3

### Description / 描述
搜索替换，点击替换所有，其他分组的hosts就全部都没了，要哭了都！！！

**Comment by emoontb** [comment]
相同的问题

**Comment by WhyWhatHow** [comment]
#636

**Comment by oldj** [comment]
搜索功能的确有一个 bug，develop 分支上已经修复，会在下一个版本（v4.1.1）中更新。
