### ISSUE TITLE
刷新remote显示certificate has expired

### ISSUE THREAD

**Issue by duke326** [oldj/SwitchHosts#640]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

Windows10

### SwitchHosts! Version / SwitchHosts! 版本
4.03

### Description / 描述

刷新remote的时候会显示certificate has expired，刷新不成功
![image](https://user-images.githubusercontent.com/52902700/135552384-7d645651-8b30-45df-8c73-cf4cc46fdfd5.png)

**Comment by oldj** [comment]
是 Let's Encrypt 的一个证书在 9 月 30 日到期，如果目标网站使用的是 Let's Encrypt 的证书且没有更新，使用一些客户端请求时就会出现这个问题。

参见：
1. https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
2. https://github.com/electron/electron/issues/31212

**Comment by yansheng836** [comment]
额，不太懂，能问下win出现这个问题，该怎么处理吗？

**Comment by oldj** [comment]
需要对应的网站升级一下 HTTPS 证书，参见[这个帖子](https://community.letsencrypt.org/t/issues-with-electron-and-expired-root/160991/19)。

临时方案可以在本机增加一个环境变量：`NODE_TLS_REJECT_UNAUTHORIZED = '0'` ，不过这样会降低安全性，不建议长期使用。
