### ISSUE TITLE
每次都删系统默认的hosts文件，与其搞那么多花里胡哨的，最基础的功能能不能先搞定？

### ISSUE THREAD

**Issue by snowshoes** [oldj/SwitchHosts#642]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

macOS big sur 11.6

### SwitchHosts! Version / SwitchHosts! 版本

4.0.3

### Description / 描述
已经尝试着安装第三次这个软件了，完全忍不住要吐槽！

第一次以为是我自己笨，不会用，把hosts默认配置项给删了
第二次也是一上来把默认配置项给删了，我只能找到另外一台机器重新抄了遍配置
第三次，还抱着一丝希望，看看能不能愉快玩耍，提前给hosts文件做了备份，果不其然，还是把hosts给删了
后面再配置其他项，再次直接修改hosts已有项

算了已经不抱希望了，删除再见👋

**Comment by oldj** [comment]
选中系统 hosts 时，右上角会有一个时钟图标（见下图），点击可以查看系统 hosts 的历史记录，可以在里面找到之前的 hosts 版本。

![](https://user-images.githubusercontent.com/416130/135616401-6d278b2e-c6dd-450c-a023-92e7a26d9dee.png)

其实 SwitchHosts 的使用方式是将需要的内容添加为各一个方案，如果原来系统 hosts 中有重要内容，可以先建立一个新方案将相关内容添加进来。

当然，这可能对新手不太友好，是一个体验问题。😂
