### ISSUE TITLE
没有写入 Hosts 文件的权限。

### ISSUE THREAD

**Issue by loloxwg** [oldj/SwitchHosts#653]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

win10
### Description / 描述
![image](https://user-images.githubusercontent.com/56066360/139555881-4f3ba712-9281-4f45-bef5-856a64a26bfd.png)

**Comment by Lubin7792** [comment]
mac meto 
At present, only modifying the host file permissions again and again can barely be used
![image](https://user-images.githubusercontent.com/42181595/140896463-e6f5ccc1-e185-4247-952f-ed236302182b.png)

**Comment by Lubin7792** [comment]
每次推出和重启电脑switchhost 都没有权限操作host文件，需要手动改host文件属性，这样太麻烦了 。
请问有什么解决方案么？

**Comment by Lubin7792** [comment]
没有权限是 mac系统文件权限的问题 没有了root 权限
使用了
chown root:admin /private/etc/sudoers
解决了 。。。

**Comment by almas1992** [comment]
> 没有权限是 mac系统文件权限的问题 没有了root 权限 使用了 chown root:admin /private/etc/sudoers 解决了 。。。

issue说的是win10系统，我在win11也遇到了同样问题。

**Comment by almas1992** [comment]
解决方法在 https://github.com/oldj/SwitchHosts/issues/645

**Comment by SJFCS** [comment]
右键以管理员身份打开cmd，执行如下两条命令即可
attrib -s -h -r C:\Windows\System32\drivers\etc\hosts
icacls "%windir%\System32\drivers\etc\hosts" /grant "%USERNAME%:(F)"

**Comment by SJFCS** [comment]
右键以管理员身份打开cmd，执行如下两条命令即可
attrib -s -h -r C:\Windows\System32\drivers\etc\hosts
icacls "%windir%\System32\drivers\etc\hosts" /grant "%USERNAME%:(F)"

**Comment by notagshen** [comment]
> 右键以管理员身份打开cmd，执行如下两条命令即可 attrib -s -h -r %windir%\System32\drivers\etc\hosts icacls "%windir%\System32\drivers\etc\hosts" /grant "%USERNAME%:(F)"

两条命令，win11实测有效，谢谢
