### ISSUE TITLE
希望能新增一个服务器端使用的SwitchHosts

### ISSUE THREAD

**Issue by snakexgc** [oldj/SwitchHosts#654]
#建议
希望能够新增一个服务器上使用的SwitchHosts，那个linux的不能在服务器上运行

**Comment by almas1992** [comment]
> #建议 希望能够新增一个服务器上使用的SwitchHosts，那个linux的不能在服务器上运行

那个运行linux的服务器会使用一个GUI程序？直接vim hosts文件或者shell脚本处理不香麽？

**Comment by wujingquan** [comment]
https://switchhosts.wujingquan.com/ 希望这个可以帮到你。
