### ISSUE TITLE
v4.0.3 windows 10下运行报存在风险

### ISSUE THREAD

**Issue by zjafei** [oldj/SwitchHosts#657]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

windows 10

### SwitchHosts! Version / SwitchHosts! 版本
v4.0.3

### Description / 描述
点击 SwitchHosts_portable_4.0.3.6070.exe windows报威胁

### How to reproduce / 重现步骤
直接双击 SwitchHosts_portable_4.0.3.6070.exe
<img width="422" alt="微信图片_20211125192445" src="https://user-images.githubusercontent.com/8189405/143433992-609bb613-4c7d-4ef4-978f-67b6bd2d4442.png">

**Comment by oldj** [comment]
这个是因为 Windows 版的 exe 程序没有经过代码签名，所以会显示发布者未知。
代码签名证书有一点经济成本，后面会看看有没有合适的方式处理。

**Comment by zjafei** [comment]
ok  
那我就关闭了
