### ISSUE TITLE
没有修改 '/etc/hosts' 的权限

### ISSUE THREAD

**Issue by mycoin** [oldj/SwitchHosts#66]
1、Mac 系统下经常出现

![qq20150416-1 2x](https://cloud.githubusercontent.com/assets/1845440/7173692/e1b8fbee-e42d-11e4-9fb3-e911ed145aaf.jpg)

即使 `/etc/hosts` 的权限已经是 777， 提示输入密码也正确

2、如果 hosts里面有内容，启动的时候报错如下：
![qq20150416-2 2x](https://cloud.githubusercontent.com/assets/1845440/7173708/184e9498-e42e-11e4-9ce3-d7c25880b1d2.jpg)

**Comment by mycoin** [comment]
手工修改 `/etc/hosts` 权限为777，保存报错：
![qq20150417-1 2x](https://cloud.githubusercontent.com/assets/1845440/7194697/4619a4c2-e4e6-11e4-89ec-330fbcece567.jpg)

**Comment by oldj** [comment]
试试 [v3.1](https://github.com/oldj/SwitchHosts/releases) 版？

**Comment by mycoin** [comment]
发现原因了，大概是因为 `公共` 里面的内容太多~ 只保留几行是OK的·

PS： V3.1 很赞

**Comment by oldj** [comment]
老版本不再更新了，欢迎使用新版。

谢谢支持！:)
