### ISSUE TITLE
请问mac10.15系统存储数据的目录具体是什么路径？

### ISSUE THREAD

**Issue by zjq77171** [oldj/SwitchHosts#661]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

mac10.15

### SwitchHosts! Version / SwitchHosts! 版本

v3.5.8

### Description / 描述

请问mac10.15系统存储数据的目录具体是什么路径？

**Comment by LeeBoNorth** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by oldj** [comment]
不是很明白你的问题，如果是问 SwitchHosts 的数据存储在哪里，一般在个人文件夹下的 `~/.SwitchHosts` 目录。

顺便，v3.5.8 已经不更新了，建议升级到 v4 。🙂

**Comment by zjq77171** [comment]
> 不是很明白你的问题，如果是问 SwitchHosts 的数据存储在哪里，一般在个人文件夹下的 `~/.SwitchHosts` 目录。
> 
> 顺便，v3.5.8 已经不更新了，建议升级到 v4 。🙂

情况是这样子的，之前用mac10.15系统安装的v3.5.8版本。系统崩溃了，我把磁盘的内容备份下来了，想找回原来Switchhosts里面的配置，但是我没找到存储数据的目录在哪里？我尝试过恢复这个目录~Library/Application\ Support/switchhosts，但是配置还是没有找回来。

**Comment by oldj** [comment]
那应该就是 `~/.SwitchHosts` 这个目录了，SwitchHosts 的数据目前是保存在这个目录下的。

**Comment by zjq77171** [comment]
> 那应该就是 `~/.SwitchHosts` 这个目录了，SwitchHosts 的数据目前是保存在这个目录下的。

已经找回数据，感谢感谢
