### ISSUE TITLE
win提示没有host写入权限，使用管理员身份打开也不行

### ISSUE THREAD

**Issue by LIANGQI0811** [oldj/SwitchHosts#666]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

win10

### SwitchHosts! Version / SwitchHosts! 版本

4.0.3

### Description / 描述

win提示没有host写入权限，使用管理员身份打开也不行

**Comment by forecloud** [comment]
![image](https://user-images.githubusercontent.com/18623789/145921339-18af8624-d3ad-4138-a090-d3e4ac8a2287.png)
免安装版

**Comment by forecloud** [comment]
修改hosts文件属性,去掉只读权限

**Comment by LIANGQI0811** [comment]
找到问题了，确实是文件本身的问题
