### ISSUE TITLE
【建议】重构 授予管理员权限 模块（在应用程序中使用 `echo '${password}' | sudo -S` 是不安全的

### ISSUE THREAD

**Issue by mrluffya** [oldj/SwitchHosts#676]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
macOS 11.6 Big Sur

### SwitchHosts! Version / SwitchHosts! 版本
v4.0.3 (6070)

#### Expect to happen / 期待发生 #674
重构 授予管理员权限 模块（在应用程序中使用 `echo '${password}' | sudo -S` 是不安全的
Refactoring grants the administrator permission module (using `echo '${password}' | sudo -S` in the application is unsafe
:(

#### Actual to happen / 实际发生
src/main/actions/hosts/setSystemHosts.ts
```ts
...
const writeWithSudo = (
  sys_hosts_path: string,
  content: string,
): Promise<IWriteResult> =>
  new Promise((resolve) => {
    ...
    let cmd = [
      `echo '${sudo_pswd}' | sudo -S chmod 777 ${sys_hosts_path}`,
      `cat "${tmp_fn}" > ${sys_hosts_path}`,
      `echo '${sudo_pswd}' | sudo -S chmod 644 ${sys_hosts_path}`,
      // , 'rm -rf ' + tmp_fn
    ].join(' && ')
    ...
  })
})
...
```

### How to reproduce / 重现步骤
e.g. src/lib/sudoer.js [^1][^2][^3]
```ts
...
class SudoerDarwin extends SudoerUnix {
  ...
  async exec(command, options={}) {
    return new Promise(async (resolve, reject) => {
      let self = this,
        env = self.joinEnv(options),
        sudoCommand = ['/usr/bin/sudo -n', env.join(' '), '-s', command].join(' '),
        result;
      ...
    });
  }
  ...
}
...
```

#### References / 引用
^1. [electron-sudo](https://github.com/automation-stack/electron-sudo)
^2. 此工具于 2017年 停止维护
^3. 暂未发现合适的替代品

**Comment by oldj** [comment]
electron-sudo 这个工具我试过，它似乎不能记住权限，每次切换都要用户再次授权，体验上不是很好。不知是我没找到方法还是它不支持。
