### ISSUE TITLE
Chinese in Eng version on "Set the write mode" screen

### ISSUE THREAD

**Issue by razordynamics** [oldj/SwitchHosts#689]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
MacOS Monterey 12.2.1

### SwitchHosts! Version / SwitchHosts! 版本
4.1.1

### Description / 描述
System language is set to English, app is in English, however when applying a new hosts file, the two radio options for append/overrite on the Set The Write Mode screen are in Chinese instead of English.

### How to reproduce / 重现步骤
Easy to reproduce, try to load a new hosts file with the small toggle button next to it so that you get the write mode screen
<img width="912" alt="Screen Shot 2022-02-21 at 8 18 49 AM" src="https://user-images.githubusercontent.com/4615252/154963490-fe844757-46e3-439e-83cc-3cfe8e6addfc.png">

**Comment by oldj** [comment]
Thanks for the feedback, the changes have been submitted and will be fixed in the next version.

**Comment by razordynamics** [comment]
Thanks! Will mark issue as closed.
