### ISSUE TITLE
自动刷新 功能不生效

### ISSUE THREAD

**Issue by hkargv** [oldj/SwitchHosts#727]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
windows 10

### SwitchHosts! Version / SwitchHosts! 版本
4.1.2

### Description / 描述
设置了 自动刷新 一分钟,然后改一下对应的文件,几分钟过去了,都没有同步过去

### How to reproduce / 重现步骤
用的是chrome浏览器吗?它在非可见情况下,定时器会停止的

**Comment by oldj** [comment]
我这儿似乎可以正常刷新，程序最小化到系统托盘（主界面不可见）的状态也没问题。不知还有其他人遇到这个问题吗？

**Comment by hkargv** [comment]
![QQ截图20220618081637](https://user-images.githubusercontent.com/61319333/174415403-1e747545-3f52-4aa1-8ff1-d142de4732a9.png)

我是这样设置的,修改 d:/docs/hosts 几分钟后都没有更新

**Comment by wjl930526** [comment]
不生效+1，只能手动点刷新

**Comment by wjl930526** [comment]
窗口挂着，不最小化同样不生效

**Comment by hkargv** [comment]
> 窗口挂着，不最小化同样不生效

https://github.com/oldj/SwitchHosts/issues/737  

作者已经确认是BUG了
