### ISSUE TITLE
Mac El Capitan版本下无法使用，一打开就出错

### ISSUE THREAD

**Issue by jinphen** [oldj/SwitchHosts#73]
![image](https://cloud.githubusercontent.com/assets/4998074/11168898/9267b2f2-8bde-11e5-80eb-8967cf8ee006.png)

**Comment by jinphen** [comment]
按这个[issue](https://github.com/oldj/SwitchHosts/issues/36)最后一条最新一条解决了

**Comment by oldj** [comment]
可以试试新版本：https://github.com/oldj/SwitchHosts/releases/tag/v3.0.0 。:)
