### ISSUE TITLE
请问如何开机自启动

### ISSUE THREAD

**Issue by mendax1234** [oldj/SwitchHosts#732]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 10

### SwitchHosts! Version / SwitchHosts! 版本
4.1.2

### Description / 描述
请问如何开机自启动

**Comment by HSK077** [comment]
AppData\Roaming\Microsoft\Windows\Start Menu\Programs\啟動\SwitchHosts
![image](https://user-images.githubusercontent.com/54111827/176946767-f10e6a99-27da-4ed2-abc9-b785ff53039f.png)

**Comment by mendax1234** [comment]
好的，谢谢！
