### ISSUE TITLE
【bug】 windows 7下切换hosts 失败，没有修改‘c:\windows\system32\drivers\etc\hosts’的权限

### ISSUE THREAD

**Issue by wwwzys** [oldj/SwitchHosts#74]
##### 环境
```
windows 7 x86_64
管理员用户
```
##### 错误截图
截图
![switch](https://cloud.githubusercontent.com/assets/5800862/11811366/09f54f48-a370-11e5-8b05-3c51e6eef112.png)

**Comment by jk2K** [comment]
这个网上搜索一下如何修改文件的权限就行了， 不是bug，
