### ISSUE TITLE
不能用啊！！！

### ISSUE THREAD

**Issue by rgbwoo** [oldj/SwitchHosts#75]
下载了3.1，没法用啊，新建的方案无法保存；本来有的hosts配置关闭程序后，得，清空了，一个不剩。还好我有备份，不然悲催了！！！

**Comment by oldj** [comment]
3.1版目前不会自动导入老版本数据，不过老 hosts 配置没有被删除，仍然在 ~/.SwitchHosts 目录下，运行老版本的 SwitchHosts! 可以看到。😁

**Comment by rgbwoo** [comment]
关键是我没有安装过老版本的啊，我都一回用～～～～😢

**Comment by rgbwoo** [comment]
而且也没有 ~/.SwitchHosts 这个目录哦！！！

**Comment by rgbwoo** [comment]
<img width="217" alt="2015-12-21 10 22 15" src="https://cloud.githubusercontent.com/assets/8149176/11921985/c339cb0e-a7cc-11e5-955f-ef7acc6c4a7d.png">

**Comment by oldj** [comment]
呃，第一次打开时应该会自动建一个“backup”方案，里面就是你原来的系统 hosts 的备份。有吗？

![image](https://cloud.githubusercontent.com/assets/416130/11921987/c982d7c6-a7cc-11e5-89e2-4e6db2b92c03.png)

**Comment by rgbwoo** [comment]
![2015-12-21 at 10 27](https://cloud.githubusercontent.com/assets/8149176/11922052/c2337ab0-a7cd-11e5-9440-3d4ec4b7a3ee.png)

刚打开时，backup里面有系统的hosts，然后退出，再打开，backup里面就清空了，连系统hosts也清空了

**Comment by rgbwoo** [comment]
刚再试了试，只要是新建一个自定义的配置，这时退出，再打开程序，hosts就被清空了

**Comment by oldj** [comment]
貌似是没有成功创建 ~/.SwitchHosts 这个目录引起的…

你先手动创建一下这个目录呢？

    mkdir ~/.SwitchHosts

**Comment by oldj** [comment]
貌似是没有成功创建 ~/.SwitchHosts 这个目录引起的…

你先手动创建一下这个目录呢？

    mkdir ~/.SwitchHosts

**Comment by rgbwoo** [comment]
嗯，OK了，果真是这个原因

**Comment by oldj** [comment]
是我疏忽了，会尽快修复。感谢反馈！:)

**Comment by rgbwoo** [comment]
以后有问题向您请教

**Comment by oldj** [comment]
[3.1.0.2514](https://github.com/oldj/SwitchHosts/releases/tag/v3.1) 版中已修复此问题。😄

**Comment by limingAlex1314** [comment]
在哪个目录下创建这个 mkdir ~/.SwitchHosts 这个目录呢

**Comment by oldj** [comment]
> 在哪个目录下创建这个 mkdir ~/.SwitchHosts 这个目录呢

不需要手动创建啊，首次启动时会自动创建的。
