### ISSUE TITLE
希望macos支持开机启动

### ISSUE THREAD

**Issue by wjx0912** [oldj/SwitchHosts#751]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
mac

### SwitchHosts! Version / SwitchHosts! 版本
4.1.2

### Description / 描述
有几次开机忘了打开程序，一些配置同步有问题，导致要用的软件破解失效需要重装。
这么重要的程序，不知道为什么不支持开机启动？技术问题还是有其它考量？

**Comment by adolphor** [comment]
系统偏好设置 -> 用户与群组 -> 登录项，自己添加需要开机启动的程序即可
