### ISSUE TITLE
Toggle between two IPs? 

### ISSUE THREAD

**Issue by simonmeggle** [oldj/SwitchHosts#758]
I have the need to reach "_foohost_" under two different IPs with the same host name. 

    location A => foohost = IP A
    location B => foohost = IP B 

(location B is from external, where I use the great zerotier network) 

I am unsure how to solve this with SwitchHosts. 
My initial idea was to define _foohost_ in "System-Hosts" with IP A and then to define a new entry for IP B. 
And my first naive expectation was that the B entry will simply overwrite the A entry, if activated. 

But by default only the first entry matches (IP A). Even the configuration option "remove duplicated" does not help, because it comments the desired second entry (IP B). 

Creating two entries for IP A and B seems like overkill because it requires me to remember that they can only be used exclusive (A **OR** B). 

**Question: What is the recommended way to implement this toggle with just 1 switch?** 

Side question/feature request: did you think about another option:  

- Remove Duplicates (comment all entries except the first one) 
- Remove Duplicates (comment all entries except the last one)

**Comment by oldj** [comment]
Have you tried the single choice mode?

![CleanShot 2022-10-10 at 16 51 23@2x](https://user-images.githubusercontent.com/416130/194829804-23b355b5-89d0-495c-9a5c-b02f872c1e94.png)


Creating two entries for IP A and B, and set the choice mode to Single, when you open one entry, the other entry (or the rest entries) will be closed automatically.

**Comment by simonmeggle** [comment]
...I knew there is a solution :-) 
Thanks, works as expected! 👍
