### ISSUE TITLE
无法绑定了！

### ISSUE THREAD

**Issue by rgbwoo** [oldj/SwitchHosts#76]
![2015-12-22 at 9 56](https://cloud.githubusercontent.com/assets/8149176/11946161/8fe05130-a892-11e5-817a-aff442dd962d.png)
今天我添加了几个host，发现界面上那个绿色小点无法点击，点击没有响应；
什么情况下会导致这个呢？

**Comment by oldj** [comment]
你用的是哪个版本呢？

看下你的 `~/.SwitchHosts/data.json` 这个文件存不存在，有没有权限？

**Comment by oldj** [comment]
可能是因为你的 sudo 密码中的特殊字符，试试[最新版本（v3.1.0.2601或更新）](https://github.com/oldj/SwitchHosts/releases/tag/v3.1)呢？

**Comment by rgbwoo** [comment]
sudo密码就是普通的字母

**Comment by rgbwoo** [comment]
~/.SwitchHosts/data.json 这个文件存在，还有一个 tmp.txt 是干啥的？
![2015-12-22 at 2 29](https://cloud.githubusercontent.com/assets/8149176/11949305/8833a024-a8b8-11e5-9433-d8304710d0fe.png)

**Comment by oldj** [comment]
tmp.txt 是临时文件，写入系统 `/etc/hosts` 之前，内容会先写在 tmp.txt 里，写入系统 hosts 后就会删除，按理你应该看不见，除非是写入系统 hosts 失败。

使用最新的版本还有问题么？

**Comment by rgbwoo** [comment]
问题找到了。原因是我在浏览issue时看到如下图的issue，照着框里的做了一下修改
![2015-12-23 at 9 40](https://cloud.githubusercontent.com/assets/8149176/11969750/7a3079ce-a959-11e5-956b-a44c822ace37.png)
结果导致进程无法退出了，用kill杀掉进程，重新进入后就正常了。
已经改回原样了。

**Comment by rgbwoo** [comment]
现在看不到 tmp.txt 文件了

**Comment by oldj** [comment]
那个是适用于第二版的配置。第三版里怎么隐藏 dock 图标让我再研究下。:)

**Comment by oldj** [comment]
[v3.1.1.2794](https://github.com/oldj/SwitchHosts/releases) 开始的版本，支持隐藏 Dock 图标了。
