### ISSUE TITLE
feature: 鼠标移动到操作按钮上后, 可否展示一下简短说明

### ISSUE THREAD

**Issue by dfjfj** [oldj/SwitchHosts#760]
### System (Mac, Windows 7/8/10, Linux) / 操作系统

windows 10

### SwitchHosts! Version / SwitchHosts! 版本
v4.1.2

### Description / 描述
易用性增强建议

**Comment by kaimeng110091** [comment]
如题, 当鼠标移动到各个按钮上时, 可否增加一个简单说明, 不然的话, 需要用户手动点击进入可知道是什么作用, 可能会产生不可逆的误操作.

**Comment by kaimeng110091** [comment]
抱歉, 我可能还需要再提一个, 都是easy级别. 设置里边的各个选项, 在排列顺序上稍微调整下吧, [关于]放在底下, [检查更新]放在[关于]的上面, 至于退出按钮, 可以放在你想放的地方, 毕竟其他软件大都是通过失去焦点进行退出的... 谢谢哦. 其他按钮的安排请遵照使用功能, 使用频率来安排, 尽量和其他软件做到一致.
