### ISSUE TITLE
Please add an function: if the `/etc/hosts` file is writable, no SUDO password need.

### ISSUE THREAD

**Issue by tianyu42** [oldj/SwitchHosts#77]
It's great to see this beautiful hosts file manager, thanks a lot!

As a lazy man, it is a little boring that i have to run cmd as a sudoer and input password when i edit the hosts file. So i make the host file writable for me, without password.

I would be grateful if the SwitchHosts stops ask me for a password when i do save or make it enabled.

**Comment by oldj** [comment]
Done!

Just try [v3.1.0.2601](https://github.com/oldj/SwitchHosts/releases/tag/v3.1) or later.

**Comment by tianyu42** [comment]
Cool, you're awesome!

**Comment by krainboltgreene** [comment]
Just an FYI, if the /etc/hosts is writable without sudo then anything can change it, not just SwitchHosts. You're vulnerable to rogue programs.
