### ISSUE TITLE
Windows Electron下打包最小可以达到44M

### ISSUE THREAD

**Issue by ppoffice** [oldj/SwitchHosts#78]
![image](https://cloud.githubusercontent.com/assets/8849362/11995038/b08a4a8c-aa84-11e5-8ef2-03d172e8af9a.png)
![image](https://cloud.githubusercontent.com/assets/8849362/11995045/bb02289a-aa84-11e5-820b-4f3d2ea7863c.png)
![image](https://cloud.githubusercontent.com/assets/8849362/11995049/cd68be68-aa84-11e5-8b44-5b1090de7fa6.png)

如图，通过upx的方式减小了可执行文件的大小（50%左右），同时删去了无用的dll。zip压缩后可以达到23M左右。由于使用旧版本的源码，没有使用压缩js代码，所以还有一点点压缩空间。所以Electron的平台最小大小我觉着还是可以忍受的。

只是一点小小的建议，望采纳。

**Comment by oldj** [comment]
感谢！

你能把你压缩的版本发我参考一下么？我的Email是oldj.wu@gmail.com。

**Comment by ppoffice** [comment]
不好意思，昨晚没有看到。已发。

**Comment by oldj** [comment]
收到，我研究一下，非常感谢！

**Comment by lebornjose** [comment]
同求教electron 压缩 打包

**Comment by HaoYafei-leafy** [comment]
> 不好意思，昨晚没有看到。已发。

同求教electron 压缩 打包，能不能把你的方法和工具，在这里详细描述一下

**Comment by imaginezz** [comment]
> ![image](https://cloud.githubusercontent.com/assets/8849362/11995038/b08a4a8c-aa84-11e5-8ef2-03d172e8af9a.png)
> ![image](https://cloud.githubusercontent.com/assets/8849362/11995045/bb02289a-aa84-11e5-820b-4f3d2ea7863c.png)
> ![image](https://cloud.githubusercontent.com/assets/8849362/11995049/cd68be68-aa84-11e5-8b44-5b1090de7fa6.png)
> 
> 如图，通过upx的方式减小了可执行文件的大小（50%左右），同时删去了无用的dll。zip压缩后可以达到23M左右。由于使用旧版本的源码，没有使用压缩js代码，所以还有一点点压缩空间。所以Electron的平台最小大小我觉着还是可以忍受的。
> 
> 只是一点小小的建议，望采纳。

您好，请问下你用upx压缩以后的版本可以在win10里启动么
