### ISSUE TITLE
feature:能不能添加自动刷新DNS

### ISSUE THREAD

**Issue by Find-NICK** [oldj/SwitchHosts#780]
# feature:能不能添加自动刷新DNS

### 我使用的是*远程*，每次自动刷新hosts后都要手动刷新DNS,不然还是没用

> 刷新DNS

- Windows 下刷新：`ipconfig /flushdns`

- Linux 下刷新: `sudo rcnscd restart`

- MacOS 下刷新: `sudo killall -HUP mDNSResponder`

**Comment by oldj** [comment]
可以把需要运行的命令加在【选项】→【命令】里，每次 hosts 更新后会自动执行。

**Comment by Find-NICK** [comment]
Thank You!
问题已解决



发件人: oldj
发送时间: 2022年11月18日 11:45
收件人: oldj/SwitchHosts
抄送: Find-NICK; Author
主题: Re: [oldj/SwitchHosts] feature:能不能添加自动刷新DNS (Issue #780)

可以把需要运行的命令加在【选项】→【命令】里，每次 hosts 更新后会自动执行。
