### ISSUE TITLE
咨询，远程方案是否会自动更新？

### ISSUE THREAD

**Issue by Mangosteen-Yang** [oldj/SwitchHosts#79]

**Comment by oldj** [comment]
远程方案么？目前不会，只在手动编辑时会更新。

如果添加自动更新的功能，你觉得默认时间间隔多长比较合适呢？

**Comment by Mangosteen-Yang** [comment]
如果可以推送的话，自然是秒级最好。但没见过推送hosts的站点。
抓取的话，默认24小时一次我觉得可以接受，毕竟hosts更新没那么频繁；可人工设置或选择更长更短时间。

**Comment by oldj** [comment]
好的，感谢建议，我考虑一下，应该会在不久后的版本里加上。

**Comment by Mangosteen-Yang** [comment]
好的，谢谢分享。

**Comment by oldj** [comment]
加上了，试试 [v3.1.1.2951或更新版](https://github.com/oldj/SwitchHosts/releases/tag/v3.1) 。:-)

**Comment by Mangosteen-Yang** [comment]
好迅速！已下载，有问题立即反馈，谢谢。

**Comment by Mangosteen-Yang** [comment]
有个小建议，从“从不”更换到其他更新间隔时候更新一次。
我不确定有没有人需求不希望自己文档在更换时候不是最新的，不过如果有这个需求应该也不会开自动更新吧。

**Comment by oldj** [comment]
有道理，我先记下…

**Comment by Mangosteen-Yang** [comment]
好像没有生效，我选择1天，但是两天过去显示的是：上次更新: N/A

**Comment by Mangosteen-Yang** [comment]
BUG:
Version 3.1.1 (2951)
自动更新在所在栏目是更新的，但是没有更新到“系统HOSTS”

**Comment by oldj** [comment]
试试 [v3.1.2.3191](https://github.com/oldj/SwitchHosts/releases/tag/v3.1) 或更新版？

关于`从“从不”更换到其他更新间隔时候更新一次`的问题，貌似直接添加一个手动刷新按钮更直观，于是在编辑界面添的“删除”链接旁边加了一个“刷新”链接，点击即可手动刷新当前方案。

`自动更新在所在栏目是更新的，但是没有更新到“系统HOSTS”`这个 bug 确实存在，在 3191 版之后应该修复了，多谢反馈！:-)
