### ISSUE TITLE
【mac】窗口关闭时，希望移除底部dock栏的图标

### ISSUE THREAD

**Issue by wjx0912** [oldj/SwitchHosts#797]
![截屏2023-01-16 22 24 34](https://user-images.githubusercontent.com/5556482/212700758-5cc0b28c-9046-4075-813e-9fd88618a3ba.png)

谢谢

**Comment by oldj** [comment]
在选项中选中【隐藏任务栏图标】就能隐藏。

![](https://user-images.githubusercontent.com/416130/212708566-d555d4a5-ac7c-4cb2-a48f-45c75d9cb43e.png)
