### ISSUE TITLE
关于Win的64位版本

### ISSUE THREAD

**Issue by StrollStars** [oldj/SwitchHosts#81]
①请问下何时会出64位的Windows版本？毕竟源码编译对一般用户来说还是有点难度。

②64Win7测试2.2.1801版本，发现在线更新URL似乎不支持HTTPS，不知后续版本可有解决这个问题。

③有些是网址形式提供的列表，获取会多出一些HTML代码，建议能够自动过滤这些内容。

**Comment by transtone** [comment]
不用幻想windows版本了，macgap只能在mac下用。

**Comment by StrollStars** [comment]
怪不得那么久没更新了，看来我得寻找其他的替代品。

**Comment by oldj** [comment]
现在使用 Electron 打包，支持 Windows 系统了，试试 [v3.2](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.0) 版？
