### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by cnsilvan** [oldj/SwitchHosts#83]
1 .
 3.0菜单栏不汉化了吗（虽然很简单的单词，但是汉语情结）？
2 .
在线终于支持https了，但是不知道自动更新那个会不会自动去生效？还是只是更新而已？
3 .
发现一个问题 hosts编辑页面右上角的锁会和滚动条重合，无法直接鼠标点击滚动条移动，必须用轮轴下移一点才能用鼠标点击移动

**Comment by oldj** [comment]
1.
是我偷懒了，后续版本会加上… (´･_･`)

2.
如果自动更新的方案是应用状态（绿灯亮），更新后会自动生效的，如果更新后发现没有写权限，会提示输入密码。

3.
一直都是用鼠标软轴滚动，还没注意到这个问题，多谢反馈！
