### ISSUE TITLE
win11怎么配置都不生效

### ISSUE THREAD

**Issue by xingguang12** [oldj/SwitchHosts#836]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
win11

### SwitchHosts! Version / SwitchHosts! 版本

[v4.2.0-beta](https://github.com/oldj/SwitchHosts/releases/tag/v4.2.0-beta)

### Description / 描述
垃圾软件，网上搜了一晚上都配置不上

**Comment by yandp** [comment]
打开hosts文件看看格式是不是UTF-8的，改为ANSI试试，我改了以后就生效了

**Comment by happy-func** [comment]
遇到问题解决问题，有能力协助就提PR，没能力就好好反馈问题。
