### ISSUE TITLE
向`https://swh.app/api/check`发送了大量无效请求

### ISSUE THREAD

**Issue by wang-qa** [oldj/SwitchHosts#839]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Kubuntu 22.04

### SwitchHosts! Version / SwitchHosts! 版本
4.1.2 

### Description / 描述
发送了大量无效请求
![image](https://github.com/oldj/SwitchHosts/assets/58168764/f9ad3f35-5778-41e3-816f-63073f0f9f0a)
![image](https://github.com/oldj/SwitchHosts/assets/58168764/d0df6ce0-aea2-4a09-98a8-27c90283af7b)

### How to reproduce / 重现步骤
sudo journalctl 中搜索

**Comment by oldj** [comment]
swh.app 曾经是这个项目的域名，但因为一些原因这个域名丢失了。

可以下载 [SwitchHosts v4.2.0-beta](https://github.com/oldj/SwitchHosts/releases/tag/v4.2.0-beta) 版，这个版本中已经去掉了对 swh.app 的请求。
