### ISSUE TITLE
[suggest] Is there no shared hosts？ (previously known as common hosts)

### ISSUE THREAD

**Issue by jk2K** [oldj/SwitchHosts#84]
Old version have the common hosts, each scheme can inherit the hosts, haven't it with new version?

btw, Please create a development road map, so convenient know what function need to be developed, and which function as well as being developed

**Comment by oldj** [comment]
In current version you can active multiple schemes at the same time, so it seems that the common hosts is not necessary, you can keep the top(or the first) scheme active and it will work like a shared hosts.
