### ISSUE TITLE
编程语言

### ISSUE THREAD

**Issue by zy416548283** [oldj/SwitchHosts#85]
该项目的编程语言好像不再是python了吧~ 建议将编程语言的分类修改一下~

**Comment by transtone** [comment]
编程分类应该是github自动分的。因为之前的legacy版本是Python的。建议将历史版本放到legacy分支，这样就不会错了。

**Comment by oldj** [comment]
已修改为 JavaScript。

具体做法是添加了 [.gitattributes](https://github.com/oldj/SwitchHosts/blob/master/.gitattributes) 文件，指定：

```
legacy/* linguist-vendored
```

这样 GitHub 在分析编程语言时就会跳过 legacy 目录了。
