### ISSUE TITLE
Win11 提示没有写入权限

### ISSUE THREAD

**Issue by laozl** [oldj/SwitchHosts#858]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Win11

### SwitchHosts! Version / SwitchHosts! 版本

v4.1.2(6086)

### Description / 描述
提示没有写入权限,但是我是使用管理员身份启动的.

**Comment by atmImphy** [comment]
@laozl 应该是Windows/System32/drivers/etc/hosts文件的属性是只读，需要去除只读属性的勾选才行
![hosts 属性_2024-01-08_14-20](https://github.com/oldj/SwitchHosts/assets/7237064/15a9be12-d04f-4056-bd97-457f7047611d)

**Comment by laozl** [comment]
您好,这里已经是非只读了,但是还是不行哦 ![image](https://github.com/oldj/SwitchHosts/assets/43659166/720b64c0-7848-4bdf-b0f4-9ac0e67776f1)

**Comment by laozl** [comment]
目前的Win11 版本是

**Comment by laozl** [comment]
后来 我把原来的 hosts文件文件重命名了,再从桌面新键一个hosts的文件,重新拖进原来的目录,神奇的一幕发生了 居然可以编辑了.好像是由于那个只读旁边的隐藏,我新创建的文件就没有这个隐藏的勾勾

**Comment by jc77411** [comment]
需要修改用户权限
1. 修改文件权限：找到hosts文件的位置（通常位于C:\Windows\System32\drivers\etc\hosts），
在 属性 - 安全 选项卡中 编辑 按钮，然后选择你的用户名，勾选“写入”权限，点击“确定”保存更改
这里可能还会遇到一个问题，没有权限更改权限（哈哈哈哈哈哈哈）
2.用命令提示符授权：
takeown /f C:\Windows\System32\drivers\etc\hosts
icacls C:\Windows\System32\drivers\etc\hosts /grant administrators:F
现在就可以更改了
