### ISSUE TITLE
项目还有人维护么？？？

### ISSUE THREAD

**Issue by pptfz** [oldj/SwitchHosts#859]
项目还有人维护么？？？
项目还有人维护么？？？
项目还有人维护么？？？

**Comment by oldj** [comment]
这个项目基本功能已经稳定了，开发者在忙日常工作，目前对这个项目的关注比较少。如果有重大问题还是会维护更新的。😅

**Comment by pptfz** [comment]
好的 感谢 🙏

**Comment by suyar** [comment]
> 这个项目基本功能已经稳定了，开发者在忙日常工作，目前对这个项目的关注比较少。如果有重大问题还是会维护更新的。😅

@oldj 感谢您的付出，不过希望您有时间可以把beta更新到latest release

您这边可以再项目里放置 Donate 渠道，方便我们肯定您的贡献！
