### ISSUE TITLE
导入之前的直接删除，没有提示

### ISSUE THREAD

**Issue by gh372029002** [oldj/SwitchHosts#887]
太傻逼了，导入之前的直接删除，没有提示，之前的host全没有了

**Comment by zhangsean** [comment]
我也建议不要删除非本项目产生的hosts记录，我用UHE获取的记录在使用SwitchHosts应用变更的时候全部覆盖没了。
可以参照UsbEAm Hosts Editor的做法，在产生host记录后面用#SH做标记，删除或者覆盖的时候只处理有专用标记的行，其他行不要覆盖或删除。

**Comment by oldj** [comment]
选项里可以设置写入模式是追加还是覆盖，而且默认应该是追加模式：

![image](https://github.com/user-attachments/assets/5ba56a72-7b29-415d-9660-29e0530d7f96)

不知是不是你选中了覆盖模式？

**Comment by Leihousuo** [comment]
remote导入的不是默认加在最后吗，不影响原来的行啊
![PixPin_2024-07-29_12-21-16](https://github.com/user-attachments/assets/ccf26533-e467-4530-b949-fc82ae67cd4a)

**Comment by gh372029002** [comment]
并不是啊，mac从菜单栏选择导入直接就覆盖了

**Comment by gh372029002** [comment]
之前下载的3.X版本，3.*版本没有写入模式默认会覆盖，已经更新下载最新版本了！
