### ISSUE TITLE
修改权限后仍无法修改host文件

### ISSUE THREAD

**Issue by li-muz** [oldj/SwitchHosts#888]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
win10

### SwitchHosts! Version / SwitchHosts! 版本
v4.2.0(6105)

### Description / 描述
host文件的权限除了“受限制的应用”全部已修改为可写入和可修改。
并且以管理员方式运行软件。
仍然提示无法修改host文件

### How to reproduce / 重现步骤
点击修改host文件button

**Comment by gongfuture** [comment]
遇到相同问题

**Comment by li-muz** [comment]
根据网友 @gongfuture 的帮助解决了此问题。
解决方法参考 https://github.com/oldj/SwitchHosts/issues/858

**Comment by li-muz** [comment]
突然发现我是888号
幸运数字
