### ISSUE TITLE
3.1 之后还会有 windows 版本吗

### ISSUE THREAD

**Issue by clarkhan** [oldj/SwitchHosts#92]
3.1 的 release log
> Use MacGap instead of Electron
> Windows version will be ready soon.

后续并未发布新版本。
#81 中有其他朋友提到以后不会有 window 版本，请问是确定了吗？

**Comment by oldj** [comment]
是想开发 Windows 版本的，只是时间暂时还不能确定。

主要原因是 3.1 版开始底层用了 MacGap 框架，要移植到 Windows 版会有一些工作量（需要另选一个合适的框架），同时最近几个月工作也比较忙，一直没有大块的时间能投入进来。T_T

**Comment by clarkhan** [comment]
期待更新！

**Comment by tellyou666** [comment]
期待win的新版本。

**Comment by archonwang** [comment]
等Windows版本。期待ing
