### ISSUE TITLE
【建议】开发一个alfred的workflow

### ISSUE THREAD

**Issue by solobat** [oldj/SwitchHosts#93]
手动点图标切换感觉还是有点儿麻烦，希望能有个alfred的workflow。

**Comment by zhoujianlei** [comment]
同求alfred的workflow

**Comment by oldj** [comment]
[v3.3.0](https://github.com/oldj/SwitchHosts/releases/tag/v3.3.0) 中添加了，可以 [点击这儿下载 workflow](https://github.com/oldj/SwitchHosts/releases/download/v3.3.0/SwitchHosts.alfredworkflow) 。
