### ISSUE TITLE
Error code: -65541

### ISSUE THREAD

**Issue by frostbelt** [oldj/SwitchHosts#95]
弹窗提示 Error code: -65541，还关不掉弹窗

**Comment by oldj** [comment]
你用的是哪个版本呢？

**Comment by frostbelt** [comment]
是 3.1.2 版本

发件人:  oldj <notifications@github.com>
答复:  oldj/SwitchHosts <reply@reply.github.com>
日期:  2016年6月3日 星期五 18:41
至:  oldj/SwitchHosts <SwitchHosts@noreply.github.com>
抄送:  yamei <frostbelt@sina.cn>, Author <author@noreply.github.com>
主题:  Re: [oldj/SwitchHosts] Error code: -65541 (#95)


你用的是哪个版本呢？

**Comment by oldj** [comment]
试试 [v3.2](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.0) 版？这个版本使用 Electron 打包，很多代码都重写了。

**Comment by zhenxxin** [comment]
macOS v3.3.12 (5349) 也有同样的报错，不移动鼠标的话，弹窗会堆积在一起（如截图）<img width="356" alt="Screen Shot 2019-04-10 at 09 37 40" src="https://user-images.githubusercontent.com/4496285/57896978-f3561800-7885-11e9-9a3c-02296546b7cf.png">

**Comment by dong4j** [comment]
v3.4.0 同样有这个问题 
macOS 10.14.5
