### ISSUE TITLE
「建议」设置取消 Dock 栏图标 

### ISSUE THREAD

**Issue by devonliu02** [oldj/SwitchHosts#96]
希望能有一个选项，能够设置成不显示 Dock 栏的 SwitchHost! 图标，因为操作基本上都可以通过菜单栏的图标弹出菜单完成或点出编辑界面。

**Comment by oldj** [comment]
<img width="194" alt="tray_menu" src="https://cloud.githubusercontent.com/assets/416130/15990010/01ee249a-30bb-11e6-95a6-3a08e2847894.png">


这个功能有的，试试菜单选项中的“Toggle Dock Icon”。

**Comment by devonliu02** [comment]
哎，是我自己没好好看，的确是这样，麻烦了。谢谢。
