### ISSUE TITLE
通过状态栏图标无法打开主界面

### ISSUE THREAD

**Issue by ElfSundae** [oldj/SwitchHosts#98]
版本 3.1.2 (3464)
系统 OS X 10.11.5 (15F34)

点击状态栏图标里的第一个菜单项，经常性的激活不了主界面。
从状态栏切换hosts，如果需要输入密码，因为激活不了主界面导致切换hosts没反应。

**Comment by LathamZ** [comment]
我也遇到了这个问题  在第一次toggle dock icon之后可以调出来 之后就不行了  哪里逻辑写错了吧？

**Comment by oldj** [comment]
我这边也偶尔会出现，但一直没找到规律，无法稳定重现，暂时未能定位原因…

**Comment by LathamZ** [comment]
本来想帮你找找看的 点开工程发现是js ＋ MacGap 瞬间懵逼 ＝。＝

**Comment by holtenko** [comment]
最近一直打不开了。。。

**Comment by quorzz** [comment]
多次测试  发现只有启动后  第一次正常，再之后就唤不醒主界面了。

重启一下，同样是只有第一次可以。


OSX 10.11.5 (15F34)

v3.1.2.3464

**Comment by holtenko** [comment]
现在不管什么情况都打不开了...重启都不好使......

**Comment by holtenko** [comment]
终于发现了原因了，原来是有别的程序修改了hosts文件，可以把hosts文件清空然后重启switchhosts就可以了，希望对各位有用

**Comment by ElfSundae** [comment]
貌似挺多人遇到这个问题。我刚看了下代码，简单修复了下。 @oldj

**Comment by oldj** [comment]
感谢 @ElfSundae ，我重新 build 了一个版本（v3.1.3.3466），可以点击下面的链接下载：

[https://github.com/oldj/SwitchHosts/releases/download/v3.1/SwitchHosts._v3.1.3.3466_for_mac.zip](https://github.com/oldj/SwitchHosts/releases/download/v3.1/SwitchHosts._v3.1.3.3466_for_mac.zip)

或者：

[https://github.com/oldj/SwitchHosts/releases/tag/v3.1](https://github.com/oldj/SwitchHosts/releases/tag/v3.1)

**Comment by holtenko** [comment]
windows也有这个问题

**Comment by agclqq** [comment]
windows上的这个问题还没能解决吗？

**Comment by ElfSundae** [comment]
Windows 版本在哪下的？
@oldj Windows 源码是 `legacy/v2` ？

**Comment by oldj** [comment]
Windows 版还是使用 Python 写的 v2 版，源码是 `legacy/v2`，v2 版后面不会维护了，现在可以在 [https://pan.baidu.com/s/1inED1](https://pan.baidu.com/s/1inED1) 下载到。

**Comment by ElfSundae** [comment]
刚从网盘下载了个 Windows 版，`v0.2.2.1801` 大概试了下，有时确实不能从系统托盘图标的第一个菜单项激活，不知道你们说的是不是这个问题。

可以试试 **直接双击托盘图标** 来激活主界面，不需要点右键再点第一个菜单项。

**Comment by iam3ddy** [comment]
https://raw.githubusercontent.com/racaljk/hosts/master/hosts

MAC版没问题。Windows 显示### URL无法访问！ ###

**Comment by ElfSundae** [comment]
@iam3ddy https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts

**Comment by iam3ddy** [comment]
@ElfSundae 还是显示### URL无法访问！ ###

**Comment by wclssdn** [comment]
清空hosts文件，重新打开就可以用了~
