### ISSUE TITLE
建议加入“检查更新”功能

### ISSUE THREAD

**Issue by ElfSundae** [oldj/SwitchHosts#99]
建议加入：检查app更新并自动更新

**Comment by ElfSundae** [comment]
貌似已经有了

**Comment by ElfSundae** [comment]
额 上次在代码里看见有检查更新的功能，就关闭 issue 了。
刚才发现有个问题，来这儿一看有新版本了…

可以在 coding.net 上搞个镜像，app内检查更新从 coding 下载。

**Comment by oldj** [comment]
3.2.0 版换成 Electron，代码几乎重写了，检查更新功能还没加上，后面会添加。🙂

**Comment by oldj** [comment]
[v3.2.2](https://github.com/oldj/SwitchHosts/releases) 版里加上了，在「帮助」->「检查更新」里。
